### ISSUE TITLE
Why StatesRebuilder extends State?

### ISSUE THREAD

**Issue by hasimyerlikaya** [GIfatahTH/states_rebuilder#1]
Hi,

Thank you very much for this approach.
I want understanding how it is work. 
When I thinking about your code, I don't understand why StatesRebuilder extends State?
I don't know but maybe we can use without extends State.
Can you explain please?

**Comment by GIfatahTH** [comment]
setState() is annotated as protected, which means that it should only be invoked from instance of a class that extend, implement or mix in State class.

**Comment by hasimyerlikaya** [comment]
I understand. You are right I checked. Thank you.
