### ISSUE TITLE
onError callback in setState method of reactive model is not catching error.

### ISSUE THREAD

**Issue by thisisRinzin** [GIfatahTH/states_rebuilder#100]
onError callback in setState method of reactive model is not reacting to error. catchError flag was set to true.
Output :
E/flutter (25030): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Instance of 'LoginError'
E/flutter (25030): #0      ReactiveModelImp.setState._onErrorCallBack 
package:states_rebuilder/src/reactive_model_imp.dart:343
E/flutter (25030): #1      ReactiveModelImp.setState.<anonymous closure>

**Comment by GIfatahTH** [comment]
@thisisRinzin  thanks for the issue.
>catchError flag was set to true.

It should not throw, can you give more information about your case?

**Comment by thisisRinzin** [comment]
Closing this issue as it's not the problem with the package. 
Thanks for this wonderful package
