### ISSUE TITLE
Getting UI update notifications without relying on the wrapper

### ISSUE THREAD

**Issue by D10100111001** [GIfatahTH/states_rebuilder#108]
I have always used `stated_rebuilder` before v2.0 like this:

```dart
Widget build(BuildContext context) {
  final appConfig = Injector.getAsReactive<AppConfig>(context: context).state;
  return Container();
}
```

I don't want to use the wrapper widgets like StatefulBuilder() or the others. Is it possible to keep the API or allowing for notifications and subscription of changes as it was prior to v2.0?

**Comment by GIfatahTH** [comment]
Using context to subscribe to a model is very simple. But I have found that it adds overweight to me with fewer benefits.

Removing the context subscription gave me more flexibility to add many new features and the internal code is very clean.

Anyway if I found a very concise and compact way to implement it I will add it back.

See #89 for more
