### ISSUE TITLE
[feature] setState, throttled, async value... without waiting

### ISSUE THREAD

**Issue by lukepighetti** [GIfatahTH/states_rebuilder#109]
Hello! I have a use case that looks like this

```dart
  final throttle = Throttle(Duration(milliseconds: 250));

  void search(String e) {
    throttle.run(() async {
      final result = await searchService.searchUsers(e);
      rm.setState((s) => result);
    });
  }
```

Ideally I could do this

```dart
    rm.setState(
      (_) => searchService.searchUsers(e),
      throttleDelay: 250,
      skipWaiting: true,
    );
```

The purpose is to update the model with a throttled async call without showing the loading screen every time.

Thank you

**Comment by GIfatahTH** [comment]
>    rm.setState(
>      (_) => searchService.searchUsers(e),
>      throttleDelay: 250,
>      skipWaiting: true,
>    );

I was thinking of something similar to this. Thanks for the idea.
