### ISSUE TITLE
Assertion failure when I am trying to dispose Bloc instance

### ISSUE THREAD

**Issue by lab-nit-s** [GIfatahTH/states_rebuilder#11]
When I am trying to dispose of the Bloc instance that I Created in either the StatefulWidget's `dispose()` or the `dispose (_) =>` of the Statebuilder. I am getting the below assertion failure.

main Issue is this form below

> flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 1182 pos 12:
> flutter: '_debugLifecycleState == _StateLifecycle.ready': is not true.

Also I can see that the `void initState()` for the `..Bloc extends StatesRebuilder` is never called, hence I thing the issue below.

`flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while finalizing the widget tree:
flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 1182 pos 12:
flutter: '_debugLifecycleState == _StateLifecycle.ready': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      State.dispose (package:flutter/src/widgets/framework.dart:1182:12)
flutter: #3      ChapterThemeBloc.dispose (package:book_app/src/blocs/chapterThemeBloc.dart:94:11)
flutter: #4      _ChapterReaderState.dispose (package:book_app/src/ui/chapterReader.dart:85:23)
flutter: #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3916:12)
flutter: #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1697:13)
flutter: #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #8      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #14     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #20     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4965:16)
flutter: #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #50     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #56     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
flutter: #66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
flutter: #75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #76     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
flutter: #77     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1706:25)
flutter: #78     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2364:27)
flutter: #79     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2196:15)
flutter: #80     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2363:7)
flutter: #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:702:18)
flutter: #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
flutter: #89     _invoke (dart:ui/hooks.dart:219:10)
flutter: #90     _drawFrame (dart:ui/hooks.dart:178:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)`

**Comment by hyperpanthera** [comment]
Show full code snippet.

**Comment by lab-nit-s** [comment]
I have uploaded a gist here:

> https://gist.github.com/lab-nit-s/2090c4d771be521abaf5e2f55973fc8d

When we run it. and go to next page. We can increase the counter using the `CounterBloc` that is written.

But when we press back to go back to root page. We can see that there is an assertion failure.

I tried both paces:

1.  In dispose of `_HomePageState`
2. In dispose of the StateBuilder.

Both places I get the same assertion failure.

Am I doing anything wrong here ???

**Comment by hyperpanthera** [comment]
Your code is wrong.

Make the class "HomePage" a StatelessWidget. Afterwards wrap your entire Scaffold in a StateBuilder. Now put 'CounterBloc counterBloc;' in your CounterBloc class. Finally do _counterBloc = CounterBloc(); in the 'initState' parameter of StateRebuild.

**Comment by lab-nit-s** [comment]
> Your code is wrong.
> 
> Make the class "HomePage" a StatelessWidget. Afterwards wrap your entire Scaffold in a StateBuilder. Now put 'CounterBloc counterBloc;' in your CounterBloc class. Finally do counterBloc = CounterBloc(); in the 'initState' parameter of StateRebuild.

Can you please update the Gist to reflect this. I am not able to understand clearly.

Also,

1. What is the problem with HomePage being Stateful ?
2. I cannot wrap the entire Scaffold always. This doesn't make much sense to me.

Please help.

**Comment by hyperpanthera** [comment]
1. Why do you make HomePage a [StatefulWidget] if you are going to use StateBuilder?

2. Why cannot you? This is how I do it at least. I wrap my main widget in a StateBuilder (I do my initState, dispose, etc. there) and the children also in StateBuilder.

**Comment by hyperpanthera** [comment]
@lab-nit-s I fixed your code.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Flutter Demo",
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        resizeToAvoidBottomInset: false,
        body: RootPage(),
      ),
    );
  }
}

class RootPage extends StatefulWidget {

  @override
  _RootPageState createState() => _RootPageState();
}

class _RootPageState extends State<RootPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Root Page"),),
      body: Center(
        child: RaisedButton(
          child: Text("Go to next page"),
          onPressed: () => Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context) => HomePage()))
        ),
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StateBuilder(
      builder: (State<StatefulWidget> state) {
        return Scaffold(
          appBar: AppBar(title: Text("Detail Page")),
          body: Center(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                StateBuilder(
                  blocs: [counterBloc],
                  builder: (State<StatefulWidget> state) {
                    return Text("Count is ${counterBloc.value}");
                  },
                  stateID: "value",
                ),
                RaisedButton(
                  child: Text("Increase value"),
                  onPressed: () => counterBloc.updateValue();
                )
              ],
            ),
          )
        );
      },
      dispose: (State<StatefulWidget> state) => counterBloc.dispose(),
      initState: (State<StatefulWidget> state) => counterBloc = CounterBloc()
    );
  }
}

CounterBloc counterBloc;

class CounterBloc extends StatesRebuilder {
  int value = 0;
  
  void dispose() {
    counterBloc = null;
  }

  void updateValue() {
    value += 1;
    rebuildStates(["value"]);
  }
}
```

**Comment by GIfatahTH** [comment]
@lab-nit-s 
please update to the latest version and refactor your code to remove any errors. In the 1.1.0 update The method 'dispose' isn't defined for classes that extend `StatesRebuilder`. If you want to use dispose() inside your BloC you have to define it (as done by hyperpanthera).

As mentioned by hyperpanthera, try to use statefullWidget as less as you can.

Now let's look at how to provide the BloC:
1- You instantiate the `CounterBloc` inside the widget. this work for this simple case, but when you have many widgets on different pages and you want to share data between them, this approach fails.

2- hyperpanthera shows you one way of providing the bloc which works very well.

3- There is the InheritedWidget method which is very popular in flutter community. Here is how it looks like:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: "Flutter Demo",
        theme: ThemeData(primarySwatch: Colors.blue),
        home: RootPage());
  }
}

class RootPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Root Page"),
        ),
        body: Center(
          child: RaisedButton(
              child: Text("Go to next page"),
              onPressed: () => Navigator.of(context).push(MaterialPageRoute(
                  builder: (BuildContext context) => HomePage()))),
        ),
        resizeToAvoidBottomInset: false);
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      bloc: CounterBloc(),
      child: Scaffold(
        appBar: AppBar(title: Text("Detail Page")),
        body: new MyBody(),
      ),
    );
  }
}

class MyBody extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final counterBloc = BlocProvider.of<CounterBloc>(context);
    return Center(
      child: Column(
          children: [
            StateBuilder(
                blocs: [counterBloc],
                builder: (State state) {
                  return Text("Count is ${counterBloc.value}");
                },
                stateID: "value"),
            RaisedButton(
                child: Text("Increase value"),
                onPressed: () => counterBloc.updateValue())
          ],
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center),
    );
  }
}

class CounterBloc extends StatesRebuilder {
  int value = 0;

  void updateValue() {
    value += 1;
    rebuildStates(["value"]);
  }
}

```

**Comment by lab-nit-s** [comment]
Thanks for taking your time and explaining. I have now ported my codebase to implement this pattern.
