### ISSUE TITLE
Observe all models without using a List?

### ISSUE THREAD

**Issue by Paradoxu** [GIfatahTH/states_rebuilder#111]
I see that it's possibile to observe more than one Model, by giving a List of Models, to the **observeMany** property when using **StateBuilder**, I'd like to know if there's a way to to have a similar behavior, but not giving a list of all Models, since I have a progress bar that will be visible everytime any of my Models start loading something, if possible I would preferer avoid creare a List of all Models.

**Comment by Paradoxu** [comment]
> If I understand your case, let's say we have two model A and B. We can use nested `StateBuilder` (or `WhenRebuilder`, or `WhenRebuilderOr`) like this:
> 
> ```dart
> WhenRebuilderOr(
>  observe : ()=> RM.get<ModelA>(),
>  onWaiting : () => CircularProgressIndicator(),
>  builder : (context, modelArm) {
>    return WhenRebuilderOr(
>        observe : ()=> RM.get<ModelB>(),
>        onWaiting : () => CircularProgressIndicator(),
>        builder : (context, modelBrm) {
>          ......
> ```
> 
> Every time any of my Models start loading something a progress bar that will be visible.
> 
> You can achieve a similar behavior using `observeMany` with one `StateBuilder`
> 
> ```dart
> WhenRebuilderOr(
>  observeMany : [ ()=> RM.get<ModelA>(),  ()=> RM.get<ModelB>()],
>   // onWaiting callback will be invoked if any of ModelA or ModelB is loading something 
>  onWaiting : () => CircularProgressIndicator(),
>  builder : (context, modelArm) {
> 
>          ......
> ```
> 
> I hope this is your case, if not a little example would be very helpful.

Alright, I read about the observeMany and I have to explicitly give a list of all Models I want to observe, I would like to know, if there's a way, to observe all Models, without having to give a list, if there's some event I can listen to... 

Let's say I have, ModelA, ModelB... ModelZ, I would like something similar:

```
WhenRebuilderOr(
// Here, I don't want to give a list of all models, can't I get the list from the Injector Widget there is on my widget tree os something like that?
 observeMany : RM.get<ModelA>().all(), 
  // onWaiting callback will be invoked if any of ModelA or ModelB is loading something 
 onWaiting : () => CircularProgressIndicator(),
 builder : (context, modelArm) {
```

**Comment by amoslai5128** [comment]
In real world use case, it'd be very wired to use, since you've observed so many Reactive Model inside a Rebuilder Widget, why don't you just put those code within few model.dart?
