### ISSUE TITLE
im trying to move to new screen as soon as i recieve an api response which is in the else condition at the very bottom. but return type is widget. how to move to new screen then?

### ISSUE THREAD

**Issue by sazzad3802** [GIfatahTH/states_rebuilder#112]
`child: StateBuilder(
                observe: () => _store,
                tag: _store.todayTag,
                builder: (_, __) {
                  if(_store.jobResponse == null){
                    return initialUI(loadingStatus: false);
                  } else if(_store.jobResponse.status == ApiStatus.LOADING) {
                    return initialUI(loadingStatus: true);
                  } else if(_store.jobResponse.status == ApiStatus.ERROR) {
                    return initialUI(loadingStatus: false);
                  } else {
//                        _navigateToJobDetail();
                    return null;
                  }
                },
              ),`

**Comment by GIfatahTH** [comment]
navigation is a side effect it should not be inside the builder method.

I can not predict what you are doing here, you may need to refactor to use WhenRebuilder.  Anywhere try
````dart
child: StateBuilder( 
observe: () => _store, 
tag: _store.todayTag,
onSetState: (_,__){
if(_store.jobResponse.status == ApiStatus.LOADED) {
_navigateToJobDetail();
}
},
 builder: (_, __) { 
if(_store.jobResponse == null)
{ return initialUI(loadingStatus: false); }
 else if(_store.jobResponse.status == ApiStatus.LOADING) 
{ return initialUI(loadingStatus: true); } 
else if(_store.jobResponse.status == ApiStatus.ERROR) 
{ return initialUI(loadingStatus: false); } 
else {  return Container(); } }, )
````
