### ISSUE TITLE
Implementation with Localization

### ISSUE THREAD

**Issue by vincent2yui** [GIfatahTH/states_rebuilder#113]
Can you share how to implement localization with states_rebuilder using stateless widget?

I made it work with a stateful widget and now I want to use a stateless widget.

I tried using your example with a stateless widget, but it is not rebuilding or changing.

But when I tried the hot reload, the changes reflect.

**Comment by GIfatahTH** [comment]
I have the intention to do an example with localization in the future.

>I tried using your example with a stateless widget, but it is not rebuilding or changing.

Sorry, I can not help unless I see what you are doing!

**Comment by vincent2yui** [comment]
I tried using this AppLocalization Class
`class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  // Helper method to keep the code in the widgets concise
  // Localizations are accessed using an InheritedWidget "of" syntax
  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  // Static member to have a simple access to the delegate from the MaterialApp
  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  Map<String, String> _localizedStrings;

  Future<bool> load() async {
    // Load the language JSON file from the "lang" folder
    String jsonString =
        await rootBundle.loadString('assets/i18n/${locale.languageCode}.json');
    Map<String, dynamic> jsonMap = json.decode(jsonString);

    _localizedStrings = jsonMap.map((key, value) {
      return MapEntry(key, value.toString());
    });

    return true;
  }

  // This method will be called from every widget which needs a localized text
  String translate(String key) {
    return _localizedStrings[key];
  }
}

// LocalizationsDelegate is a factory for a set of localized resources
// In this case, the localized strings will be gotten in an AppLocalizations object
class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  // This delegate instance will never change (it doesn't even have fields!)
  // It can provide a constant constructor.
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    // Include all of your supported language codes here
    return ['en', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    // AppLocalizations class is where the JSON loading actually runs
    AppLocalizations localizations = new AppLocalizations(locale);
    await localizations.load();
    return localizations;
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
`

And this is UI page
`class LoginBody extends StatelessWidget {
  final TextEditingController usernameTextController = TextEditingController();

  final RMKey passwordRMKey = RMKey<bool>(false);

  @override
  Widget build(BuildContext context) {
    final deviceHeight = RM.mediaQuery.size.height;
    final deviceWidth = RM.mediaQuery.size.width;

    final cardHeight = deviceHeight / 2;
    final cardWidth = deviceWidth / 1.2;
    final loginWidgetWidth = deviceWidth / 1.5;
    final loginPageButtonHeight = deviceHeight / 15;

    return StateBuilder<SettingsService>(
      observe: () => RM.get<SettingsService>(),
      tag: 'translate',
      builder: (context, settingsServiceRM) {
        return Container(
          height: cardHeight,
          width: cardWidth,
          child: Card(
            elevation: kCardElevation,
            margin: EdgeInsets.only(top: 30, bottom: 15),
            shape:
                RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                //Username TextField
                Container(
                  width: loginWidgetWidth,
                  child: TextFormField(
                    controller: usernameTextController,
                    keyboardType: TextInputType.visiblePassword,
                    enableInteractiveSelection: false,
                    style: kLoginPageTextFieldTextStyle,
                    decoration: InputDecoration(
                      labelText: 'Username',
                      suffixIcon: IconButton(
                        icon: Icon(Icons.clear),
                        onPressed: () {
                          usernameTextController.clear();
                        },
                      ),
                    ),
                  ),
                ),
                //Password TextField
                Container(
                  width: loginWidgetWidth,
                  child: StateBuilder<bool>(
                    observe: () => RM.create(false),
                    rmKey: passwordRMKey,
                    builder: (context, passwordRM) {
                      return TextField(
                        keyboardType: TextInputType.visiblePassword,
                        style: kLoginPageTextFieldTextStyle,
                        obscureText: passwordRM.state,
                        decoration: InputDecoration(
                          labelText: 'Password',
                          suffixIcon: IconButton(
                            icon: Icon(
                              passwordRM.state
                                  ? Icons.visibility_off
                                  : Icons.visibility,
                            ),
                            onPressed: () {
                              passwordRM.state = !passwordRM.state;
                            },
                          ),
                        ),
                      );
                    },
                  ),
                ),
                WhenRebuilderOr<AuthenticationService>(
                  observe: () => RM.get<AuthenticationService>(),
                  onWaiting: () => CircularProgressIndicator(
                    valueColor: AlwaysStoppedAnimation<Color>(kPrimaryColor),
                  ),
                  builder: (_, autheticationServiceRM) {
                    return Container(
                      height: loginPageButtonHeight,
                      width: loginWidgetWidth,
                      child: RaisedButton(
                        color: kPrimaryColor,
                        child: Text(
                          'SIGN IN',
                          style: kLoginPageButtonSignInTextStyle,
                        ),
                        shape: RoundedRectangleBorder(
                          side: BorderSide(
                            color: kPrimaryColor,
                            width: 4,
                          ),
                          borderRadius: BorderRadius.circular(30),
                        ),
                        onPressed: () {
                          autheticationServiceRM.setState(
                            (state) => state.signIn(
                              User(username: 'admin1', password: 'admin'),
                            ),
                            onError: ErrorHandler.showErrorDialog,
                            onData: (context, authenticationServiceRM) {
                              debugPrint(
                                  'UI Layer: ${authenticationServiceRM.user.username}');
                            },
                          );
                        },
                      ),
                    );
                  },
                ),
                Container(
                  height: loginPageButtonHeight,
                  width: loginWidgetWidth,
                  child: RaisedButton(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        color: kPrimaryColor,
                        width: 4,
                      ),
                      borderRadius: BorderRadius.circular(30),
                    ),
                    child: Text(
                      settingsServiceRM.state.appLanguage
                          .languageCode, //AppLocalizations.of(context).translate('language'),
                      style: kLoginPageButtonTranslationTextStyle,
                    ),
                    onPressed: () {
                      if (settingsServiceRM.state.appLanguage == Locale("en")) {
                        //Translate to Arabic
                        settingsServiceRM.setState(
                          (state) => state.setAppLanguage(Locale("ar")),
                          filterTags: ['translate'],
                        );
                      } else {
                        //Translate to English
                        settingsServiceRM.setState(
                          (state) => state.setAppLanguage(Locale("en")),
                          filterTags: ['translate'],
                        );
                      }
                    },
                  ),
                )
              ],
            ),
          ),
        );
      },
    );
  }
}
`

**Comment by vincent2yui** [comment]
`import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  // Helper method to keep the code in the widgets concise
  // Localizations are accessed using an InheritedWidget "of" syntax
  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  // Static member to have a simple access to the delegate from the MaterialApp
  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  Map<String, String> _localizedStrings;

  Future<bool> load() async {
    // Load the language JSON file from the "lang" folder
    String jsonString =
        await rootBundle.loadString('assets/i18n/${locale.languageCode}.json');
    Map<String, dynamic> jsonMap = json.decode(jsonString);

    _localizedStrings = jsonMap.map((key, value) {
      return MapEntry(key, value.toString());
    });

    return true;
  }

  // This method will be called from every widget which needs a localized text
  String translate(String key) {
    return _localizedStrings[key];
  }
}

// LocalizationsDelegate is a factory for a set of localized resources
// In this case, the localized strings will be gotten in an AppLocalizations object
class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  // This delegate instance will never change (it doesn't even have fields!)
  // It can provide a constant constructor.
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    // Include all of your supported language codes here
    return ['en', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    // AppLocalizations class is where the JSON loading actually runs
    AppLocalizations localizations = new AppLocalizations(locale);
    await localizations.load();
    return localizations;
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
`

**Comment by vincent2yui** [comment]
**This is the UI Page**
`import 'package:flutter/material.dart';
import 'package:states_rebuilder/states_rebuilder.dart';
import 'package:tnt_scanner/service/settings_service.dart';

import '../../../domain/entities/user.dart';
import '../../../service/common/app_localizations.dart';
import '../../../service/authentication_service.dart';
import '../../../ui/common/constant.dart';
import '../../../ui/exceptions/error_handler.dart';

class LoginBody extends StatelessWidget {
  final TextEditingController usernameTextController = TextEditingController();

  final RMKey passwordRMKey = RMKey<bool>(false);

  @override
  Widget build(BuildContext context) {
    final deviceHeight = RM.mediaQuery.size.height;
    final deviceWidth = RM.mediaQuery.size.width;

    final cardHeight = deviceHeight / 2;
    final cardWidth = deviceWidth / 1.2;
    final loginWidgetWidth = deviceWidth / 1.5;
    final loginPageButtonHeight = deviceHeight / 15;

    return StateBuilder<SettingsService>(
      observe: () => RM.get<SettingsService>(),
      tag: 'translate',
      builder: (context, settingsServiceRM) {
        return Container(
          height: cardHeight,
          width: cardWidth,
          child: Card(
            elevation: kCardElevation,
            margin: EdgeInsets.only(top: 30, bottom: 15),
            shape:
                RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                //Username TextField
                Container(
                  width: loginWidgetWidth,
                  child: TextFormField(
                    controller: usernameTextController,
                    keyboardType: TextInputType.visiblePassword,
                    enableInteractiveSelection: false,
                    style: kLoginPageTextFieldTextStyle,
                    decoration: InputDecoration(
                      labelText: 'Username',
                      suffixIcon: IconButton(
                        icon: Icon(Icons.clear),
                        onPressed: () {
                          usernameTextController.clear();
                        },
                      ),
                    ),
                  ),
                ),
                //Password TextField
                Container(
                  width: loginWidgetWidth,
                  child: StateBuilder<bool>(
                    observe: () => RM.create(false),
                    rmKey: passwordRMKey,
                    builder: (context, passwordRM) {
                      return TextField(
                        keyboardType: TextInputType.visiblePassword,
                        style: kLoginPageTextFieldTextStyle,
                        obscureText: passwordRM.state,
                        decoration: InputDecoration(
                          labelText: 'Password',
                          suffixIcon: IconButton(
                            icon: Icon(
                              passwordRM.state
                                  ? Icons.visibility_off
                                  : Icons.visibility,
                            ),
                            onPressed: () {
                              passwordRM.state = !passwordRM.state;
                            },
                          ),
                        ),
                      );
                    },
                  ),
                ),
                WhenRebuilderOr<AuthenticationService>(
                  observe: () => RM.get<AuthenticationService>(),
                  onWaiting: () => CircularProgressIndicator(
                    valueColor: AlwaysStoppedAnimation<Color>(kPrimaryColor),
                  ),
                  builder: (_, autheticationServiceRM) {
                    return Container(
                      height: loginPageButtonHeight,
                      width: loginWidgetWidth,
                      child: RaisedButton(
                        color: kPrimaryColor,
                        child: Text(
                          'SIGN IN',
                          style: kLoginPageButtonSignInTextStyle,
                        ),
                        shape: RoundedRectangleBorder(
                          side: BorderSide(
                            color: kPrimaryColor,
                            width: 4,
                          ),
                          borderRadius: BorderRadius.circular(30),
                        ),
                        onPressed: () {
                          autheticationServiceRM.setState(
                            (state) => state.signIn(
                              User(username: 'admin1', password: 'admin'),
                            ),
                            onError: ErrorHandler.showErrorDialog,
                            onData: (context, authenticationServiceRM) {
                              debugPrint(
                                  'UI Layer: ${authenticationServiceRM.user.username}');
                            },
                          );
                        },
                      ),
                    );
                  },
                ),
                Container(
                  height: loginPageButtonHeight,
                  width: loginWidgetWidth,
                  child: RaisedButton(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        color: kPrimaryColor,
                        width: 4,
                      ),
                      borderRadius: BorderRadius.circular(30),
                    ),
                    child: Text(
                      settingsServiceRM.state.appLanguage
                          .languageCode, //AppLocalizations.of(context).translate('language'),
                      style: kLoginPageButtonTranslationTextStyle,
                    ),
                    onPressed: () {
                      if (settingsServiceRM.state.appLanguage == Locale("en")) {
                        //Translate to Arabic
                        settingsServiceRM.setState(
                          (state) => state.setAppLanguage(Locale("ar")),
                          filterTags: ['translate'],
                        );
                      } else {
                        //Translate to English
                        settingsServiceRM.setState(
                          (state) => state.setAppLanguage(Locale("en")),
                          filterTags: ['translate'],
                        );
                      }
                    },
                  ),
                )
              ],
            ),
          ),
        );
      },
    );
  }
}
`

**Comment by vincent2yui** [comment]
Apology for the formatting, this is my first time posting a comment in GitHub.

I'm thinking that I might change the App Localization class for this.

**Comment by qhu91it** [comment]
In my case, I need to wait 500ms before call reload (setState) for language change work, because when I change locale and reload immediately, the locale not effect yet and app reload still get old locale so app doesn't change language.

**Comment by vincent2yui** [comment]
> In my case, I need to wait 500ms before call reload (setState) for language change work, because when I change locale and reload immediately, the locale not effect yet and app reload still get old locale so app doesn't change language.

Can you share some sample code you use for this to work? I tried the 500 ms but the it is still the same (maybe I have a different use case)

**Comment by qhu91it** [comment]
Maybe different, I was using library "easy_localization", this is provide enough function I want with no extra class or gen code, just json file.
https://pub.dev/packages/easy_localization


Sorry I just read your code, not sure what is inside of settingsServiceRM, I think rootBundle not refresh when you setState so locale not change
`await rootBundle.loadString('assets/i18n/${locale.languageCode}.json');`
you can set debug in function `translate(String key)` in print current locale and _localizedStrings to know it change or not.

**Comment by vincent2yui** [comment]
Hi Mr. MELLATI Fatah,

Please share us a code snippet for a simple localization in states_rebuilder.

Thank you,
Vincent

**Comment by vincent2yui** [comment]
Managed to fix this by putting my Material App inside the StateBuilder Widget

```
StateBuilder<SettingsService>(
      observe: () => RM.get<SettingsService>(),
      builder: (_, settingsServiceRM) => MaterialApp()
```
