### ISSUE TITLE
Blank screen on bloc example.

### ISSUE THREAD

**Issue by uwejan** [GIfatahTH/states_rebuilder#116]
Am trying to learn the library, and i first started with examples, all seems to work on web. but the bloc example. 
I get white blank screen, please see the screenshot.
Why is that? is it library related?
![statuesREbuilder](https://user-images.githubusercontent.com/20250935/87259681-bdc2b400-c4b5-11ea-80eb-ec47bc6e7824.png)

**Comment by GIfatahTH** [comment]
From the console log you provide I do not see anything related to states_rebuilder here.

**Comment by uwejan** [comment]
@GIfatahTH  All i did is clone the repo and run examples.
Can you at-least run and confirm if this specific example is working please?

**Comment by GIfatahTH** [comment]
Thank you for trying the library and I will re-try the bloc example and see.

**Comment by uwejan** [comment]
@GIfatahTH Hi, any update on this issue. wonder if you had time to test it out?

**Comment by GIfatahTH** [comment]
@uwejan apologize for my late response.

The app works for me on an android simulator.

For web, I added the missing key_value_store_web plugging and test it on chrome using :

> flutter run -t lib/main_web.dart -d chrome 

And it works as intended.
