### ISSUE TITLE
undo redo

### ISSUE THREAD

**Issue by advancedtw** [GIfatahTH/states_rebuilder#121]
I'm planning on porting a project from bloc to states_rebuilder but I'm missing a couple of features the first one is an easy way to undo/redo the state for an observed model (similar to [replay_cubit](https://pub.dev/packages/replay_cubit)) and the second one is a way to hydrate the state automatically although it's not a deal breaker for now. 
Do you have any insight on how I can make states_rebuilder handle state replay? 
thanks a lot

**Comment by GIfatahTH** [comment]
@advancedtw , thank you for opening the issue and getting my attention to undo/redo and hydrate the state features:

In the next release, I will add the undo/redo feature. Here is what it will look like. (I am using the same example as in replay_cubit)

```dart
import 'package:flutter/material.dart';

import 'package:states_rebuilder/states_rebuilder.dart';

class Counter {
  final int count;

  Counter(this.count);

  Counter increment() => Counter(count + 1);

  Counter decrement() => Counter(count - 1);

  Counter reset() => Counter(0);
}
// create a ReactiveModel and set undoStackLength to 8,
//By default undoStackLength  is 0 so that the undo/redo feature is disabled. By setting undoStackLenth to any value, the undo/redo is enabled.
final counterRM = RM.create(Counter(0))..undoStackLength = 8;

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: CounterPage(),
    );
  }
}

class CounterPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final textTheme = Theme.of(context).textTheme.headline2;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Counter'),
        actions: [
          StateBuilder<Counter>(
            observe: () => counterRM,
            builder: (_, __) {
              return IconButton(
                icon: const Icon(Icons.undo),
                onPressed: counterRM.canUndoState ? counterRM.undoState : null,
              );
            },
          ),
          StateBuilder<Counter>(
            observe: () => counterRM,
            builder: (_, __) {
              return IconButton(
                icon: const Icon(Icons.redo),
                onPressed: counterRM.canRedoState ? counterRM.redoState : null,
              );
            },
          ),
        ],
      ),
      body: StateBuilder<Counter>(
        observe: () => counterRM,
        builder: (_, __) {
          return Center(
              child: Text('${counterRM.state.count}', style: textTheme));
        },
      ),
      floatingActionButton: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        mainAxisAlignment: MainAxisAlignment.end,
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              child: const Icon(Icons.add),
              onPressed: () => counterRM.setState((s) => s.increment()),
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              child: const Icon(Icons.remove),
              onPressed: () => counterRM.setState((s) => s.decrement()),
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              child: const Icon(Icons.delete_forever),
              onPressed: () => counterRM
                ..setState((s) => s.reset())
                ..clearUndoStack(),
            ),
          ),
        ],
      ),
    );
  }
}
```

Do you have any comment?

For hydrating the state, I am not aware of its use case. Can you show me how useful it is?

**Comment by advancedtw** [comment]
first of all thank you for considering these features and for your continuous support.

concerning state replay the api is perfectly adequate. personally I would skip the canUndo/canRedo checks and simply throw an exception or return the state and log a warning letting the developer know the reactive model is not setup for undo/redo. 
An other thing that might be useful is a way to dump the replay stack (possibly a stream) and initialize the stack. that can be handy for web apps or when the application has been closed. that is somewhat tied to hydration.

Now for state hydration/persistence i can see multiple viable scenarios:
- web apps/desktop apps: the user is likely to be logged out at some point. it's nice to be able to continue where you left out.
- easy caching : if the state is persisted there is no need to always fetch remote data.
- syncing between users:  this can be achieved using [aws appsync](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-delta-sync.html) with DeltaSync queries.

all the above scenarios can already be achieved with custom hooks in service classes. state hydration just makes it automatic and eliminates repetitive boilerplate. 

let me know what you think.

**Comment by advancedtw** [comment]
actually forget about the "skip the canUndo/canRedo part" I didn't take in consideration that canUndo will also be false when the top of the stack has been reached for some reason I thought it was to check if the replay functionality was enabled.

**Comment by GIfatahTH** [comment]
@advancedtw 
Better late than never. I added the feature of state hydration/persistence. see there #134
