### ISSUE TITLE
VSCode - Exceptions cannot catch up at time sometimes

### ISSUE THREAD

**Issue by amoslai5128** [GIfatahTH/states_rebuilder#122]
Dear GIfatahTH,

Recently I'm practising a Cubit Weather App example from RosaCode, then I rewrote by StatesRebuilder as a practice, and the states_builder's version was very satisfying on the performance 🥇.

However, I've noticed that even setState(catchError: true) / onError, after the same exceptions have been throwing for several times, the app broke.

Should be:
![image](https://user-images.githubusercontent.com/30002046/90765818-2f93e600-e31d-11ea-8f49-91b419a75f9a.png)

When running on Debug mode. the exception sometimes doesn't catch up and throw an Exception breakpoint in VSCode (suppose it should be a spacebar).  However, neither I setState cathchError: true and onError:  , the vscode throws breakpoint still.

![image](https://user-images.githubusercontent.com/30002046/90765916-53efc280-e31d-11ea-8d60-3794d43d9a7d.png)

And this issue only appeared on states_rebuiller. I don't know it should be correct or a potential issue. 

I put two examples of the WeatherApp in here, many thanks!

Here are two simples source code: https://github.com/amoslai5128/two_exmples_errors_inWeatherApp

Many thanks.

**Comment by GIfatahTH** [comment]
@amoslai5128 hello and sorry for my late response. 

This behavior is expected, as with Cubit the error is caught:

```dart
Future<void> getWeather(String cityName) async {
    try {
      emit(WeatherLoading());
      final weather = await _weatherRepository.fetchWeather(cityName);
      emit(WeatherLoaded(weather));
    } on NetworkException {
      emit(WeatherError("Couldn't fetch weather. Is the device online?"));
    }
  }
```

In the case of state_rebuilder the error is thrown
```dart
  static Future<WeatherState> getWeather(
      WeatherState state, String cityName) async {
    try {
      final _newWeather = await state._weatherRepository.fetchWeather(cityName);
      return state.copyWith(weather: _newWeather);
    } catch (e) {
      throw WeatherError("Couldn't fetch weather. Is the device online?");
    }
  }
```

and the error is caught later, but vscode considers the first throw as an uncaught exception.

Disabling uncaught exceptions will not stop the code.

**Comment by amoslai5128** [comment]
> @amoslai5128 hello and sorry for my late response.
> 
> This behavior is expected, as with Cubit the error is caught:
> 
> ```dart
> Future<void> getWeather(String cityName) async {
>     try {
>       emit(WeatherLoading());
>       final weather = await _weatherRepository.fetchWeather(cityName);
>       emit(WeatherLoaded(weather));
>     } on NetworkException {
>       emit(WeatherError("Couldn't fetch weather. Is the device online?"));
>     }
>   }
> ```
> 
> In the case of state_rebuilder the error is thrown
> 
> ```dart
>   static Future<WeatherState> getWeather(
>       WeatherState state, String cityName) async {
>     try {
>       final _newWeather = await state._weatherRepository.fetchWeather(cityName);
>       return state.copyWith(weather: _newWeather);
>     } catch (e) {
>       throw WeatherError("Couldn't fetch weather. Is the device online?");
>     }
>   }
> ```
> 
> and the error is caught later, but vscode considers the first throw as an uncaught exception.
> 
> Disabling uncaught exceptions will not stop the code.

Yes, the errors can be caught at the first 3~4 times, while it will be uncatchable after then.

**Comment by GIfatahTH** [comment]
> Yes, the errors can be caught at the first 3~4 times, while it will be uncatchable after then.

I do not understand what you mean here.

**Comment by amoslai5128** [comment]
Thanks it works
