### ISSUE TITLE
GLOBAL FUNCTIONAL INJECTION makes your life easier!!! [New Feature]

### ISSUE THREAD

**Issue by GIfatahTH** [GIfatahTH/states_rebuilder#123]
To inject dependency in `states_rebuilder`, we are used to use the Injector widget:
* `Injector` widget (old approach):
    * Injection
        ```dart
        Injector(
            inject : [Inject(()=>Foo())]
            builder:(context)=> MyWidget(),
        )
        ```
    * To consume an injected model:
        ```dart
        final ReactiveModel<Foo> fooRM = RM.get<Foo>();
        //to get the state
        final Foo foo = fooRM.state;
        //to set the state
        fooRM.setState((s)=> ....);
        ```
  *  In test we can inject a fake implementation fo `Foo`.
        ```dart
        Injector.enableTestMode = true;
        Injector(
            inject : [Inject(()=>FooFake())] //inject FooFake
            builder:(context)=> MyWidget(),
        )
        ```

* Now Global Functional injection comes to make our life easier:
    * Injection:

        ```dart
        //Although foo is global, the state is not.
        //The state is automatically cleaned when no longer used.
        //The state is easily mocked and tested
        final Injected<Foo> foo = RM.inject(()=> Foo());
        ```
    * To consume an injected model:
        Use the global `foo` variable
        ```dart
        //to get the state
        final Foo foo = foo.state;
        //to set the state
        foo.setState((s)=> ....);
        ```
    * In test we can inject a fake implementation fo `Foo`.
        ```dart
        //Using a fake implementation of Foo in test
        foo.injectMock(()=> FooFake())
        ```

Global functional injection, use good global variables, not evil ones. They are accessible from anywhere, making them practical and useful at the same time the state they refer to is cleaned up when not in use and it is easily mocked and tested.

Let's see the hello counter app with global functional injection:

First, create a global counter variable and inject a "0".
```dart
 final Injected<int> counter = RM.inject<int>(() => 0);
```

and simply use it in the UI:

```dart
class CounterApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      //Subscribe using rebuilder method
      child: counter.rebuilder(
        () => Text('${counter.state}'),
      ),
    );
  }
}
```
* To get the current state of the counter, we use the `state` getter:
    ```dart
    final int counterState = counter.state;
    ```
* To subscribe to the counter, we use the `rebuilder` of Injected counter:
    ```dart
    counter.rebuilder(
        () => Text('${counter.state}'),
    )

    //This is exactly equivalent to :
    StateBuilder(
        observe: ()=> counter.getRM,
        builder: (context, counterRM) => Text('${counter.state}'),
    )
    ```
To change the value of the counter and notify observers we use setState method. As the counter is a global variable we can call it anywhere:

Let see that with the test.

```dart
void main() {

  testWidgets('First test : should increment counter', (tester) async {
    await tester.pumpWidget(CounterApp());
    // Initial value
    expect(find.text('0'), findsOneWidget);
    //Increment and notify observers
    counter.state++;
    //Typically called inside onPressed callback of a button
    // RaisedButton(
    //    onPressed: ()=> counter.state++,
    //    child: ...
    //)
    //
    await tester.pump();
    //the counter is incremented and the widget is refreshed to display it.
    expect(find.text('1'), findsOneWidget);
  });

  //Even if you run all tests, the two tests are independent
  //This shows that the even counter is global, its state is not.
  testWidgets('Second test: should increment counter', (tester) async {
    await tester.pumpWidget(CounterApp());
    //
    //If the state is global, it will fail while running all tests
    expect(find.text('0'), findsOneWidget);
    //
    counter.state++;
    await tester.pump();
    expect(find.text('1'), findsOneWidget);
  });
}
```

This is just the tip of the iceberg. Please go here [link](https://github.com/GIfatahTH/states_rebuilder/wiki/00-functional_injection) to see more general function injection in detail.

**Comment by AleFachini** [comment]
Great, Job. I am learning and i found all the examples so i did not get what was new and what was old but no this article helped me. please keep maintaining i am going to use this as my main state management package together with BLoC package. Your work is really appreciated!!!

**Comment by GIfatahTH** [comment]
Thank you. Any remark or any kind of contribution is welcome.

**Comment by AleFachini** [comment]
Hello:
I am confused about this:
in some examples for functional global Injection you use 
```
 final Injected<int> counter = RM.inject<int>(() => 0,
 );
```

But in other examples you use

`final counter = RM.inject(() => CounterStore(0));`

and i dont know what is different? and which is newer or more recommended

**Comment by GIfatahTH** [comment]
Hi;

Examples are just examples, they simplify a common scenario, and  two different examples cannot be compared.:

This example : 
```
 final Injected<int> counter = RM.inject<int>(() => 0);
```
represents all primitive Enums and immutable.
you can replace it by:
```
 final Injected<String> email= RM.inject<Strings>(() =>'email@email.com');
 final Injected<double> price= RM.inject<double>(() =>2.5);

and so on ...
```

Whereas,

```
final counter = RM.inject(() => CounterStore(0));
```

represents custom objects:

```
final user= RM.inject(() => User());
final repo= RM.inject(() => Repository());
final auth= RM.inject(() => AuthenticationService());
```

**Comment by reidterror** [comment]
How can this be used with the auto login example?

**Comment by GIfatahTH** [comment]
@reidterror see this example 
https://github.com/GIfatahTH/states_rebuilder/tree/dev/examples/ex_009_1_4_ca_todo_mvc_with_state_persistence_and_user_auth

**Comment by amoslai5128** [comment]
Hey @GIfatahTH, thanks for your library, it does make my life easier, and I've a question about:

How can I use `RM.injectComputed` to compute async tasks?  
I cannot use async into `compute: async {}', however, how should I use computeAsync instead?

`
```
final activeFilterX = RM.inject(() => FilterEnum.None);

// itemFilteredResultX should get the corresponding repository' APIs according to the activeFilterX state
final itemFilteredResultX = RM.injectComputed<List<Item>>(compute: (_)  {

  if (activeFilterX.state == FilterEnum.ByDate) {
     return await **repositoryA**.state.getItems(stateA.state.id);
  }
  if (activeFilterX.state == FilterEnum.ByName) {
    return await **repositoryB**.state.getItems(stateA.state.id);
  }
  return stateA.state;
});
```

**Comment by AleFachini** [comment]
Hello Still maintaining package? 2 months without updates? is there a discord slack channel?

**Comment by GIfatahTH** [comment]
@AleFachini Yes, the package is still maintained. Now I am working on refactoring of the library to migrate to null safety, meanwhile I plan to catch the occasion and do some breaking changes.

**Comment by GIfatahTH** [comment]
@amoslai5128 
>How can I use RM.injectComputed to compute async tasks?
I cannot use async into `compute: async {}', however, how should I use computeAsync instead?

In the next update, I will remove the RM.injectComputed. 

Instead all Injected can be computed.

```dart

final activeFilterX = RM.inject(() => FilterEnum.None);

//It will change the state after activeFilterX changed
final itemFilteredResultX = RM.injectFuture<List<Item>>(
  () async {
    if (activeFilterX.state == FilterEnum.ByDate) {
      return await repositoryA.state.getItems(stateA.state.id);
    }
    if (activeFilterX.state == FilterEnum.ByName) {
      return await repositoryB.state.getItems(stateA.state.id);
    }
    return stateA.state;
  },
 //Here how the dependence will bi declared
  dependsOn: DependsOn({activeFilterX}),
);
```

**Comment by amoslai5128** [comment]
> @amoslai5128
> 
> > How can I use RM.injectComputed to compute async tasks?
> > I cannot use async into `compute: async {}', however, how should I use computeAsync instead?
> 
> In the next update, I will remove the RM.injectComputed.
> 
> Instead all Injected can be computed.
> 
> ```dart
> final activeFilterX = RM.inject(() => FilterEnum.None);
> 
> //It will change the state after activeFilterX changed
> final itemFilteredResultX = RM.injectFuture<List<Item>>(
>   () async {
>     if (activeFilterX.state == FilterEnum.ByDate) {
>       return await repositoryA.state.getItems(stateA.state.id);
>     }
>     if (activeFilterX.state == FilterEnum.ByName) {
>       return await repositoryB.state.getItems(stateA.state.id);
>     }
>     return stateA.state;
>   },
>  //Here how the dependence will bi declared
>   dependsOn: DependsOn({activeFilterX}),
> );
> ```

Thank you, also I wanna know can it be possible to wrap the `CircularProgressIndicator()` into the onWaiting from` RM.inject`?
So that I don't need to write the statement again in the `whenRebuilderOr()`
For example:

```
final uploadService = RM.injectComputed<UploadService>(         // Or using injectFuture at the next release 
  compute: (s) => s.copyWith(repo: uploadRepository.state),
  ..........
  onWaiting: () => const Center(child: CircularProgressIndicator( value: uploadService.state.updatePercent )),
  onError: (e, s) => UIErrorHandler.showErrorSnackBar(e),
);


In UI Pages
onWaiting: () => const Center(child: CircularProgressIndicator()),
Case 1: 
uploadService.whenRebuilderOr(
     //  onWaiting can be override here, default is following the Indicator from RM.inject
      builder: () => GridView.builder(
             .........
Case 2 (Clean state only): 
// The rebuilder desn't have onWaiting Indicator by default
uploadService.rebuilder(
   ()=>  GridView.builder(
             .........

```

**Comment by GIfatahTH** [comment]
@amoslai5128 if I understood you question well, the answer is yes.
