### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by anas-aw** [GIfatahTH/states_rebuilder#136]
I want to create a project, and i want to use states rebuilder 

how to integrate pageview with states_rebuilder
and for example 
navigate and show dialogs don't have to use context what about mediaquary ?

**Comment by GIfatahTH** [comment]
MediaQuery and theme are usually used inside the build method where the context is available. Nevertheless, you can use RM.context to get a valid BuildContext.

**Comment by anas-aw** [comment]
and how to integrate pageview

**Comment by amoslai5128** [comment]
> and how to integrate pageview

Would you explain more about that? 
Do you mean passing the PageController between multiple screens?
