### ISSUE TITLE
Widget-Wise injection of globally injected model - InheritedWidget style

### ISSUE THREAD

**Issue by GIfatahTH** [GIfatahTH/states_rebuilder#139]
Fetching a list of items from a backend service, parsing each item To a Widget, displaying it, and performing CRUD operations is a common task in the life of a programmer.

Items are of the same `Widget` type and `state` type, so getting the right state of an item will depend on its position in the widget tree; (The `state` is scoped). Speaking of the position in the widget tree, we implicitly refer to `BuildContext` which contains information about the position of a widget in the widget tree. Likewise, getting the state using `BuildContext` is exactly what `InheritedWidget` is designed for.

Imagine we fetched a list of items and got a list of them:

```dart
//fetched list of ItemData
final List<ItemData> items = [itemData1, itemData2, itemData3, ...];
```
Using `ListView`, we can iterate over each item and render it:

```dart
return ListView.builder(
    itemCount: items.length,
    itemBuilder: (BuildContext context, int index) {
      return ItemWidget(items[index]); //We can not use const here. See later for comparison
    }
)
```
We want to access an item's state from any child widget of `ItemWidget` without having to pass it through a chain of constructors. If you have some experience with Flutter, you might know this is the right place to use `InheritedWidget`.

In states_rebuilder, we build on the concept of `InheritedWidget` to get what we call widget aware injected model.

First, we declare a global injected model to represent a single item.

```dart
//Think to this a a global template to be used by items
final itemData = RM.inject<ItemData>(()=> null);
//null here because items are populated inside the ListView not here
```
In the `ListVew`: 

```dart
return ListView.builder(
    itemCount: items.length,
    itemBuilder: (BuildContext context, int index) {
      //invoke the inherited method on the global itemData
      return itemData.inherited(
          //How the state of an item is obtained from the list of items
          state : ()=> items[index],
          //The builder method. Notice we can use const here, which is a big performance gain
          builder: (BuildContext context)=>  const ItemWidget()
      )
    }
)
```

To get the injected state, in a child widget of `ItemWidget`, we use :

```dart
//calling the of method on the global itemData will get the right state using InheritedWidget
final Injected<ItemData> itemState = itemData.of(context);
```

As you can see, the global `itemData` injected model, is used to inject the model in the widget tree using `inherited` method and at the same time is used to get the state using the `of` method.

The global injected model as more options:

* `itemData` has `onWaiting`, `onError` and `onData` callbacks.
    ```dart
    final Injected<Todo> itemData = RM.inject(
        () => null,
        onWaiting: (){
            //Called if at least one item state is waiting
            print('onWaiting');
        }
        onError: (e, s) {
            //Called if at least one item state throws an error
            print('error');
        },
        onData: (item)  (){
            //Called if all item items has data and exposed the item state of the item emitting data
            print('onData');
            //The right pace to update the whole item list
        }
    );
    ```
* Refreshing the global `itemData` state, all item state will be refreshed.
  As `ItemWidget` are constructed with `const` modifier, they will not rebuild when their parent widget rebuild.
  In case we want to reinject the item state and rebuild their listeners, we simply call the refresh method on the global `itemData`.
  ```dart
  itemData.refresh();
  //All the states of the elements are recalculated, and those modified, their auditor is notified to rebuild
  ```  

## `InheritedWidget` limitation
As we know `InheritedWidget` cannot cross route boundary, unless it is defined above the `MaterielApp` widget (which s a non practical case).

After navigation, the `BuildContext` connection loses the connection with the `InheritedWidgets` defined in the old route. To overcome this shortcoming, with state_rebuilder, we can reinject the state to the next route:

```dart
RM.navigate.to(
  itemData.reInherited(
     // Pass the current context
     context : context,
     //The builder method, Notice we can use const here, which is a big performance gain
     builder: (BuildContext context)=>  const NewItemDetailedWidget()
  )
)
```

For more information, see https://github.com/GIfatahTH/states_rebuilder/wiki/17-inherited_inject

**Comment by amoslai5128** [comment]
I'm excited to see more examples with InheritedWidget, while I'm also thinking that might it be possible to reuse something like Switcher Widget in listview? 
The switcher normally requests you in a `StatefulWidget`, and you need to defined state for each of them.

**Comment by GIfatahTH** [comment]
>while I'm also thinking that might it be possible to reuse something like Switcher Widget in listview?

Could you explain more?

**Comment by amoslai5128** [comment]
See the third example at "SwitchListTile isn't exactly what I want":
https://api.flutter.dev/flutter/material/SwitchListTile-class.html

For example, a `ListView.builder` has 10 Switchers inside, each Switcher should be defined as its state.
I don't know is that suitable to use InheritedWidget.

**Comment by GIfatahTH** [comment]
Try this simple example, I think it answers your question:

```dart

void main() => runApp(_App());

//Simulate getting a list of bool from async task
final switcherList = RM.injectFuture(
  () => Future.delayed(
    Duration(seconds: 1),
    () => List.generate(10, (index) => false),
  ),
);

//The state of a single switcher
final switcherItem = RM.inject<bool>(() => null);

class _App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: switcherList.futureBuilder<List<bool>>(
          onWaiting: () => Center(child: CircularProgressIndicator()),
          onError: (e) => Text('$e'),
          onData: (data) => ListView.builder(
            itemCount: data.length,
            itemBuilder: (context, index) => switcherItem.inherited(
              stateOverride: () => data[index],
              builder: (context) => const LabeledSwitch(
                label: 'This is the label text',
                padding: const EdgeInsets.symmetric(horizontal: 20.0),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class LabeledSwitch extends StatelessWidget {
  const LabeledSwitch({
    this.label,
    this.padding,
  });

  final String label;
  final EdgeInsets padding;

  @override
  Widget build(BuildContext context) {
    final switcher = switcherItem(context);
    return InkWell(
      onTap: () {
        switcher.state = !switcher.state;
      },
      child: Padding(
        padding: padding,
        child: Row(
          children: <Widget>[
            Expanded(child: Text(label)),
            switcher.rebuilder(
              () => Switch(
                value: switcher.state,
                onChanged: (bool newValue) {
                  switcher.state = newValue;
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by amoslai5128** [comment]
> Try this simple example, I think it answers your question:
> 
> ```dart
> void main() => runApp(_App());
> 
> //Simulate getting a list of bool from async task
> final switcherList = RM.injectFuture(
>   () => Future.delayed(
>     Duration(seconds: 1),
>     () => List.generate(10, (index) => false),
>   ),
> );
> 
> //The state of a single switcher
> final switcherItem = RM.inject<bool>(() => null);
> 
> class _App extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Scaffold(
>         appBar: AppBar(),
>         body: switcherList.futureBuilder<List<bool>>(
>           onWaiting: () => Center(child: CircularProgressIndicator()),
>           onError: (e) => Text('$e'),
>           onData: (data) => ListView.builder(
>             itemCount: data.length,
>             itemBuilder: (context, index) => switcherItem.inherited(
>               stateOverride: () => data[index],
>               builder: (context) => const LabeledSwitch(
>                 label: 'This is the label text',
>                 padding: const EdgeInsets.symmetric(horizontal: 20.0),
>               ),
>             ),
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> class LabeledSwitch extends StatelessWidget {
>   const LabeledSwitch({
>     this.label,
>     this.padding,
>   });
> 
>   final String label;
>   final EdgeInsets padding;
> 
>   @override
>   Widget build(BuildContext context) {
>     final switcher = switcherItem(context);
>     return InkWell(
>       onTap: () {
>         switcher.state = !switcher.state;
>       },
>       child: Padding(
>         padding: padding,
>         child: Row(
>           children: <Widget>[
>             Expanded(child: Text(label)),
>             switcher.rebuilder(
>               () => Switch(
>                 value: switcher.state,
>                 onChanged: (bool newValue) {
>                   switcher.state = newValue;
>                 },
>               ),
>             ),
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```

Thank you, it works very well.

**Comment by amoslai5128** [comment]
@GIfatahTH
Syntax improvement request

When nested inherited the state, especially we also need to inherited the item index from the list view.
**Current:** 
```
final itemData = RM.inject<ItemData>(()=> null);
final itemIndex = RM.inject<int>(()=> null);
..... Outside the widget .......  

return ListView.builder(
    itemCount: items.length,
    itemBuilder: (BuildContext context, int index) {
      return itemData.inherited(
          stateOverride: ()=> items[index],
          builder: (BuildContext context)=>  itemIndex.inherited(
                   stateOverride: ()=> index,
                   builder: (BuildContext context)=>  const ItemWidget()
           )
      )
    }
)
```

**Ideal:** 
```
return ListView.builder(
    itemCount: items.length,
    itemBuilder: (BuildContext context, int index) {
      return [itemData, itemIndex].inherited(
          stateOverride: ()=> [ items[index], index ],
          builder: (BuildContext context)=>   const ItemWidget();
      )
    }
)
```
