### ISSUE TITLE
Problem with initializing Injected State in StatefulWidget

### ISSUE THREAD

**Issue by amoslai5128** [GIfatahTH/states_rebuilder#142]
Some problem with initializing Injected State in StatefulWidget, the widget won't be updated.
I know it can set initState inside the rebuilder, however, when it's too many injected states (like form), it'd be hard to manage.
I've tried, the original `@override initState()`, but it doesn't work too.

```
class Page extends StatefulWidget {
  const AddProductForm({Key key, this.editProduct}) : super(key: key);

  final Product editProduct;

  @override
  _PageState createState() => _PageState();
}


class _PageState extends State<Page>{
  bool get isEditing => widget.editProduct != null;
  final myStateA= RM.inject<bool>(() => false);
  final myStateB = RM.inject<bool>(() => false);
  
  Widget build(BuildContext context) {
    //As a initState, Doesn't work
    if (isEditing) {
      myStateA.setState((s)=> isEditing);
      myStateB.setState((s)=> !isEditing);
    }

    return  Column(
      children: [
         myStateA.rebuilder(()=> Text( myStateA.state.toString() ) ),
         myStateB.rebuilder(()=> Text( myStateB.state.toString() ) ),
      ],
    );

  }
}
```

**Comment by GIfatahTH** [comment]
I do not exactly understand  your case;
setting the state inside build method is not good practice. Try this:
```dart
class _PageState extends State<Page> {
  bool get isEditing => widget.editProduct != null;
  Injected<bool> myStateA;
  Injected<bool> myStateB;
  initState() {
    super.initState();
    myStateA = RM.inject<bool>(() => isEditing);
    myStateB = RM.inject<bool>(() => !isEditing);
  }

  Widget build(BuildContext context) {
    return Column(
      children: [
        myStateA.rebuilder(() => Text(myStateA.state.toString())),
        myStateB.rebuilder(() => Text(myStateB.state.toString())),
      ],
    );
  }
}
```

**Comment by amoslai5128** [comment]
> I do not exactly understand your case;
> setting the state inside build method is not good practice. Try this:
> 
> ```dart
> class _PageState extends State<Page> {
>   bool get isEditing => widget.editProduct != null;
>   Injected<bool> myStateA;
>   Injected<bool> myStateB;
>   initState() {
>     super.initState();
>     myStateA = RM.inject<bool>(() => isEditing);
>     myStateB = RM.inject<bool>(() => !isEditing);
>   }
> 
>   Widget build(BuildContext context) {
>     return Column(
>       children: [
>         myStateA.rebuilder(() => Text(myStateA.state.toString())),
>         myStateB.rebuilder(() => Text(myStateB.state.toString())),
>       ],
>     );
>   }
> }
> ```

OK, it makes sense, and I got another question. How about set another State after onData? 
```
stateA.whenRebuilderOr(
      initState: () {
        stateA.setState((s) => stateA.loadData(s),
            onData: (_, stateA) => cloneIDfromStateA.setState(
                (s) =>stateA.products.map((e) => item.id ).toList()));
      },
      builder: ()=> Text( cloneIDfromStateA.toString() )
 )
```

**Comment by amoslai5128** [comment]
> > OK, it makes sense, and I got another question. How about set another State after onData? It seems not working.
> 
> No problem you can nest setStates. Doesn't is work for you?

Yes, the cloneIDfromState doesn't get any data, and I can sure that the productState has data

**Comment by GIfatahTH** [comment]
I tried with this simple example that I hope it reproduces your case and I it worked with me!

```dart
void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Page(),
    ),
  ));
}

class Counter1 {
  String id;
  Future<void> setID() async {
    await Future.delayed(Duration(seconds: 1));
    id = '__counter1_id__';
  }
}

class Counter2 {
  String id;
  Future<void> setID(String pre) async {
    await Future.delayed(Duration(seconds: 1));
    id = pre + ' __counter2__id';
  }
}

final counter1 = RM.inject(() => Counter1());
final counter2 = RM.inject(() => Counter2());

class Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return counter1.whenRebuilderOr(initState: () {
      counter1.setState((s) => s.setID(), onData: (ctx, counter1) {
        counter2.setState((s) => s.setID(counter1.id));
      });
    }, builder: () {
      return Column(
        children: [
          Text(counter1.state.id.toString()),
          counter2.rebuilder(() => Text(counter2.state.id.toString()))
        ],
      );
    });
  }
}

```

**Comment by amoslai5128** [comment]
> I tried with this simple example that I hope it reproduces your case and I it worked with me!

Thank you for your great answer, is that another that to work with it?  Since currently, the situation is I have 50 more product items in my ListView, each one has their Switcher to decide whether it is in published status. However, I want each of the item's switcher rebuilds independently.

 Since the swither widget is stateful, it must provide its bool state, here are two possible ways to do that:
A. Clone partial data as a local RM.injected() from current products' state. For example: [ [id1, true], [id2. false] ...... [id50, true] ]
B. Wrap a StatefulBuilder for each of the Swither widget, setState inside to determine the value.
... or any way that can work smarter?

**Comment by amoslai5128** [comment]
Why a local RM won't be updated after setState inside other state's onData?

```
void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Page(),
    ),
  ));
}

class Counter1 {
  String id;
  
  Future<void> setID() async {
    await Future.delayed(Duration(seconds: 1));
    id = '__counter1_id__';
  }
}

final counter1 = RM.inject(() => Counter1());
final clone = RM.inject<String>(() =>  "");   // clone is a local RM

class Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return counter1.whenRebuilderOr(
       initState: () {
         counter1.setState((s) => s.setID(), onData: (ctx, counter1) {
               clone .setState((s) => counter1.id );
       });
    }, builder: () {
      return Column(
        children: [
          Text(counter1.state.id.toString()),
          clone.rebuilder(() => Text(clone.state)),    //It doesn't update
        ],
      );
    });
  }
}
```

**Comment by amoslai5128** [comment]
> I tried with this simple example that I hope it reproduces your case and I it worked with me!
> 
> ```dart
> void main() {
>   runApp(MaterialApp(
>     home: Scaffold(
>       body: Page(),
>     ),
>   ));
> }
> 
> class Counter1 {
>   String id;
>   Future<void> setID() async {
>     await Future.delayed(Duration(seconds: 1));
>     id = '__counter1_id__';
>   }
> }
> 
> class Counter2 {
>   String id;
>   Future<void> setID(String pre) async {
>     await Future.delayed(Duration(seconds: 1));
>     id = pre + ' __counter2__id';
>   }
> }
> 
> final counter1 = RM.inject(() => Counter1());
> final counter2 = RM.inject(() => Counter2());
> 
> class Page extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return counter1.whenRebuilderOr(initState: () {
>       counter1.setState((s) => s.setID(), onData: (ctx, counter1) {
>         counter2.setState((s) => s.setID(counter1.id));
>       });
>     }, builder: () {
>       return Column(
>         children: [
>           Text(counter1.state.id.toString()),
>           counter2.rebuilder(() => Text(counter2.state.id.toString()))
>         ],
>       );
>     });
>   }
> }
> ```
Is it possible to
