### ISSUE TITLE
Perhaps I'm missing something with the Global Injectors

### ISSUE THREAD

**Issue by cidothia** [GIfatahTH/states_rebuilder#144]
If I place logic in my injected.dart the following:

```
final Injected<MyModelService> modelSrv = RM.injectComputed<MyModelService>(
    compute: (state) => state.copyWith(repository: modelRepo.state),
    initialState: InitModelService(modelRepo.state),
    onInitialized: (s) => loadModel(s),
);
```

The state is not saved for use in any of the observers, which forces you to use a modelSrv.futureBuilder() call in any of the observers.  Is this intended?

**Comment by cidothia** [comment]
Because I just realized that you may want to know:

the signature of loadModel(s) returns a Future<MyModelService>

**Comment by GIfatahTH** [comment]
@cidothia  thank you for opening the issue.
1. first I wonder why you used `RM.injectedComputed` here, why not simply using RM.inject? Do you want the `modelSrv` to recompute each time `modelRepo` state change? If yes it's OK.
2. to change the state of any model and make it notify its listeners, you must use setState. Your example may be rewritten like this:
```dart
final Injected<MyModelService> modelSrv = RM.injectComputed<MyModelService>(
    compute: (state) => state.copyWith(repository: modelRepo.state),
    initialState: InitModelService(modelRepo.state),
    onInitialized: (s) => modelSrv.setState((s) => loadModel(s)),
);
```

**Comment by cidothia** [comment]
> 1. first I wonder why you used `RM.injectedComputed` here, why not simply using RM.inject? Do you want the `modelSrv` to recompute each time `modelRepo` state change? If yes it's OK.

Indeed, ModelRepo uses the active user in their constructor.  So the Service needs to have the correct Repo at all times.

> 2. to change the state of any model and make it notify its listeners, you must use setState. Your example may be rewritten like this:

I believe that I understand this, but there is one confusion.  the `s` in the example is used in two places, is the `(s) => modelSrv` more important or unused?  So, is this correct?

`onInitiated: (_) => modelSrv.setState((s) => loadModel(s)),`

**Comment by GIfatahTH** [comment]
the answer is (Do not forget setState):
```
onInitiated: (_) => modelSrv.setState((s) => loadModel(s)),
```

Thank you for your kind explination.

**Comment by cidothia** [comment]
So, I wanted to post a follow-up:

I have two ModelSrv: 

`final Injected<SkuService> skuSrv = RM.injectComputed<SkuService>(
  compute: (s) => s.copyWith(
    repository: skuRepo.state,
  ),
  initialState: InitSkuService(skuRepo.state),
  onInitialized: (s) => skuSrv.setState(
    (s) => loadSkus(s),
  ),
  onError: (e, s) => showErrorSnackbar,
  onWaiting: () => progressIndicator(null),
);`

`
final Injected<KeepService> keepSrv = RM.injectComputed<KeepService>(
  compute: (s) => s.copyWith(
    repository: keepRepo.state,
  ),
  initialState: InitKeepService(keepRepo.state),
  onInitialized: (s) => keepSrv.setState(
    (s) => loadKeeps(s),
  ),
  onError: (e, s) => showErrorSnackbar,
  onWaiting: () => progressIndicator(null),
);`

Both of these use a search bottomSheet to choose which instance from a list to use:  KeepSrv has an `active` and a `current` instance.  Active is the one for forms to use, and Current is only used in the search bar and is not a global function injector, and the following is top-level in the `keep_choose.dart` file.

`final Injected<KeepService> currentKeep = RM.injectComputed<KeepService>(
  compute: (s) => s.copyWith(currentKeep: s.current),
  initialState: keepSrv.state,
);`

The build of the statefulWidget

`@override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) => Container(
        height: constraints.maxHeight - 150,
        padding: EdgeInsets.only(left: 10, right: 10),
        child: currentKeep.rebuilder(
          () => TrakSearchBar<Keep>(
            onSearch: keepSrv.state.searchByRef,
            onItemFound: (Keep i, int idx) => KeepItem(
                onDismissed: (direction) => null,
                onTap: () => onKeepSelected(i),
                actionTap: () => onKeepAction(i),
                keep: i),
            suggestions: currentKeep.state.childrenMap(),
            hintText: formatKeepTitle(currentKeep.state.current),
          ),
        ),
      ),
    );
  }`

The above code works great, and is called using `RM.navigate.toBottomSheet` and when it is done `RM.navigate.back` is called, and everything works.

Now, for the SkuSrv... it doesn't work.  The only difference is that Sku is a flat list, and doesn't need a currentSku, and so does not have a FI in the `sku_choose.dart`  For that stateful widget I have to have a futureBuilder to get the List<Sku> to be populated.

`@override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) => Container(
        height: constraints.maxHeight - 200,
        padding: EdgeInsets.only(left: 10, right: 10),
        child: skuSrv.futureBuilder(
          future: (s, as) => loadSkus(s),
          onError: null,
          onWaiting: () => progressIndicator(null),
          onData: (_) => TrakSearchBar<Sku>(
            onSearch: skuSrv.state.searchByRef,
            onItemFound: (Sku i, int idx) => SkuItem(
              onDismissed: null,
              onTap: () => onSkuSelected(i),
              sku: i,
            ),
            suggestions: skuSrv.state.skus,
            hintText: kNullSkuTitle,
          ),
        ),
      ),
    );
  }`

Without a `futureBuilder()` the sku search bar gives an [error](https://i.imgur.com/2LvB2pf.png) that length was called on null.

**Comment by cidothia** [comment]
And, just so you know, I found the error causing this:  Once more to aid those who may be running into issues like this:

If you have an issue where this code doesn't work, then look at your Repository code.  I had forgotten to return my _cacheSkus on the initial.  So, on the second call to loadSkus, the _cacheSkus would be returned, but on the initial call, they were not returned.

```
Future<List<Sku>> _retrieveSkus() async =>
   await Future.delayed(Duration(seconds: 1)).then((value) => _cache.addAll(kSampleSkus));
```
This doesn't actually return anything...

'''
Future<List<Sku>> _retrieveSkus() async {
  await Future.delayed(Duration(seconds: 1))
      .then((value) => _cache.addAll(kSampleSkus));
  return _cache;
}
```
