### ISSUE TITLE
Need some help on how to load values in another page with states_rebuilder

### ISSUE THREAD

**Issue by prafgup** [GIfatahTH/states_rebuilder#15]
I had initiated a MainBloc StatesRebuilder to have it the same in every page of the app but when I try to access it from another page  whose route is as follows 

`Navigator.push(
    context,
    MaterialPageRoute(builder: (context) => anotherpage()),
  );`

I am unable to get the same MainBloc in anotherpage() .

The MainModel is as follows:

`class MainBloc extends StatesRebuilder{
  double variable=0;
change(){
variable++;
}
}
`

I initiated the MainBloc in the app starting as 
`class HomePageBuilder extends StatelessWidget {
  GoogleSignInAccount currentgoogleuser;
  HomePageBuilder({this.currentgoogleuser});
  @override
  Widget build(BuildContext context) {
    return BlocProvider<MainBloc>(
              bloc: MainBloc(),
        child:HomePage(currentgoogleuser:currentgoogleuser ,),

    );
  }
}
`

And using by 

`final bloc = BlocProvider.of<MainBloc>(context);`

`somewidget onTap:()=>bloc.change()`

Everything is working except when I do the same in anotherpage();
I cant acess the bloc.

How do i get the same Initially created Bloc and its data in every page of my app?

**Comment by GIfatahTH** [comment]
BlocProvider relays on the context to find the MainBloc. anotherpage should be a child of the widget where your uded the BlocProvider.
The better solution is to use Injector to provide your bloc. For this update to the latest version and do the following changes:

```
class HomePageBuilder extends StatelessWidget {
final GoogleSignInAccount currentgoogleuser;
HomePageBuilder({this.currentgoogleuser});
@override
Widget build(BuildContext context) {
return Injector(
models: [()=>MainBloc()],
builder:(_)=>HomePage(currentgoogleuser:currentgoogleuser ,),
);
}
}
```

You call the bloc with:
```
final bloc = Injector.get<MainBloc>();
```
The Injector do not relay on the context so it can be called from any class.

**Comment by prafgup** [comment]
Thankyou @GIfatahTH  for the solution. I had one more query if your could help.

Is there any way to retain this MainModel even after app restart ,except using Sqflite to save every data in database and again retrieving at every restart?
