### ISSUE TITLE
How can I archive renewing the firebase token automatically by using States_rebuilder FI

### ISSUE THREAD

**Issue by amoslai5128** [GIfatahTH/states_rebuilder#152]
Thank you @GIfatahTH for making this amazing example. However, how can I do to renew the firebase token instead of sign out the user when it's expired?
Since I'm now discovering the Firebase Cloud API, so that I need to send the HTTP request with a valid token. There're some ways like storing the token in security_storage and checking each time before the HTTP API is sent, but I don't think it's the best practice.....
 
[Ref to: Example009_1_4](https://github.com/GIfatahTH/states_rebuilder/blob/master/examples/ex_009_1_4_ca_todo_mvc_with_state_persistence_and_user_auth/lib/ui/injected/injected_user.dart)

**Comment by GIfatahTH** [comment]
I didn't try it, but I think it will work:
First add refreshToken method:
```dart
extension UserX on User {
 . . . . 
 . . . . 

  Future<User> refreshToken() async {
    //get new token based on the current token
    final newToken = await authRepository.state.refreshToken(token);
    return copyWith(token: newToken);
  }
}
```

and change in _setExpirationTimer

```dart
void _setExpirationTimer(Token token) {
  _cancelExpirationTimer();
  final timeToExpiry = token.expiryDate.difference(DateTimeX.current).inSeconds;
  _authTimer = Timer(
    Duration(seconds: timeToExpiry),
    () {
      user.state = user.state.refreshToken();
    },
  );
}
```

**Comment by amoslai5128** [comment]
Yes, it works very nicely, however, how can I keep standing for the current screen if the token can be refreshable:
[example, at line 60](https://github.com/GIfatahTH/states_rebuilder/blob/master/examples/ex_009_1_4_ca_todo_mvc_with_state_persistence_and_user_auth/lib/ui/injected/injected_user.dart)
```
  onData: (User u) {
    if (u is UnsignedUser) {
      _cancelExpirationTimer();
      RM.navigate.toNamedAndRemoveUntil(AuthPage.routeName);
    } else {
      _setExpirationTimer(u.token);
      RM.navigate.toNamedAndRemoveUntil(HomeScreen.routeName); //This
    }
  },
```

**Comment by amoslai5128** [comment]
I also realized that there is a package "[cloud_functions](https://pub.dev/packages/cloud_functions)"

**Comment by amoslai5128** [comment]
> I didn't try it, but I think it will work:
> First add refreshToken method:
> 
> ```dart
> extension UserX on User {
>  . . . . 
>  . . . . 
> 
>   Future<User> refreshToken() async {
>     //get new token based on the current token
>     final newToken = await authRepository.state.refreshToken(token);
>     return copyWith(token: newToken);
>   }
> }
> ```
> 
> and change in _setExpirationTimer
> 
> ```dart
> void _setExpirationTimer(Token token) {
>   _cancelExpirationTimer();
>   final timeToExpiry = token.expiryDate.difference(DateTimeX.current).inSeconds;
>   _authTimer = Timer(
>     Duration(seconds: timeToExpiry),
>     () {
>       user.state = user.state.refreshToken();
>     },
>   );
> }
> ```


Question 1: 
I noticed sometimes when the app runs in the background for a while and then reopens again. The timer state will countdown wrongly to refresh the token. (I'll try the real device later)

Question 2:
Thanks for the new features `InjectAuth`, what's the best practice to refresh the token from firestore with the auth stream changes?

Thanks
