### ISSUE TITLE
global function injection of a stream does not update with firebase auth

### ISSUE THREAD

**Issue by samuelstroschein** [GIfatahTH/states_rebuilder#153]
Hello everyone, 

I am facing an issue using RM.injectStream for two days. Firebase recommends using `FirebaseAuth.instance.authStateChanges()` to handle authentication state which is a Stream<User>. My approach is/was something like that:
```Dart
final _currentUser =
    RM.injectStream(() => FirebaseAuth.instance.authStateChanges());

final authState = RM.injectComputed<AuthState>(
    initialState:
        AuthState(authImplementation: AuthImplementation(), user: null),
    compute: (previousState) =>
        previousState.copyWith(user: _currentUser.state));
```

Ignore `authState` for the following problem. `currentUser = RM.injectStream()` does not seem to work properly since it does not update its state when the user logs out e.g. when FirebaseAuth.instance.signOut()) is called. 

#### StreamBuilder with FirebaseAuth.instance works
```Dart
return StreamBuilder(
    stream: FirebaseAuth.instance.authStateChanges(),
    builder: (context, snapshot) {
      if (snapshot.data == null) {
        return LoginScreen();
      } else {
        return HomeScreen();
      }
    },
  );
```
#### StatesRebuilder injectStream() does not work
```Dart
final currentUser =
    RM.injectStream(() => FirebaseAuth.instance.authStateChanges());


return currentUser.rebuilder(
    () {
      if (currentUser.state == null) {
        return LoginScreen();
      } else {
        return HomeScreen();
      }
    },
  );
```

I am using Firebase Phone Auth. The moment the user enters the correct verification code, states_rebuilder works as expected: the state contains the current user which corresponds to the 'internal' _auth state. See the screenshot from the debugger below:
<img width="395" alt="login" src="https://user-images.githubusercontent.com/35429197/102882420-a7e6f100-444e-11eb-8c7c-a0a915d02e34.png">

However, when logging out the state does not update although the 'internal' _auth has the correct/another state. See the screenshot below:
<img width="390" alt="logout" src="https://user-images.githubusercontent.com/35429197/102882615-ebd9f600-444e-11eb-84dd-551d14da0986.png">

**Comment by amoslai5128** [comment]
Attempt 1:
Can you try to replace the `currentUser.rebuilder` to `currentUser.whenRebuilderOr`?
```
currentUser.whenRebuilderOr(
 wacth: ()=> currentUser.state
 builder: () => ....
)
```

Attempt 2:  I'm working fine with this [example 009_1_4](https://github.com/GIfatahTH/states_rebuilder/blob/master/examples/ex_009_1_4_ca_todo_mvc_with_state_persistence_and_user_auth/lib/ui/injected/injected_user.dart). (at line 54~60, ignoring the token)

**Comment by GIfatahTH** [comment]
@samuelstroschein Thank you for opening the issue

By design, in states_rebuilder you can not set the state to null. And if the state is set to null (case of user logout) nothing will change.

To deal with null, you have to refer to what is called the null object pattern.

Try these changes:
```dart

//This is your User data class not FirebaseAuth's
//
//It is a bad practice to use the default FireBaseAuth User class throughout your app
class User {
  final String name;
  final String email;
  User({
    this.name,
    this.email,
  });
}

//Extend the user class
class NullUser extends User {}

final currentUser = RM.injectStream(
  () => FirebaseAuth.instance.authStateChanges().map(
        (user) =>user != null? User(name: user.name, email: user.email) :+1:  NullUser(),
      ),
);

return currentUser.rebuilder(
    () {
      if (currentUser.state is NullUser) {
        return LoginScreen();
      } else {
        return HomeScreen();
      }
    },
  );

```

**Comment by samuelstroschein** [comment]
@GIfatahTH I was already wondering why Dart/Flutter is getting null safety and FirebaseAuth is implemented using a nullable variable. Thanks a lot for the explanation (and the hint in the comment ;) )!

**Comment by samuelstroschein** [comment]
@GIfatahTH btw wouldn't it be a good idea to throw an Error when a State is set to null?

**Comment by amoslai5128** [comment]
> @GIfatahTH btw wouldn't it be a good idea to throw an Error when a State is set to null?

Currently, by using the InheritedWidget with an injected state, most of the time it has defended a null as its initial value.

Btw, at the next release with the null safaty update, there would be some breaking changes.
