### ISSUE TITLE
Help to understand why hasData returns false in first time

### ISSUE THREAD

**Issue by devfelipereis** [GIfatahTH/states_rebuilder#156]
Hello.

I'm trying to understand why my form is invalid in the first line of build method(it's an edit form). I have data and my form is populated but the property **_isFormValid** is **false**.

![image](https://user-images.githubusercontent.com/5348752/103885917-811bf200-50bf-11eb-8225-d1daf950b0c8.png)

It will only be true if I type something in both fields.

Why this happen? Thank you!

**Comment by amoslai5128** [comment]
can you try to wrap your print function inside of
```
 [_apiUrlRM, _scoreRm].rebuilder(
    ()=> Text( _isFormValid.toString() )
),
```

**Comment by devfelipereis** [comment]
Sorry for that mistake... I created that example but I'm alreary using rebuilder.
Inside rebuilder I still get **false.**

Using your example and StatesBuilder I have false in both.

![image](https://user-images.githubusercontent.com/5348752/104052136-02f74280-51c8-11eb-8e19-8d3fbc733dd2.png)

**Comment by amoslai5128** [comment]
Thanks for giving the code, I've taken a look into it.
First, I notice your `_apiUrlRM & _scoreRM` (line 13~16) are subscribing to another injected state `appSettings`, but why don't you directly use appSettings only?  However, if you only want to clone the state and work locally, you can do the following step:

1. Wrap `_apiUrlRM & _scoreRM`  outside the class, and change it to `injectComputed`, however, this syntax will be deprecated at next release (keep your eyes on [this](https://github.com/GIfatahTH/states_rebuilder/issues/123#issuecomment-756777248)).

It would subscribe to appSettings every time onData:

```
final _apiUrlRM = RM.injectComputed<String>(
    computed: (_) => appSettings.state.apiUrl,
  );
final _scoreRM = RM.injectComputed<String>(computed: (_) => appSettings.state.score);

class class SettingsScreen extends StatelessWidget {
       .......

```
BTW, there is an example would be helpful for you:  https://github.com/GIfatahTH/states_rebuilder/tree/master/examples/ex_002_2_form_validation_with_reactive_model_with_functional_injection

**Comment by devfelipereis** [comment]
Not working yet. :/
But.... I found something that works.

Instead of 

bool get _isFormValid => _apiUrlRM.hasData && _scoreRM.hasData;

use

bool get _isFormValid =>
      _apiUrlRM.state.isNotEmpty && _scoreRM.state.isNotEmpty;

The screen will load and the button will be active. I just don't know why.

And I found another thing.. button will be always active in this validation because the value will never be empty:
```

_scoreRM.setState(
              (_) {
                if (value.isEmpty) {
                  throw ValidationException('Este campo é obrigatório'); // here the value will never be empty in the state 
                }

                if (int.tryParse(value) == null) {
                  throw ValidationException(
                    'O Score precisa ser um número',
                  );
                }

                return value;
              },
              catchError: true,
            );
```

for now, thank you for all the information.

**Comment by amoslai5128** [comment]
> The screen will load and the button will be active. I just don't know why.



> Not working yet. :/
> But.... I found something that works.
> 
> Instead of
> 
> bool get _isFormValid => _apiUrlRM.hasData && _scoreRM.hasData;
> 
> use
> 
> bool get _isFormValid =>
> _apiUrlRM.state.isNotEmpty && _scoreRM.state.isNotEmpty;
> 
> The screen will load and the button will be active. I just don't know why.
> 
> And I found another thing.. button will be always active in this validation because the value will never be empty:
> 
> ```
> 
> _scoreRM.setState(
>               (_) {
>                 if (value.isEmpty) {
>                   throw ValidationException('Este campo é obrigatório'); // here the value will never be empty in the state 
>                 }
> 
>                 if (int.tryParse(value) == null) {
>                   throw ValidationException(
>                     'O Score precisa ser um número',
>                   );
>                 }
> 
>                 return value;
>               },
>               catchError: true,
>             );
> ```
> 
> for now, thank you for all the information.

Oh, please be aware that the rebuilder doesn't accept any null state, thus it will not be notified to rebuild or hasData. 
Do you mean the MaterialButton on line 65?

**Comment by devfelipereis** [comment]
But if I try with:

```
final _apiUrlRM = RM.inject<String>(
  () => 'testing',
);
final _scoreRM = RM.inject<String>(() => '58');
```
it will not work either.

and about material, yes. I just want to load the page and if it has data, the button should be active.
With that code(that I shared and with modifications will provided), the button will not be active.

**Comment by amoslai5128** [comment]
Can you update your code to the Git?

**Comment by devfelipereis** [comment]
I created a repo: https://github.com/devfelipereis/states_rebuilder_issue_button

**Comment by amoslai5128** [comment]
> I created a repo: https://github.com/devfelipereis/states_rebuilder_issue_button
> 
> **Update**
> I put some comments about the save button. In fact that is not an issue with states_rebuilder but with the it was done.

Please check the pull request: https://github.com/devfelipereis/states_rebuilder_issue_button/pull/1/files

Changed it to, and it works fine.
`bool get _isFormValid => appSettings.state.apiUrl != null && appSettings.state.score != null;`

**Comment by devfelipereis** [comment]
Amazing! It's working great now.
It will give me a great base to build forms and other stuff.

Thank you so much for your time!! I really appreciate.
