### ISSUE TITLE
Refresh without loosing state?

### ISSUE THREAD

**Issue by devfelipereis** [GIfatahTH/states_rebuilder#158]
Injecting a future and loading some data from api is very easy.
If I want to refresh, just call .refresh() and it works. When using the RefreshIndicator, If I call .refresh() the state will be lost and a loading will show(with the loading from RefreshIndicator).
To fix that, stead of .refresh() I call setState passing the future again and with the option skipWaiting true.

Now it will show only the loading from RefreshIndicator and state will not be lost.. but... If I got an error, the state will be lost and a Text widget will show the error in the screen. 

When using RefreshIndicator, If I got an error, I want to show a snackbar and keep the state to continue to show something to the user.

Is there any way to do this?

Another question: that setState is doing something like the .refresh() but with some options. I still need to pass the future again.
Is there any option to just repeat the future and use an option like skipWaiting?

Thank you!

**Comment by GIfatahTH** [comment]
Hi @devfelipereis  thanks for the issue

Does this representative example, reflect yours?

```dart
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

final list = ['0'];
int count = 0;
final items = RM.injectFuture<List<String>>(
  () async {
    await Future.delayed(Duration(seconds: 1));
    if (Random().nextBool()) {
      throw Exception('Fetching items Error');
    }
    return list..add('${++count}');
  },
  onError: (err, stack) {
    Scaffold.of(RM.context).showSnackBar(
      SnackBar(
        content: Text('$err'),
      ),
    );
  },
);

void main() {
  runApp(_MyApp());
}

class _MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: RefreshIndicator(
          onRefresh: () async {
            return items.refresh();
          },
          child: items.futureBuilder(
            onWaiting: () => Center(
              child: CircularProgressIndicator(),
            ),
            onError: null,
            onData: (_) => items.rebuilder(
              () => ListView.builder(
                itemCount: items.state.length,
                itemBuilder: (_, index) {
                  return Text('Item ${items.state[index]}');
                },
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by devfelipereis** [comment]
No... I'm using only whenRebuilderOr ... Sorry I forgot to show the code.

![image](https://user-images.githubusercontent.com/5348752/104646896-dd6aad00-568f-11eb-8c86-f1a75d0f79b8.png)

**Comment by GIfatahTH** [comment]
>I don't know why but the loading from RefreshIndicator will not hide when the request is success.

I tried with my representative example and it hides as expected.

Could you give more information?

**Comment by devfelipereis** [comment]
Sorry. It was my mistake. Thank you!
