### ISSUE TITLE
how to rebuild the appbar 

### ISSUE THREAD

**Issue by anas-aw** [GIfatahTH/states_rebuilder#160]
i have a app and i'm use states_rebuilder

in appbar i need to rebuild to get cart length

**Comment by samuelstroschein** [comment]
I see that this is your first issue on GitHub. You should provide a clear description of your problem and preferably show code. Otherwise, it's hard to help you.

**Comment by qhu91it** [comment]
You can wrap appBar with PreferredSize and then you can use StateBuilder here

```
appBar: PreferredSize(
  child: StateBuilder<String>(
    observe: () => vm.titleRM,
    builder: (_, __) => AppBar(
      centerTitle: true,
      title: Text(vm.titleRM.state),
    ),
  ),
  preferredSize: Size(0, 56),
)
```
