### ISSUE TITLE
how to implement page transition

### ISSUE THREAD

**Issue by anas-aw** [GIfatahTH/states_rebuilder#161]
how to implement page transition with states rebuilder

**Comment by GIfatahTH** [comment]
Once I'm done with the new update, I'll see how to do this.

**Comment by GIfatahTH** [comment]
Hi @anas-aw ;
In the ^4.0.0-nullsafety.0 update I added page transition animation.
It is very simple and works for both named and widget routing.

See here for more information, and feed me back:

https://github.com/GIfatahTH/states_rebuilder/wiki/navigation_dialog_scaffold_without_BuildContext_api

then new update is available in pub.dev:

https://pub.dev/packages/states_rebuilder/versions/4.0.0-nullsafety.0
