### ISSUE TITLE
New 4.0.0 null safety updtate is ready.

### ISSUE THREAD

**Issue by GIfatahTH** [GIfatahTH/states_rebuilder#163]
After about a month of hard work, I finally managed to migrate states_rebuilder to the null-safety world.

I didn't use any automatic tools, I rewrote the code from scratch. This allowed me to improve the underlying logic and open the door for me to add more interesting and production-time-saver features.

 ## Some breaking changes
In states_rebuilder there are two methods of dependency injection, the old one is to use the Injector widget and the newer approach is to use functional injection. I decided to go in favor of functional injection. My first thought is to remove the Injector approach but ultimately decided to leave a lite version of it in order to support legacy codes and remove it from the documentation.

The `RMKey` class is completely removed because it has nothing to do with functional injection.
`InjectComputed 'is also removed in favor of a new approach where any injected model can be calculated from other injected states.

 ## Production-time-saving features.
By rewriting the code and with the clean architecture I followed, I found that I could model some of the repetitive tasks that a developer does in his day-to-day coding life. I abstracted and hid their detailed implementation and exposed a clean and simple API through a dedicated Injected objects.

In almost any application, a developer will write code to authenticate a user, retrieve, update, and delete items from a backend server, handle theme change, and internationalize the application. Please stand up and welcome `RM.injectCRUD`,` RM.injectAuth`, `RM.injectTheme` and` RM.injectI18N`.

Be ready for the next step states_rebuilder will take you.

**Comment by KhatibFX** [comment]
This looks amazing! I feel like refactoring my code is going to take a while, but it will be easier moving forward!

Previously, I always used the Injector widget, because it had the initState call which I always used to initialize all necessary services for a page (aka services for CRUD).

I can't wait to see how this will work with the new methods!
