### ISSUE TITLE
Example for infinite list with refresh

### ISSUE THREAD

**Issue by wackazong** [GIfatahTH/states_rebuilder#169]
Thanks for your excellent work on states_rebuilder. I like your approach and would want to try it out. What I am missing is an example for an infinite list with automatic fetch of more data when the user scrolls as well as an option to refresh the list (effectively reloading the first page of data). 

I understand that in your approach the service layer holds the data received from the data source in an array. This is the state of the app. If this array is a future you deduct that the state is "waiting". But what if the service already holds the first page of data in the list and the client want to get more data? While the repository is fetching the data I still want to display the first page of the data but also I need to store the new state (getting more data) somewhere. Similar questions apply to the situation of data refresh. 

Would be great to see an example of that. Thanks!

**Comment by GIfatahTH** [comment]
Thank you @wackazong for your issue that pushes me to get out with the concept of middleState and middleSnapState

Here is a working example of infinite list with the requirement you asked for. 
https://github.com/GIfatahTH/states_rebuilder/tree/null_safety/examples/ex_006_2_infinite_scroll_list

Please use the new null safety update

https://pub.dev/packages/states_rebuilder/versions/4.0.0-nullsafety.0
