### ISSUE TITLE
And finaly, the new null safety update is published

### ISSUE THREAD

**Issue by GIfatahTH** [GIfatahTH/states_rebuilder#171]
I am very happy to announce that the new null safety update is in the pub:
Here is the short change log:

### Breaking change :
* Remove RMKey classes.
* `RM.injectComputed `is removed
* Change `Injector.en` to `RM.env`.
### New features :
* Add `On` and `OnCombined`.
* All `onError` callbacks in `On` and `OnCombined` expose a refresher to retry the last async function that causes the exception.
* `middleSnapState`
* Add page route transition animation.
* Add `RM.injectCRUD`, `RM.injectAuth`, `RM.injectTheme`, and `RM.injectI18N`.
* Refactor the internal logic.
* Refactor to null safety.

For the detailed change log head to:

https://github.com/GIfatahTH/states_rebuilder/blob/null_safety/states_rebuilder_package/changelog/v-4.0.0.md

Please try it, and contribute to make it better.

**Comment by amoslai5128** [comment]
Very happy to see this new release, I can't wait to implement my projects with null safety with States_rebuilder :)

**Comment by am2074** [comment]
Awesome. I'm looking through the readme for ver 4 and wanted to try some examples to better understand, but they're dead links. What's the timeline for having examples with these new features?

**Comment by xalikoutis** [comment]
Hi after upgrading to 4.0 i see that there isnt .getRm in order to get the reaction model and to subscribe like below
`coursePlayerStore.getRM.onError((context, error) {
      ErrorHandler.showSnackBar(context, error);
    });`
How can i replace it?

**Comment by GIfatahTH** [comment]
Yes, that is a breaking change.
I go in favor of functional injected, where you can easily handle error the way you like.

Please update to version 4 and try it.

**Comment by xalikoutis** [comment]
Thanks awesome work, and last one i use a lot `filterTags` in my apps is there any alternative in order not to call all builders that are listening to specific reactive model?

**Comment by GIfatahTH** [comment]
@xalikoutis  with the new approach you do not have to use filterTags anymore.

**Comment by gustavobrian** [comment]
Well, bet on this bookstore, but there is a new approach! the most expensive approach to the project. Where do I find information to be able to update to the new approach... Thanks

**Comment by amoslai5128** [comment]
> @xalikoutis with the new approach you do not have to use filterTags anymore.

@gustavobrian  please check out [https://github.com/GIfatahTH/states_rebuilder/wiki/on_builder_api](WIKI DOC), you can find `shouldRebuild: ` to let you define a condition to rebuild.
