### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by devfelipereis** [GIfatahTH/states_rebuilder#172]
Small typo in https://github.com/GIfatahTH/states_rebuilder/wiki/rm_injected_api#middleSnapSate

Search for: If stateA asData and stateB hasData than stateC hasData; Optionally, stateC recalculation can be:
typo in:  If stateA asData
shoud be:  If stateA hasData

**Comment by GIfatahTH** [comment]
Thanks it will be fixed
