### ISSUE TITLE
todoDelete not working in global functional injection (Newer Approach) when connecting to NodeJS

### ISSUE THREAD

**Issue by agus-tin** [GIfatahTH/states_rebuilder#174]
Hello,
I'm trying **global functional injection (Newer Approach)**, by adapting the provided example to use NodeJS calls instead of Firefly, everything is working all right except when I try to use the Delete functionality from the example.

What I have been able to understand is that when the method __interceptorWrapper(_ is called in the dio.dart file, for method=DELETE, the **_data_** object's path looks like _http://10.0.2.2:1337/todos603fb01d344e933cc04e22fd_, which apparently, is missing the "/" between the route and the Id of the object to be deleted.
If I add the "/" manually [http://10.0.2.2:1337/todos**/**603fb01d344e933cc04e22fd] and test it directly in ARC or Insomnia, it works perfectly.

My problem is that I haven't been able to identify which Class (and method) I should intercept to introduce the "/" when the URL is being built

Is this something you can guide me with?
Thanks in advance
Agus

**Comment by GIfatahTH** [comment]
Hi @agus-tin 
I do not think that this is related to states_rebuilder

Could you show me The repository class implementation
