### ISSUE TITLE
Updated Countdown Example has timer bug.

### ISSUE THREAD

**Issue by am2074** [GIfatahTH/states_rebuilder#176]
First off, let me say thank you for the awesome update for States Rebuilder, I've been really enjoying the package so far. I wanted to mention that your countdown timer example has a weird bug that whenever the timer hits halfway, it skips the integer after the middle one for some reason. 
For example, if the timer was set to 10 and I printed each of the values: 
` final timer = middleState.nextSnap.data;
          int d = initialTimer - timer - 1;
          print('$d');`
 
in the terminal you would see: 
 `10
   9
   8 
   7
   6
   5
   3
   2
   1
`
Here, 4 is not shown. So in the ui, it looks like it freezes for two seconds when the timer hits 5 seconds remaining and immediately jumps to 3'. 

Is there anyway to remediate it and ensure this doesn't happen if we have to use a countdown timer or some similar application of these methods? 

Thank you.

**Comment by GIfatahTH** [comment]
Hi @ am2074, good catch man. Thank you very much for your opening this interesting issue.

What is happening here is that the stream emits values from 0 to 10, and in the `middleSnap` hook, we changed it to count form 10 to 0.

The stream        :   0   - 1 - 2 - 3 - 4 - 5 - 6 - 7 - 8 - 9 - 10
The middleSnap:  10 -  9 - 8 - 7 - 6 - 5 - 4 - 3 - 2 - 1 - 0

When the stream emits 5, the state already holds 5, and as by default, states_rebuild will not rebuild listeners if the state does not change, so the `middleSnap` callback will not be called. For this reason, we see 4 escaped.

What I'm doing wrong is comparing the old state with the new state before calling the `middleSnap`.

Now I have solved the problem by simply invoking `middleSnap` before comparing the old and new state. I tried it and it works.

Thank you again for drawing my attention to this very subtle and weird bug.
