### ISSUE TITLE
About the child state with InheritedWidget

### ISSUE THREAD

**Issue by amoslai5128** [GIfatahTH/states_rebuilder#179]
I notice a problem (correct me if there's something wrong) with InheritedWidget about the state between a parent and its inherited child.
If the parent widget gets a new state, both parent and child rebuild, but the child inside doesn't get any update. 

Thanks again for making this amazing package.

```
class ParentWidget extends StatelessWidget {
  const ParentWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ElevatedButton(
            onPressed: () => counter3.setState((s) => s + 1),
            child: counter3
                .rebuilder(() => Text('parent: ' + counter3.state.toString()))),
        Container(
          child: counter3.inherited(
              // onWaiting: () => circularIndicator(),
              key: UniqueKey(),
              stateOverride: () => counter3.state,
              builder: (context) {
                print(counter3.state);
                return const TestInherited();
              }),
        ),
      ],
    );
  }
}

final counter3 = RM.inject<int>(() => 0);

class TestInherited extends StatelessWidget {
  const TestInherited({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final inj = counter3(context);
    return inj.rebuilder(
      () => Column(
        children: [
          Text('-- Inherited Child --'),
          Text(inj.state.toString()),
          Text(counter3.of(context).toString()),
          ElevatedButton(
              onPressed: () => inj.setState((s) => s + 1),
              child: Text('Inside ++')),
        ],
      ),
    );
  }
}

```

**Comment by GIfatahTH** [comment]
Hi @amoslai5128 
Try and comment `stateOverride: () => counter3.state`, and notice then new behaviour: 
```dart
          child: counter3.inherited(
              // onWaiting: () => circularIndicator(),
              key: UniqueKey(),
              // stateOverride: () => counter3.state,
              builder: (context) {
                print(counter3.state);
                return const TestInherited();
              }),
        ),
```

After that try and set   `connectWithGlobal` to false, Notice the new behaviour:

```dart
 Container(
          child: counter3.inherited(
              // onWaiting: () => circularIndicator(),
              key: UniqueKey(),
              stateOverride: () => counter3.state,
              connectWithGlobal: false,
              builder: (context) {
                print(counter3.state);
                return const TestInherited();
              }),
        ),
```

What did you notice?

**Comment by amoslai5128** [comment]
> Hi @amoslai5128
> Try and comment `stateOverride: () => counter3.state`, and notice then new behaviour:
> 
> ```dart
>           child: counter3.inherited(
>               // onWaiting: () => circularIndicator(),
>               key: UniqueKey(),
>               // stateOverride: () => counter3.state,
>               builder: (context) {
>                 print(counter3.state);
>                 return const TestInherited();
>               }),
>         ),
> ```
> 
> After that try and set `connectWithGlobal` to false, Notice the new behaviour:
> 
> ```dart
>  Container(
>           child: counter3.inherited(
>               // onWaiting: () => circularIndicator(),
>               key: UniqueKey(),
>               stateOverride: () => counter3.state,
>               connectWithGlobal: false,
>               builder: (context) {
>                 print(counter3.state);
>                 return const TestInherited();
>               }),
>         ),
> ```
> 
> What did you notice?

Thank you so much, it works very well!  :)

I'm also thinking about should this Inherited State function be suitable for doing some chat messaging. The only use case is to use it for doing message read status(to double ticks).  Would you like to share some experience or suggestions?
