### ISSUE TITLE
call rebuildStates without any listeners

### ISSUE THREAD

**Issue by Nico04** [GIfatahTH/states_rebuilder#18]
I've just started using your great plugin, but quickly I had this error when calling rebuildStates :
"No listener is registered yet"

And yes, it's true, I have no listener set yet, there are added later in my app.
Still I don't understand the error.
For me it's like a ChangeNotifier or a Stream, you can call notifyListener() or add() even if there are nobody listening.

**Comment by hyperpanthera** [comment]
Yeah I have had the same issue and had to program around that.

**Comment by GIfatahTH** [comment]
Thanks for trying the library.

I intentionally added the constrained that Before calling rebuildStates() you have to register at least on listener. The idea is that why notifying a listener that is not registered.

I want to see your case to see why you have to call rebuildStates before registering any listener.

**Comment by Nico04** [comment]
I have a top-level app model, that can change.
I have a Login screen at first, that doesn't need to be changed regarding the model because it only writes data.
Later after login I need to update some screens when this model changes.

I have a sync service that work top-level too and update the model when it syncs from server, and when it does, it calls rebuildStates. But from his point of vue, sometimes there are screen to update, sometime not.

Is that any clearer ?

**Comment by hyperpanthera** [comment]
@Nico04 That was exactly my issue!

**Comment by GIfatahTH** [comment]
If I understand well your case, in simple example bellow. When the app starts the login screen is displayed and the syncMethod() is called. if I stay in the login screen and when the future resolves the rebuildState() is called which results in error because no listener is added. In case I navigate to the home screen before 2 seconds, the home page is registered as listener and when the rebuildStates() is called the home page as expected without any error.

Is this the case?

```dart
class TopLevelModel extends StatesRebuilder {
  String hasData;
  syncMethod() async {
    hasData = "waiting for data ...";
    await Future.delayed(Duration(seconds: 2));
    hasData = "Data is available";
    rebuildStates();
  }
}

//For simplicity I provide the model globally
TopLevelModel model = TopLevelModel();

class LoginScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    model.syncMethod();
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Login Screen"),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text("login screen"),
              RaisedButton(
                child: Text("go to home page"),
                onPressed: () => Navigator.push(context,
                    MaterialPageRoute(builder: (context) => HomePage())),
              )
            ],
          ),
        ),
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("home page"),
        ),
        body: StateBuilder(
          viewModels: [model],
          builder: (_, __) => Center(
            child: Text(model.hasData),
          ),
        ),
      ),
    );
  }
}
```

**Comment by Nico04** [comment]
Your simple example shows an issue that is similar to the one in my project, yes.

**Comment by GIfatahTH** [comment]
The solution is to register the login page as listener so that when you are in the login page and rebuildStates() is called, there is one listener.

```dart
class LoginScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    model.syncMethod();
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Login Screen"),
        ),
        body: StateBuilder(
          viewModels: [model],
          builder: (_, __) => Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text("login screen"),
                RaisedButton(
                  child: Text("go to home page"),
                  onPressed: () => Navigator.push(context,
                      MaterialPageRoute(builder: (context) => HomePage())),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by GIfatahTH** [comment]
You can use `pushReplacement` to make sure that the login page is removed from listener list when you navigate to home page.

In this example I use Injector to provide the model
```
class TopLevelModel extends StatesRebuilder {
  String hasData;
  syncMethod() async {
    hasData = "waiting for data ...";
    await Future.delayed(Duration(seconds: 3));
    hasData = "Data is available";
    print(hasData);
    rebuildStates();
  }
}

class LoginScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context1) {
    print("rebuild");
    return Injector(
      models: [() => TopLevelModel()],
      builder: (_, __) => MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            title: Text("Login Screen"),
          ),
          body: _Body(),
        ),
      ),
    );
  }
}

class _Body extends StatelessWidget {
  final model = Injector.get<TopLevelModel>();
  @override
  Widget build(BuildContext context) {
    return StateBuilder(
      viewModels: [model],
      initState: (_, __) => model.syncMethod(),
      builder: (context, __) {
        return Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text("login screen"),
              RaisedButton(
                child: Text("go to home page"),
                onPressed: () => Navigator.pushReplacement(context,
                    MaterialPageRoute(builder: (context) => HomePage())),
              )
            ],
          ),
        );
      },
    );
  }
}

class HomePage extends StatelessWidget {
  final model = Injector.get<TopLevelModel>();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("home page"),
        ),
        body: StateBuilder(
          viewModels: [model],
          builder: (_, __) => Center(
            child: Text(model.hasData),
          ),
        ),
      ),
    );
  }
}
```

**Comment by Nico04** [comment]
I think I understand your example but when you stay on Login page and rebuildStates() is called, the login page will be rebuild for nothing... So yes it will work but it kind of remove the interest of the plugin which is only rebuilt what's necessary, don't you think?

**Comment by GIfatahTH** [comment]
yes you are right. when the login screen will rebuild unnecessary when the rebuildStates() is called while working in the login screen. But this is not a that big concern if your login page is a lightweight widget. You can wrap the text Widget like shown in the code bellow so that just the static text widget will rebuild.

If it is necessary, I can  add a flag to the rebuildStates() to silent the error. 

```dart
class LoginScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    model.syncMethod();
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Login Screen"),
        ),
        body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                StateBuilder(
                  viewModels: [model],
                  builder: (_, __) => Text("login screen"),
                ),
                RaisedButton(
                  child: Text("go to home page"),
                  onPressed: () => Navigator.push(context,
                      MaterialPageRoute(builder: (context) => HomePage())),
                )
              ],
          ),
        ),
      ),
    );
  }
}

**Comment by Nico04** [comment]
Yes, I think removing or optionning the error seems a good idea, it's cleaner and clearer, don't you think?

**Comment by Nico04** [comment]
Meanwhile I've just wrapped my entire MaterialApp with a StateBuilder with a tag that is never used.
It just remove the error.
Please keep me updated.
I'm moving my whole app structure to your plugin, I love it :)

**Comment by n8crwlr** [comment]
> If it is necessary, I can add a flag to the rebuildStates() to silent the error.

Is it done?

I am new to Dart and Flutter and this package looks very promising 💯  But, this issue is a bit irritating.

> yes you are right. when the login screen will rebuild unnecessary when the rebuildStates() is called while working in the login screen.

> But this is not a that big concern if your login page is a lightweight widget. 

The last one should never be.

The flag sounds ideal to me?

**Comment by GIfatahTH** [comment]
Yes, I add the flag, and it will be pushed soon.
It will look like this
```dart
class TopLevelModel extends StatesRebuilder {
  String hasData;
  syncMethod() async {
    hasData = "waiting for data ...";
    await Future.delayed(Duration(seconds: 3));
    hasData = "Data is available";
    print(hasData);
    if(hasStates) rebuildStates();
  }
}
```

**Comment by n8crwlr** [comment]
@GIfatahTH Can you explain me the part which is a _flag_ in Dart? Is there a typing in `hasData` and `hasStates`? Where is `hasStates` defined?

Sorry about late response, i got _flagged by Github_ yesterday. Feels like the Outlook spam filter, which kills me when i send only a message a week 😒

Thx ☺️

**Comment by GIfatahTH** [comment]
@Nico04 @hyperpanthera @n8crwlr 
I updated the package to solve this issue, I hope it will work! just check `hasObserver ` if true before calling statesRebuilder. I intended to name it `hasStates `but unfortunately `hasObserver ` escaped to the code.

**Comment by hyperpanthera** [comment]
@GIfatahTH Should we always call it when we do rebuildStates? Thanks.

**Comment by GIfatahTH** [comment]
@hyperpanthera  No. You check it only in the rare case where you call rebuildStates before registering the state using StatesBuilder or Injector

**Comment by hyperpanthera** [comment]
@GIfatahTH Thanks, neat update.
