### ISSUE TITLE
injectStream PersistantStore cast error

### ISSUE THREAD

**Issue by samuelstroschein** [GIfatahTH/states_rebuilder#182]
The persistent store API officially supports `injectStream` since version 4.0. However, seems like it's not correctly implemented since it emits the following cast error: 

```dart
The following _CastError was thrown building Directionality(textDirection: ltr):
type '_ControllerStream<Set<int>>' is not a subtype of type 'FutureOr<Set<int>>' in type cast
```

I looked into the tests of persistentStore and found that no test for `injectedStream` exists, only for `injected` and `injectedFuture`. I added an `injectedStream` state to the `injected_persistance2_test.dart` file. The test "Return to previous state and notify listeners when throw error" now fails with the error stated above. 

I created a pull request with the reproducible exception which changed one of the test files [here](https://github.com/samuelstroschein/states_rebuilder/pull/1/files).

**Comment by GIfatahTH** [comment]
Hi @samuelstroschein thanks for the PR.
I'll try and see.
I'm working on a new update where I'll add custom injects for some frequently used controllers similar to InjectedCRUD, InjectedAuth, InjectedTheme, and InjectedI18N. I will solve the issue there.

**Comment by samuelstroschein** [comment]
Little remark: In the test, I use a set of integers. I guess that's not even necessary to reproduce the cast error (but I used a set of objects in my app).

**Comment by GIfatahTH** [comment]
@samuelstroschein 
With the new update I tested persisting the state of injectedStream with no error:

```dart
  testWidgets(
    'injectedStream works persisted state'
    'Case not initially persisted state',
    (tester) async {
      counter = RM.injectStream(
        () => Stream.periodic(Duration(seconds: 1), (num) => num * 10).take(3),
        persist: () => PersistState(With the new update I tested persisting the state of injectedStream with no error:With the new update I tested persisting the state of injectedStream with no error:
          key: 'counter',
        ),
      );
      expect(counter.state, null);
      expect(store.store['counter'], null);

      await tester.pump(Duration(seconds: 1));
      expect(counter.state, 0);
      expect(store.store['counter'], '0');

      await tester.pump(Duration(seconds: 1));
      expect(counter.state, 10);
      expect(store.store['counter'], '10');

      await tester.pump(Duration(seconds: 1));
      expect(counter.state, 20);
      expect(store.store['counter'], '20');
    },
  );

  testWidgets(
    'injectedStream works persisted state'
    'Case the state is already persisted',
    (tester) async {
      // pre-populating store with data
      store.store.addAll({'counter': '10'});
      counter = RM.injectStream(
        () => Stream.periodic(Duration(seconds: 1), (num) => num * 10).take(3),
        persist: () => PersistState(
          key: 'counter',
        ),
      );
     
      expect(counter.state, 10);
      expect(store.store['counter'], '10');

      await tester.pump(Duration(seconds: 1));
      expect(counter.state, 10);
      expect(store.store['counter'], '10');
    },
  );
```
