### ISSUE TITLE
[suggestion] RM.navigate.toNamed with transition param

### ISSUE THREAD

**Issue by maimake** [GIfatahTH/states_rebuilder#185]
It would be better using transition param like Fluro, cause a page will not be presented awalys use the same transition.

Wish to add transition param like 
```flutter
RM.navigate.toNamed('/routeName', transition: TransitionType.none);
```

And adding more preset transitions like
```flutter
enum TransitionType {
  native,
  nativeModal,
  inFromLeft,
  inFromTop,
  inFromRight,
  inFromBottom,
  fadeIn,
  custom,
  material,
  materialFullScreenDialog,
  cupertino,
  cupertinoFullScreenDialog,
  none,
}
```

**Comment by GIfatahTH** [comment]
I plan to separate navigation into a new package and will add more page transitions.
