### ISSUE TITLE
[New Feature] InjectedTextEditing and InjectedForm 

### ISSUE THREAD

**Issue by GIfatahTH** [GIfatahTH/states_rebuilder#187]
`TextEditingController` is yet another controller that has a dedicated Injected state that will make it easier for us: 
- Create and automatically dispose of a `TextEditingController`,
- Associate the `TextEditingController` with a `TextField` or `TextFormField`,
- Change the value of the text and cache it,
- Easily work with a collection of TextFields (Form).
- Manage `FocusNote`, to dynamically change the focus to the next field to edit.

## Creation of the `InjectedTextEditing` state
Let's take the case of two `TextField`s: one for the email and the other for the password.
``` dart
final email =  RM.injectTextEditing():

final password = RM.injectTextEditing(
  text: '',
  selection: TextSelection.collapsed(offset: -1),
  composing: TextRange.empty,
  validator: (String? value) {
    if (value!.length < 6) {
      return "Password must have at least 6 characters";
    }
    return null;
  },
  autoValidate: true,
  autoDispose: true,
);
```
- `text`,` selection` and `composing` used as in Flutter.
- The `validator` callback returns an error string or null if the field is valid.
- By default, text input is automatically validated while the user is typing. If set to false, the input text is only validated by calling the `email.validate ()` method.
- The `InjectedTextEditing` is automatically deleted when it is no longer used. If you want to keep the data and use it in another `TextField`, set` autoDispose` to false.

## Link the InjectedTextEditing with a TextField:
```dart
//Basically, define only the controller
//No need to define onChange nor onSave callbacks
TextField(
    controller: email.controller,
),

//Or for full features
TextField(
    controller: email.controller,
    focusNode: email.focusNode, //It is auto disposed of.
    decoration:  InputDecoration(
        errorText: email.error, //To display the error message.
    ),
    onSubmitted: (_) {
        //Focus on the password TextField after submission
        password.focusNode.requestFocus();
    },
),
```

## Consuming the valid data after submission:
```dart
_submit() {
  if (email.isValid && password.isValid) {
      print('Authenticate with ${email.text} and ${password.text}');
  }
}
```
- You can reset any `TextField` to its initial text using:
```dart
email.reset();
password.reset();
```
## Working with forms:
If the application you are working on contains dozens of TextFields, it becomes tedious to process each field individually. `Form` helps us collect many TextFields and manage them as a unit.

### Injected the form state:
```dart
final form = RM.injectForm(
  //optional parameter
  autovalidateMode: AutovalidateMode.disable,
);
```
- `InjectedForm` has one optional parameter. “autovalidateMode” is of type “AutovalidateMode”. As in Flutter, It can take one of three enumeration values:
      - `AutovalidateMode.disable`: The form is validated manually by calling` form.validate()`
      - `AutovalidateMode.always`: The form is always validated
      - `AutovalidateMode.onUserInteraction`: The form is not validated until the user has started typing.

### Link InjectedForm to InjectedTextEditing states
In the user interface, we put the `TextField`s that we want to associate with the form inside the` On.form` widget:

```dart
On.form(
  () => Column(
    children: <Widget>[
        TextField(
            focusNode: email.focusNode,
            controller: email.controller,
            decoration: InputDecoration(
              errorText: email.error,
            ),
            onSubmitted: (_) {
              //request the password node
              password.focusNode.requestFocus();
            },
        ),
        TextField(
            focusNode: password.focusNode,
            controller: password.controller,
            decoration: new InputDecoration(
              errorText: password.error,
            ),
            onSubmitted: (_) {
              //request the submit button node
              form.submitFocusNode.requestFocus();
            },
        ),
        ElevatedButton(
            focusNode: form.submitFocusNode,
            onPressed: (){
                if(form.validate()){
                    _submit();
                }
            },
            child: Text('Submit'),
        )
    ],
  ),
).listenTo(form),
```
- We only use `TextField` widgets, no need to use` TextFormField`
- To validate all fields, use: `form.validate()`
- To reset all fields to their initial values, use: `form.reset()`
- To check that all fields are valid, use `form.isValid`
- Each `InjectedTextEditing` has an associated` FocusNode`.
- The `InjectedForm`  is associated with a FocusNote to be used in the submit button.
- All `TextEditingControllers` and `FocusNotes` are automatically disposed of when they are no longer in use.

**Comment by tk2232** [comment]
This is a great addition. It would be nice if the FocusNode focuses on the first field with an error.

```dart

  final form = RM.injectForm(
    autovalidateMode: AutovalidateMode.disabled,
    focusOnError: true
  );

  final bool focusOnError = this.focusOnError;
  @override
  bool validate() {
    bool isNotValid = false;
    FocusNode? focusNodeFirst = null;
    for (var field in _textFields) {
      isNotValid = !field.validate() || isNotValid;
      if(isNotValid && focusNodeFirst == null && focusOnError){
        focusNodeFirst = field.focusNode;
      }
    }
    if(focusNodeFirst != null) {
      focusNodeFirst.requestFocus();
    }
    return !isNotValid;
  }

```

**Comment by GIfatahTH** [comment]
@tk2232 great idea.

**Comment by tk2232** [comment]
Another great feature for me would be to validate first when the focus changes.

```dart

# injected_text_editing.dart

  final bool validateOnFocusChange;

  FocusNode get focusNode {
    if (_focusNode != null) {
      return _focusNode!;
    }

    _focusNode ??= FocusNode();
    //To cache the auto focused TextField
    SchedulerBinding.instance!.addPostFrameCallback((_) {
      SchedulerBinding.instance!.addPostFrameCallback((_) {
        //After too frame, to ensure the focused field is initialized
        if (_focusNode?.hasFocus == true) {
          final form =
          (this as InjectedTextEditingImp).form as InjectedFormImp?;
          form?._autoFocusedNode = _focusNode;
        }
      });
    });
    if(validateOnFocusChange){
      _focusNode!.addListener(() {
        if(!_focusNode!.hasFocus) {
          validate();
        }
      });
    }
    return _focusNode!;
  }
```

**Comment by tk2232** [comment]
And one feature to inject manually errors. It's sometimes nice to throw an error without the validator. For example, when checking whether passwords from two TextFields match

```dart
# injected_text_editing.dart

  @override
  void injectError(String msg) {
    _errorText = msg;
    snapState = snapState.copyToHasError(_errorText!, data: this.text);
    notify();
  }
```

**Comment by GIfatahTH** [comment]
@tk2232 
>And one feature to inject manually errors. It's sometimes nice to throw an error without the validator. For example, when checking whether passwords from two TextFields match. And one option to clear the error.

When it comes to passwords  matching, it is very easy :

```dart
final password = RM.injectTextEditing(
  validator: (text) {
    if (text!.length < 5) {
      return 'must be greater than 5 characters';
    }
  },
);
final confirmPassword = RM.injectTextEditing(
  validator: (text) {
    if (password.text != text) {
      return 'Passwords do not match';
    }
  },
);
```

**Comment by GIfatahTH** [comment]
@tk2232 
>Another great feature for me would be to validate first when the focus changes.

Validating when a TextField gets foucus is almost similar to validating when the user starts typing. Isn't it?

**Comment by tk2232** [comment]
> @tk2232
> 
> > Another great feature for me would be to validate first when the focus changes.
> 
> Validating when a TextField gets foucus is almost similar to validating when the user starts typing. Isn't it?

But there is a small difference. If the user starts typing and the error is displayed directly is a more aggressive method is to ask for the correct input.

In some fields you shouldn't be so aggressive. It's a little more user friendly. Anyone can enter a username and give it a try before the error appears. For more difficult fields like passwords, show the mistake as you type to encourage them to make fewer mistakes.

**Comment by tk2232** [comment]
Here is a example with all three features. Check the _submit() function

```dart
import 'package:flutter/material.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

class TestingForm extends StatelessWidget {
  final form =
      RM.injectForm(autovalidateMode: AutovalidateMode.onUserInteraction);

  // Everyone can type an email. Give it a try. validateOnFocusChange: true
  final email = RM.injectTextEditing(
    autoDispose: false,
    validateOnFocusChange: true,
    validator: (String value) {
      if (!value.contains('@')) {
        return "That's not an email.";
      }
      return null;
    },
  );

  // Everyone can type a username. Give it a try. validateOnFocusChange: true
  final username = RM.injectTextEditing(
    autoDispose: false,
    validateOnFocusChange: true,
    validator: (String value) {
      if (value.length < 4) {
        return "Usernames must have at least 4 characters";
      }
      return null;
    },
  );

  // Let's be a little bit more aggressive. validateOnFocusChange: false, autoValidate: true
  final password = RM.injectTextEditing(
    text: '',
    selection: TextSelection.collapsed(offset: -1),
    composing: TextRange.empty,
    validator: (String value) {
      if (value.length < 6) {
        return "Password must have at least 6 characters";
      }
      return null;
    },
    autoValidate: true,
    autoDispose: false,
  );

  Future<String> _validateUsernameOnServer() async {
    return await Future.delayed(
        Duration(seconds: 1), () => 'Username already in use!');
  }

  Future<String> _validateEmailOnServer() async {
    return await Future.delayed(
        Duration(seconds: 1), () => 'The email is blocked!');
  }

  void _submit() async {
    String usernameError = await _validateUsernameOnServer();
    String emailError = await _validateEmailOnServer();
    username.injectError(usernameError);
    email.injectError(emailError);
  }

  @override
  Widget build(BuildContext context) {
    return On.form(() => Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            On(
              () => TextField(
                focusNode: email.focusNode,
                controller: email.controller,
                decoration: InputDecoration(
                  errorText: email.error,
                ),
                onSubmitted: (_) {
                  //request the username node
                  username.focusNode.requestFocus();
                },
              ),
            ).listenTo(email),
            On(
              () => TextField(
                focusNode: username.focusNode,
                controller: username.controller,
                decoration: new InputDecoration(
                  errorText: username.error,
                ),
                onSubmitted: (_) {
                  //request the password node
                  password.focusNode.requestFocus();
                },
              ),
            ).listenTo(username),
            TextField(
              focusNode: password.focusNode,
              controller: password.controller,
              decoration: new InputDecoration(
                errorText: password.error,
              ),
              onSubmitted: (_) {
                //request the submit button node
                form.submitFocusNode.requestFocus();
              },
            ),
            ElevatedButton(
              focusNode: form.submitFocusNode,
              onPressed: () {
                if (form.validate()) {
                  _submit();
                }
              },
              child: Text('Submit'),
            ),
          ],
        )).listenTo(form);
  }
}

```

**Comment by GIfatahTH** [comment]
@tk2232 
Now I understand. You want to validate when the text field loses focus.


I try your example, and I have the following remarks:
- If you are using `On.form`, you don't have to wrap each TextFiled widget with `On` widget to subscribe to the corresponding InjectedTextEditing
   - what is the purpose of setting autoDispose to false?
   - 
Here's what your example will look like after the following refactors:
- I think it's better to use the name `validateOnLoseFocus` and use` validateOnTyping` instead of `autoValidate`,
- I put all Injected states outside the StatelessWidget to keep their state after rebuilding the parent.
- I removed the unnecessary. `On (...). ListenTo ()`  widgets
- instead of `username.injectedError () `I used username.`errorText = ....`
- I used `On.formSubmittion` to display a circular progress indicator while waiting for submission.

What do you think?
```dart
final form = RM.injectForm(
  autovalidateMode: AutovalidateMode.disabled,
  //Optional side effect
  onSubmitting: () => print('onSubmitting'),
  onSubmissionError: (err, ref) => print(err),
);

// Everyone can type an email. Give it a try. validateOnFocusChange: true
final email = RM.injectTextEditing(
  autoDispose: false,
  validateOnLoseFocus: true,
  validator: (String? value) {
    if (!value!.contains('@')) {
      return "That's not an email.";
    }
    return null;
  },
);

// Everyone can type a username. Give it a try. validateOnFocusChange: true
final username = RM.injectTextEditing(
  validateOnLoseFocus: true,
  validator: (String? value) {
    if (value!.length < 4) {
      return "Usernames must have at least 4 characters";
    }
    return null;
  },
);

// Let's be a little bit more aggressive. validateOnFocusChange: false, autoValidate: true
final password = RM.injectTextEditing(
  text: '',
  selection: TextSelection.collapsed(offset: -1),
  composing: TextRange.empty,
  validator: (String? value) {
    if (value!.length < 6) {
      return "Password must have at least 6 characters and other stuff...";
    }
    return null;
  },
  validateOnTyping: true,
);

class TestingForm extends StatelessWidget {
  Future<String> _validateUsernameOnServer() async {
    return await Future.delayed(
      Duration(seconds: 1),
      () => Random().nextBool()
          ? 'Username already in use!'
          : throw Exception('Error'),
    );
  }

  Future<String> _validateEmailOnServer() async {
    return await Future.delayed(
        Duration(seconds: 1), () => 'The email is blocked!');
  }

  void _submit() async {
    username.errorText = await _validateUsernameOnServer();
    email.errorText = await _validateEmailOnServer();
  }

  @override
  Widget build(BuildContext context) {
    return On.form(
      () => Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          TextField(
            focusNode: email.focusNode,
            controller: email.controller,
            decoration: InputDecoration(
              errorText: email.error,
            ),
            onSubmitted: (_) {
              //request the username node
              username.focusNode.requestFocus();
            },
          ),
          TextField(
            focusNode: username.focusNode,
            controller: username.controller,
            decoration: new InputDecoration(
              errorText: username.error,
            ),
            onSubmitted: (_) {
              //request the password node
              password.focusNode.requestFocus();
            },
          ),
          TextField(
            focusNode: password.focusNode,
            controller: password.controller,
            decoration: new InputDecoration(
              errorText: password.error,
            ),
            onSubmitted: (_) {
              //request the submit button node
              form.submitFocusNode.requestFocus();
            },
          ),
          On.formSubmission(
            onSubmitting: () => CircularProgressIndicator(),
            // onSubmissionError: (error, refresh) => IconButton(
            //   icon: Icon(Icons.refresh),
            //   onPressed: () => refresh(),
            // ),
            child: ElevatedButton(
              focusNode: form.submitFocusNode,
              onPressed: () {
                if (form.validate()) {
                  form.setState((_) => _submit());
                }
              },
              child: Text('Submit'),
            ),
          ).listenTo(form),
        ],
      ),
    ).listenTo(form);
  }
}
```

**Comment by tk2232** [comment]
That's great. I think it's a little bit more user friendly.
Very often forms have to be validated on the server side. This gives you more control over the forms.
InjectedTextEditing makes life a lot easier :-)

autoDispose can be ignored, I've only tested something.

**Comment by tk2232** [comment]
I only wrapped email TextField and username TextField with the on widget. Without the on widget on these field they won't rebuild when the async task is complete

**Comment by GIfatahTH** [comment]
@tk2232  check this, I polished the API to default to validateOnLoseFocus and autoFocusOnFirstError and  added submit, onSubmitting, and submitted callbacks to `RM.injectedForm.`

```dart
// validateOnLoseFocus: true is the default choice
final email = RM.injectTextEditing(
  validator: (String? value) {
    if (!value!.contains('@')) {
      return "That's not an email.";
    }
    return null;
  },
);

final username = RM.injectTextEditing(
  validator: (String? value) {
    if (value!.length < 4) {
      return "Usernames must have at least 4 characters";
    }
    return null;
  },
);

// Let's be a little bit more aggressive. validateOnTyping: true
final password = RM.injectTextEditing(
  validator: (String? value) {
    if (value!.length < 6) {
      return "Password must have at least 6 characters and other stuff...";
    }
    return null;
  },
  validateOnTyping: true,
);

///autoFocusOnFirstError defaults to true
final form = RM.injectForm(
  submit: () async {
    username.errorText = await _validateUsernameOnServer();
    email.errorText = await _validateEmailOnServer();
  },
  onSubmitting: () => print('Waiting for submission to end ... '),
  onSubmitted: () =>
      print('form successfully submitted (Navigate to HomeScreen'),
);

Future<String> _validateUsernameOnServer() async {
  return await Future.delayed(
    Duration(seconds: 1),
    () => 'Username already in use!',
  );
}

Future<String> _validateEmailOnServer() async {
  return await Future.delayed(
    Duration(seconds: 1),
    () => 'The email is blocked!',
  );
}

class TestingForm extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return On.form(
      () => Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          TextField(
            focusNode: email.focusNode,
            controller: email.controller,
            decoration: InputDecoration(
              errorText: email.error,
            ),
            onSubmitted: (_) {
              //request the username node
              username.focusNode.requestFocus();
            },
          ),
          TextField(
            focusNode: username.focusNode,
            controller: username.controller,
            decoration: InputDecoration(
              errorText: username.error,
            ),
            onSubmitted: (_) {
              //request the password node
              password.focusNode.requestFocus();
            },
          ),
          TextField(
            focusNode: password.focusNode,
            controller: password.controller,
            decoration: InputDecoration(
              errorText: password.error,
            ),
            onSubmitted: (_) {
              //request the submit button node
              form.submitFocusNode.requestFocus();
            },
          ),
          On.formSubmission(
            onSubmitting: () => CircularProgressIndicator(),
            child: ElevatedButton(
              focusNode: form.submitFocusNode,
              onPressed: () {
                //Will check for form validation, if so, it will call the defined
                //submit callback.
                form.submit();
              },
              child: Text('Submit'),
            ),
          ).listenTo(form),
        ],
      ),
    ).listenTo(form);
  }
}
```

**Comment by tk2232** [comment]
Yes that works perfectly. 

For me is the best experience to turn on validateOnLoseFocus: true and validateOnTyping: true for the most fields.

Workflow:
1. Trust the user that they are doing it right. => loose focus => validate
2. if isNotValid
    1. Show the error
    2. Assist the user in typing. Keep showing the error until they get it right
3. finish


```dart
final username = RM.injectTextEditing(
  validator: (String? value) {
    if (value!.length < 4) {
      return "Usernames must have at least 4 characters";
    }
    return null;
  },
  validateOnLoseFocus: true,
  validateOnTyping: true,
);
```

**Comment by GIfatahTH** [comment]
@tk2232 
I added a small improvement.
Once a field is validated after losing focus, and if it is not valid, `validateOnTyping` is enabled so that the user receives feedback while typing.

I really want to thank you for your contribution. Now the `TextEditingController` abstraction using `InjectedTextEditign` and `InjectedForm` deserves the value it has.

If you have the time, it would be very helpful to take a look at other custom injected abstraction and see what needs improvement. Also, if you have any Flutter controllers that you want to abstract, please tell me.

Until now we have: 
- For production time saving: InjectedAuth, InjectedCRUD, InjectedTheme, InjectedI18N, 
- For controllers: InjectedAnimation, InjectedTextEditing, InjectedForm, and InjectedScrolling

**Comment by amoslai5128** [comment]
@GIfatahTH 
Thank you for bring these amazing updates and great features to the community
Still working if I wrap the `formSubmission` outside the `On.form`?
```dart
      body: On.form(
      () => Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
           TextField(...),
           TextField(...)
            ....
        ],
       ).listenTo(form),
       //Sometimes I would place it outside the body
       floatingActionButton: On.formSubmission(
            onSubmitting: () => CircularProgressIndicator(),
            child: FloatingActionButton(
              focusNode: form.submitFocusNode,
              onPressed: () {
                form.submit();
              },
              child: Text('Submit'),
            ),
       ).listenTo(form),
```

**Comment by GIfatahTH** [comment]
@amoslai5128 
Yes, it works outside `On.form` and you can use as many `On.formSubmission` as you want

**Comment by tk2232** [comment]
reset() is not resetting the error.

I think there is one missing line

```dart
  @override
  void reset() {
    _controller?.text = initialValue;
//this line is missing
   error = null;
  }
```

**Comment by GIfatahTH** [comment]
@tk2232 
It is fixed in the dev branch. Can you confirm that is works?

**Comment by amoslai5128** [comment]
@GIfatahTH Ga
What's the best practice to deal with the dynamic form? 
Sometimes I might need to add/delete a number of `Textfield` widgets inside the form.

**Comment by amoslai5128** [comment]
> ```dart
> _confirmationPassword
> ```

@GIfatahTH 
Thank you for the reply, what if a state can be duplicate used to generate for `TextField`, and rebuilds independently? Can I use widget-wise injection? 
For example:
```dart
// A common widget state
final additionalField = RM.injectTextEditing(
  validator: (String? value) {
    if (value!.length < 4) {
      return "Notes must have at least 4 characters";
    }
    return null;
  },
);

final duplicateFieldItem = RM.injectTextEditing(()=> throw UnimplementedError());

class .... {
@overrider
Widget build(context) {
  ....
  ListView(
   itemCount: numberOfFields.state.length,
    itemBuilder: (BuildContext context, int index) {
      return itemData.inherited(
          stateOverride : ()=> items[index],
          builder: (BuildContext context)=>  TextField(controller: duplicateFieldItem.controller, 
                       focusNode: duplicateFieldItem.focusNode, ....  ),
      )
    }
  ),
}
}

```

**Comment by GIfatahTH** [comment]
>Thank you for the reply, what if a state can be duplicate used to generate for multipleTextField widgets, and rebuilds independently? Can I use widget-wise injection?

I didn't get your case, could you give more information?

**Comment by tk2232** [comment]
> @tk2232
> It is fixed in the dev branch. Can you confirm that it works?

After this commit I got following error

```stack
E/flutter (31399): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (31399): #0      InjectedTextEditingImp.reset (package:states_rebuilder/src/injected/injected_text_editing/injected_text_editing.dart:233:13)
E/flutter (31399): #1      _animateExpand (package:.../ui/pages/testing_pages/sign_in_up_card.dart:61:20)
E/flutter (31399): <asynchronous suspension>
```

**Comment by amoslai5128** [comment]
> > Thank you for the reply, what if a state can be duplicate used to generate for multipleTextField widgets, and rebuilds independently? Can I use widget-wise injection?
> 
> I didn't get your case, could you give more information?

@GIfatahTH 
Here is an example: https://www.coderzheaven.com/2021/04/04/creating-dynamic-forms-get-data-from-dynamic-forms-in-flutter/

I've no idea how to let these generated textfields rebuild independently.

**Comment by GIfatahTH** [comment]
@amoslai5128 
Please try this:
```dart
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

void main() {
  runApp(_App());
}

final form = RM.injectForm(
  autovalidateMode: AutovalidateMode.disabled,
);
final List<Map<String, dynamic>> _values = [];

class _App extends StatelessWidget {
  const _App({Key? key}) : super(key: key);

  String get _result {
    final r = _values
        .map((e) => {
              'id': e['id'],
              'value': (e['value'] as InjectedTextEditing).state,
            })
        .toList();
    return _jsonPrettier(r);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: Text('Dynamic Form'),
          actions: [
            IconButton(
              icon: Icon(Icons.add),
              onPressed: () async {
                _values.add({
                  'id': _values.length,
                  'value': RM.injectTextEditing(
                    validator: (val) {
                      if (val!.length < 3) {
                        return 'INVALID FIELD';
                      }
                    },
                    validateOnLoseFocus: false,
                    onTextEditing: (_) {
                      form.notify();
                    },
                  )..focusNode.requestFocus(),
                });
                form.notify();
              },
            ),
            IconButton(
              icon: Icon(Icons.refresh),
              onPressed: () async {
                _values.clear();
                form.notify();
              },
            )
          ],
        ),
        body: Container(
          padding: EdgeInsets.all(20.0),
          child: On.form(
            () => Column(
              children: [
                Flexible(
                  child: ListView.builder(
                    shrinkWrap: true,
                    itemCount: _values.length,
                    itemBuilder: (context, index) {
                      return _row(index);
                    },
                  ),
                ),
                SizedBox(height: 10.0),
                ElevatedButton(
                  onPressed: () {
                    form.validate();
                  },
                  child: Text('Validate Form'),
                ),
                SizedBox(height: 10.0),
                Text(_result),
              ],
            ),
          ).listenTo(form),
        ),
      ),
    );
  }

  _row(int index) {
    final id = _values[index]['id'];
    final InjectedTextEditing injectedTextEditing = _values[index]['value'];
    return Row(
      children: [
        Text('ID: $id'),
        SizedBox(width: 30),
        Expanded(
          child: TextField(
            controller: injectedTextEditing.controller,
            focusNode: injectedTextEditing.focusNode,
            decoration: InputDecoration(
              errorText: injectedTextEditing.error,
            ),
          ),
        ),
        IconButton(
          onPressed: () {
            _values.removeWhere((map) {
              return map["id"] == id;
            });
            form.notify();
          },
          icon: Icon(Icons.delete),
        )
      ],
    );
  }

  String _jsonPrettier(Object obj) {
    final encoder = JsonEncoder.withIndent('    ');
    return encoder.convert(obj);
  }
}
```

**Comment by tk2232** [comment]
I don't know if that is a bug but validateOnLoseFocus is not working anymore after reset

validateOnLoseFocus is working.
press reset button
validateOnLoseFocus is not working anymore

```dart
import 'package:flutter/material.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

final password = RM.injectTextEditing(
  validateOnLoseFocus: true,
  text: '',
  selection: TextSelection.collapsed(offset: -1),
  composing: TextRange.empty,
  validator: (String? value) {
    if (value!.length < 6) {
      //TODO: implement
      return "Password must have at least 6 characters";
    }
    return null;
  },
);

final InjectedTextEditing rePassword = RM.injectTextEditing(
  validateOnLoseFocus: true,
  text: '',
  selection: TextSelection.collapsed(offset: -1),
  composing: TextRange.empty,
  validator: (String? value) {
    if (password.text != rePassword.text) {
      //TODO: implement
      return "Passwords are not equal!";
    } else if (value!.length < 6) {
      return "Test";
    }
    return null;
  },
);

class TestingTextFields extends StatelessWidget {
  const TestingTextFields({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          On(
            () => TextField(
              focusNode: password.focusNode,
              controller: password.controller,
              decoration: InputDecoration(
                errorText: password.error,
              ),
            ),
          ).listenTo(password),
          On(
            () => TextField(
              focusNode: rePassword.focusNode,
              controller: rePassword.controller,
              decoration: InputDecoration(
                errorText: rePassword.error,
              ),
            ),
          ).listenTo(rePassword),
          ElevatedButton(
            onPressed: () {
              password.reset();
              rePassword.reset();
            },
            child: Text('Reset'),
          ),
        ],
      ),
    );
  }
}
```

**Comment by amoslai5128** [comment]
> @amoslai5128
> Please try this:
> 
> ```dart
> import 'dart:convert';
> 
> import 'package:flutter/material.dart';
> import 'package:states_rebuilder/states_rebuilder.dart';
> 
> void main() {
>   runApp(_App());
> }
> 
> final form = RM.injectForm(
>   autovalidateMode: AutovalidateMode.disabled,
> );
> final List<Map<String, dynamic>> _values = [];
> 
> class _App extends StatelessWidget {
>   const _App({Key? key}) : super(key: key);
> 
>   String get _result {
>     final r = _values
>         .map((e) => {
>               'id': e['id'],
>               'value': (e['value'] as InjectedTextEditing).state,
>             })
>         .toList();
>     return _jsonPrettier(r);
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       debugShowCheckedModeBanner: false,
>       home: Scaffold(
>         appBar: AppBar(
>           title: Text('Dynamic Form'),
>           actions: [
>             IconButton(
>               icon: Icon(Icons.add),
>               onPressed: () async {
>                 _values.add({
>                   'id': _values.length,
>                   'value': RM.injectTextEditing(
>                     validator: (val) {
>                       if (val!.length < 3) {
>                         return 'INVALID FIELD';
>                       }
>                     },
>                     validateOnLoseFocus: false,
>                     onTextEditing: (_) {
>                       form.notify();
>                     },
>                   )..focusNode.requestFocus(),
>                 });
>                 form.notify();
>               },
>             ),
>             IconButton(
>               icon: Icon(Icons.refresh),
>               onPressed: () async {
>                 _values.clear();
>                 form.notify();
>               },
>             )
>           ],
>         ),
>         body: Container(
>           padding: EdgeInsets.all(20.0),
>           child: On.form(
>             () => Column(
>               children: [
>                 Flexible(
>                   child: ListView.builder(
>                     shrinkWrap: true,
>                     itemCount: _values.length,
>                     itemBuilder: (context, index) {
>                       return _row(index);
>                     },
>                   ),
>                 ),
>                 SizedBox(height: 10.0),
>                 ElevatedButton(
>                   onPressed: () {
>                     form.validate();
>                   },
>                   child: Text('Validate Form'),
>                 ),
>                 SizedBox(height: 10.0),
>                 Text(_result),
>               ],
>             ),
>           ).listenTo(form),
>         ),
>       ),
>     );
>   }
> 
>   _row(int index) {
>     final id = _values[index]['id'];
>     final InjectedTextEditing injectedTextEditing = _values[index]['value'];
>     return Row(
>       children: [
>         Text('ID: $id'),
>         SizedBox(width: 30),
>         Expanded(
>           child: TextField(
>             controller: injectedTextEditing.controller,
>             focusNode: injectedTextEditing.focusNode,
>             decoration: InputDecoration(
>               errorText: injectedTextEditing.error,
>             ),
>           ),
>         ),
>         IconButton(
>           onPressed: () {
>             _values.removeWhere((map) {
>               return map["id"] == id;
>             });
>             form.notify();
>           },
>           icon: Icon(Icons.delete),
>         )
>       ],
>     );
>   }
> 
>   String _jsonPrettier(Object obj) {
>     final encoder = JsonEncoder.withIndent('    ');
>     return encoder.convert(obj);
>   }
> }
> ```

Thanks :) It works perfectly.

**Comment by amoslai5128** [comment]
> I don't know if that is a bug but validateOnLoseFocus is not working anymore after reset
> 
> validateOnLoseFocus is working.
> press reset button
> validateOnLoseFocus is not working anymore
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:states_rebuilder/states_rebuilder.dart';
> 
> final password = RM.injectTextEditing(
>   validateOnLoseFocus: true,
>   text: '',
>   selection: TextSelection.collapsed(offset: -1),
>   composing: TextRange.empty,
>   validator: (String? value) {
>     if (value!.length < 6) {
>       //TODO: implement
>       return "Password must have at least 6 characters";
>     }
>     return null;
>   },
> );
> 
> final InjectedTextEditing rePassword = RM.injectTextEditing(
>   validateOnLoseFocus: true,
>   text: '',
>   selection: TextSelection.collapsed(offset: -1),
>   composing: TextRange.empty,
>   validator: (String? value) {
>     if (password.text != rePassword.text) {
>       //TODO: implement
>       return "Passwords are not equal!";
>     } else if (value!.length < 6) {
>       return "Test";
>     }
>     return null;
>   },
> );
> 
> class TestingTextFields extends StatelessWidget {
>   const TestingTextFields({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Padding(
>       padding: const EdgeInsets.all(16.0),
>       child: Column(
>         mainAxisAlignment: MainAxisAlignment.center,
>         children: [
>           On(
>             () => TextField(
>               focusNode: password.focusNode,
>               controller: password.controller,
>               decoration: InputDecoration(
>                 errorText: password.error,
>               ),
>             ),
>           ).listenTo(password),
>           On(
>             () => TextField(
>               focusNode: rePassword.focusNode,
>               controller: rePassword.controller,
>               decoration: InputDecoration(
>                 errorText: rePassword.error,
>               ),
>             ),
>           ).listenTo(rePassword),
>           ElevatedButton(
>             onPressed: () {
>               password.reset();
>               rePassword.reset();
>             },
>             child: Text('Reset'),
>           ),
>         ],
>       ),
>     );
>   }
> }
> ```

@GIfatahTH

**Comment by GIfatahTH** [comment]
@tk2232 

Again, thank you for raising my attention to these edge cases. 

The issue is fixed and it will be pushed to the dev channel sooner.

**Comment by Prn-Ice** [comment]
Hi, how do you make the `InjectedForm` work with other `FormField`s like the `DropdownButtonFormField` that has no `TextEditingController`?

**Comment by GIfatahTH** [comment]
@Prn-Ice good point.

This deserves a new issue,please open a new issue to comment below!

**Comment by amoslai5128** [comment]
> Hi, how do you make the `InjectedForm` work with other `FormField`s like the `DropdownButtonFormField` that has no `TextEditingController`?

I haven't tried it, but I've found this [example](https://stackoverflow.com/questions/52926335/how-to-validate-dropdown-button-in-flutter).
From the example, I think an `RM.inject` should be defined as for keeping the state of the selected item.

NOTE: The `Validator` in DropdownButtonFormField was deprecated, and should use `AutovalidateMode` instead, at [official doc](https://api.flutter.dev/flutter/widgets/AutovalidateMode-class.html).

**Comment by Prn-Ice** [comment]
> > Hi, how do you make the `InjectedForm` work with other `FormField`s like the `DropdownButtonFormField` that has no `TextEditingController`?
> 
> I haven't tried it, but I've found this [example](https://stackoverflow.com/questions/52926335/how-to-validate-dropdown-button-in-flutter).
> From the example, I think an `RM.inject` should be defined as for keeping the state of the selected item.
> 
> NOTE: The `Validator` in DropdownButtonFormField was deprecated, and should use `AutovalidateMode` instead, at [official doc](https://api.flutter.dev/flutter/widgets/AutovalidateMode-class.html).

This would require wrapping with a form, adding a key and probably using a statefull widget.
