### ISSUE TITLE
`setState` doesn't notify everytime

### ISSUE THREAD

**Issue by shripal17** [GIfatahTH/states_rebuilder#198]
I have persistently faced this issue multiple times in my apps across various platforms. After successfully modifying properties of an injected object, notify doesn't get called properly.
In some cases it gets called, in others it doesn't.

Am I missing something here? My object is mutable, so this should work. 

As a workaround, I have to call notify every time after setting the state.

**Comment by shripal17** [comment]
Using the latest null-safe v4.x

**Comment by amoslai5128** [comment]
> I have persistently faced this issue multiple times in my apps across various platforms. After successfully modifying properties of an injected object, notify doesn't get called properly.
> In some cases it gets called, in others it doesn't.
> 
> Am I missing something here? My object is mutable, so this should work.
> 
> As a workaround, I have to call notify every time after setting the state.


Yes, for current version, I've found a way to solve this:
```Dart
// Don't
person.setState((s) => s.name = 'Ben');


// Do
person.setState((s){ s.name = 'Ben'; });
```

**Comment by shripal17** [comment]
> > I have persistently faced this issue multiple times in my apps across various platforms. After successfully modifying properties of an injected object, notify doesn't get called properly.
> > In some cases it gets called, in others it doesn't.
> > Am I missing something here? My object is mutable, so this should work.
> > As a workaround, I have to call notify every time after setting the state.
> 
> Yes, for current version, I've found a way to solve this:
> 
> ```dart
> // Don't
> person.setState((s) => s.name = 'Ben');
> 
> 
> // Do
> person.setState((s){ s.name = 'Ben'; });
> ```

Wow, such a simple fix. Thanks.

I would suggest to mention this in the breaking changes wiki because old users like us are used to returning in `setState`

**Comment by GIfatahTH** [comment]
@shripal17 Thanks for the issue,

Is this kind of example reflects your case:

```dart
void main(List<String> args) {
  runApp(_App());
}

class _App extends StatelessWidget {
  const _App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: _Body(),
      ),
    );
  }
}

class User {
  String name = 'Tedy';
}

final user = RM.inject(() => User());

class _Body extends StatelessWidget {
  const _Body({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        On(() => Text('${user.state.name}')).listenTo(user),
        ElevatedButton(
          onPressed: () => user.setState((s) {
            s.name = 'Bob';
          }),
          child: Text('+'),
        ),
      ],
    );
  }
}

```


@amoslai5128 

I think this person.setState((s) => s.name = 'Ben'); will throw as descried in this issue #183

**Comment by shripal-is-in** [comment]
Yes.
This works properly
```dart
user.setState((s) {
  s.name = 'Bob';
});
```
But, this doesn't
```dart
user.setState(s) => s.name = 'Bob');
```
But, this also works properly
```dart
user.setState(s) => s..name = 'Bob');
```

**Comment by shripal17** [comment]
Yes.
This works properly
```dart
user.setState((s) {
  s.name = 'Bob';
});
```
But, this doesn't
```dart
user.setState(s) => s.name = 'Bob');
```
But, this also works properly
```dart
user.setState(s) => s..name = 'Bob');
```

**Comment by amoslai5128** [comment]
> ```dart
> 'Bob
> ```
@shripal17 
I think it's correct way to do that, exception exists in `user.setState(s) => s.name = 'Bob');` because it just returns a value of `name` but `user` object, then throw a logical error kind of makes sense.

@GIfatahTH 
I've read the post https://github.com/GIfatahTH/states_rebuilder/issues/183#issuecomment-818753894. That being said, would it be a good idea to warn the developer by checking the return type inside the `setState()`, when it's nullable type?

Correct me if there's something wrong.
```Dart
/*  ---------     IDEA ONLY        ---------  */

// Case 1: Default only Notifying when setState returned a double type, otherwise warns the developers
// 👌  Good
final double = RM.Inject<double>((s)=>0.0);
// ⛔  Warn
final double = RM.Inject<double>((s)=> "");

// Case 2: Notifying all the listeners when setState returned a null / dobule type
final nullableDouble = RM.Inject<double?>((s)=> null);
```

**Comment by shripal17** [comment]
> @shripal17
> I think it's the correct way, exception exists in `user.setState(s) => s.name = 'Bob');` because it just returns a value of `name` but `user` object, nothing happended from a logical error kind of makes sense.
> 
Yes, that's fine, we can work with that. But my point being that we should mention this in the breaking changes file, because in 3.x, we were used to returning anything and it would work fine.

It's been almost a month since we have been using 4.x, but only until yesterday I figured out the solution to this problem when you replied. And it caused a lot of frustration when the lib wasn't notifying setState changes

**Comment by amoslai5128** [comment]
> > @shripal17
> > I think it's the correct way, exception exists in `user.setState(s) => s.name = 'Bob');` because it just returns a value of `name` but `user` object, nothing happended from a logical error kind of makes sense.
> 
> Yes, that's fine, we can work with that. But my point being that we should mention this in the breaking changes file, because in 3.x, we were used to returning anything and it would work fine.
> 
> It's been almost a month since we have been using 4.x, but only until yesterday I figured out the solution to this problem when you replied. And it caused a lot of frustration when the lib wasn't notifying setState changes

Yes, I agree to mention this change and making two short use cases of `setState()`(mutable & immutable) in the flutter.pub example.

**Comment by GIfatahTH** [comment]
@amoslai5128 
>/*  ---------    For  Question Only        ---------  */
// Case 1: Only notifying when setState returned a double type, otherwise warns the developers
// 👌  Good
final double = RM.Inject<double>((s)=>0.0);
// ⛔  Warn
final double = RM.Inject<double>((s)=> "");
// Case 2: Notifying all the listeners when setState returned a null / dobule type
final nullableDouble = RM.Inject<double?>((s)=> null);

YES, That's what should happen.


@shripal17 
>It's been almost a month since we have been using 4.x, but only until yesterday I figured out the solution to this problem when you replied. And it caused a lot of frustration when the lib wasn't notifying setState changes

The lib should throw, an assertion error, shouldn't it? Could you give me a case where the lib does not throw and does not notify changes?

**Comment by shripal17** [comment]
> The lib should throw, an assertion error, shouldn't it? Could you give me a case where the lib does not throw and does not notify changes?
The lib throws error if something else is returned. But there is completely unexpected behavior even when returning the same type. It doesn't notify. That's the issue which needs to be fixed.

**Comment by amoslai5128** [comment]
> > The lib should throw, an assertion error, shouldn't it? Could you give me a case where the lib does not throw and does not notify changes?
> 
> The lib throws error if something else is returned. But there is completely unexpected behavior even when returning the same type. It doesn't notify. That's the issue which needs to be fixed.

@shripal17 
It has been mentioned on [Wiki doc](https://github.com/GIfatahTH/states_rebuilder/wiki/set_state_api#why--dont-regarding-this-issues).

**Comment by shripal17** [comment]
Thanks all. Closing.
