### ISSUE TITLE
Need some help on how to load and update a specific value with states_rebuilder

### ISSUE THREAD

**Issue by bremington** [GIfatahTH/states_rebuilder#2]
Hi, I think I am close to getting your state management code to work in Flutter, but the few examples you have listed in Medium and the Github site, do not seem to address a simple task.

I have a large database and want to build a widget that loads a single value, then allows me to edit and update my Sqflite db.

Here is an example widget

Container(
                                    padding: EdgeInsets.only(top: 10),
                                    height: 25,
                                    child: StateBuilder(
                                      initState: (state) => financeBloc.loadValueById(state,[0].id),
                                      builder: (State state) =>
                                          SizedBox(
                                            width: 25,
                                            child: Text(
                                              financeBloc.loadValueById(state,[0].id).value.toString()
                                              , style: Theme
                                                .of(context)
                                                .textTheme
                                                .body2,
                                            ),

                                          ),

                                    )),

Here is my model

class Finance {
  int id, value, future, year, flag;
  String icon, name, cat;

  Finance({
    this.id,
    this.year,
    this.name,
    this.cat,
    this.value,
    this.future,
    this.icon,
    this.flag});

  Finance.update({this.id,
    this.year,
    this.name,
    this.cat,
    this.value,
    this.future,
    this.icon,
    this.flag
  });

  Finance.fromMap(Map<String, dynamic> map) {
    id = map[id];
    year = map[year];
    name = map[name];
    cat = map[cat];
    value = map[value];
    future = map[future];
    icon = map[icon];
    flag = map[flag];
  }

  Finance.fromMapValue(Map<String, dynamic> map) {
    future = map[future];
  }

  Map<String, dynamic> toMap() {
    var map = Map<String, dynamic>();
    map['id'] = id;
    map['year'] = year;
    map['name'] = name;
    map['cat'] = cat;
    map['value'] = value;
    map['future'] = future;
    map['icon'] = icon;
    map['flag'] = flag;
    return map;
  }
}

Here is my model

class FinanceDB {
  static final FinanceDB _financeDB = FinanceDB._internal(AppDatabase.get());

  AppDatabase _appDatabase;

  //private internal constructor to make it singleton
  FinanceDB._internal(this._appDatabase);

  static FinanceDB get() {
    return _financeDB;
  }

  updateFinanceValue(int id, int value) async {
    // Get a reference to the database
    var db = await _appDatabase.getDb();
    await db.transaction((Transaction txn) async {
      await txn.rawUpdate(
          "UPDATE Finance SET value = $value WHERE id = $id");
    });
  }

  Future<Finance> getFinanceByID(int id) async {
    var db = await _appDatabase.getDb();
    var res = await db.query("Finance", where: "id = ?", whereArgs: [id]);
    return res.isNotEmpty ? Finance.fromMap(res.first) : null;
  }
}

Here is my repository

import 'package:flutter/widgets.dart';
import 'package:seed/db/finance_db.dart';
import 'package:seed/models/datamodel.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

class FinanceBloc extends StatesRebuilder {

  FinanceDB _financeDB;
  List<Finance> financeList;
  int id;
  Finance item;

  loadFinances(State state) async {
    financeList = await _financeDB.getAll();
    rebuildStates(states : [state]);
  }

  loadValueById(State state, int id) async {
   await  _financeDB.getFinanceByID(id);
   rebuildStates(states : [state]);
  }

  loadValueByName(State state, String name) async {
    await  _financeDB.getByName(name);
    rebuildStates(states : [state]);
  }
  void updateValue(State state, int id, int value) {
    _financeDB.updateFinanceValue(id, value);
    rebuildStates(states : [state]);
  }

}

The error I am getting is NoSuchMethodError: Class 'Future<dynamic>' has no instance getter 'value'

Perhaps someone has an example using states_rebuilder and Sqflite that can help?

**Comment by GIfatahTH** [comment]
Hello
I tried to replicated your code but I didn't understand the following lines:
1-  **initState: (state) => financeBloc.loadValueById(state, [0].id),**. (What do you mean by [0].id)

2- **AppDatabase _appDatabase;** (Which database package you are using).

I am using Sqflite with states_rebuilder to replicate Ankidroid app and it works well.

**Comment by hyperpanthera** [comment]
This is an error with your code and not the library. I am using sqflite as well. Try to trigger a circular progress indicator until your async function (to fetch data) is finished.
