### ISSUE TITLE
[Suggestion] Dispose suscribe to RM 

### ISSUE THREAD

**Issue by pdelgadohurtado** [GIfatahTH/states_rebuilder#202]
Im doing this to update the whole view to react to app global state, but when i move on to another view, the suscribed method is not disposed. Can u provide a stream interface or something to suscribe/unsuscribe to injected variable, or there is something im missing? , it returns a void functionRegards folks !

```
  @override
  void initState() {
    super.initState();
    App app = Provider.of<App>(context, listen: false);
    app.appState.subscribeToRM((snap) {
      if (mounted) {
        setState(() {});
      }
      else {
       // NOT MOUNTED BUT STILL LISTENING
      }
    });
  }
```

**Comment by amoslai5128** [comment]
I'm afraid I don't have a full understanding on your case, would be provide a mini reproduce code? 

Btw, if you're using states_rebuild, that's no need to rely on provider to do the dependency injection, you can simply define a global state that can let you inject anywhere you want, and most likely in StatelessWidget.

The state itself would be disposed automatically and you can also manually dispose on below code:
`model.dispose()`
See [doc](https://github.com/GIfatahTH/states_rebuilder/wiki/rm_injected_api#autoDisposeWhenNotUsed)
