### ISSUE TITLE
Using states_rebuilder for dependency injection[Question]

### ISSUE THREAD

**Issue by nixcode1** [GIfatahTH/states_rebuilder#208]
Hello, I've been using package a lot recently and I'm curious about how to use it as a dependency injector for my services and repositories(non state-related classes).

In GetX, the dependency injection feature is well documented but its not the same with states_rebuilder or maybe I just haven't read up enough.

So please how can the following be done in states_rebuilder:
1. Manually inject a dependency(or multiple dependencies of the same class)
2. Get dependencies of the same class but based on id
3. Keep a dependency alive throughout the app(e.g api or database service)
4. manually close a dependency.

Or if you could just explain how to use states_rebuilder as a dependency injector, that would be awesome. Thank you.

**Comment by GIfatahTH** [comment]
Hi @nixcode1, thank you for the issue.
>1. Manually inject a dependency(or multiple dependencies of the same class)
>2. Get dependencies of the same class but based on id

Dependency injection with states_rebuilder is the simplest one.
Let's suppose we have `MyService` class that we want to inject.
In states_rebuilder:
```dart
final myService = RM.inject(
        () => MyService(),
        autoDisposeWhenNotUsed: true, //Default to true,
        isLazy: true, // Default to true
);
```

This is equivalant in GetX:

```dart
Get.put(
  MyService(),
  permanent: true, //Default to false
);
//and 
Get.lazyPut(
   ()=>  MyService(),
  fenix : true, //Default to false
);
```

For async injection:
In states_rebuilder we use RM.injectFuture or RM.injectStream
```dart
final myService = RM.injectFuture(
        () async => MyService().initialize(),
        autoDisposeWhenNotUsed: true, //Default to true,
        isLazy: true, // Default to true
);
```
In getX:
```dart
Get.putAsync(
   () async => MyService().initialize(),
   permanent  : true, //Default to false
);
```

To consume the injected instance:

In states_rebuilder; just use the global variable myService,
```dart
print(myService.state);
```
In getX you use find method:
```dart
final myService = Get.find<MyService>();
print(myService);
```

Here, you may argue that states_rebuilder (just like riverpod) uses global variable and getX (like get) does not use global variable. NO even getX uses a global container (a singleton Map) and form it you can access any registered instance.

Another point here, with getX you can not register two instances of the same class unless you use a tag to differentiate between them.
```dart
final service1 = Get.put(
  MyService(),
  tag: 'tag1',
);

final service2 = Get.put(
  MyService(),
  tag: 'tag2',
);
```
With states_rebuilder you don't have this problem:

```dart
final service1 =  RM.inject(() => MyService())

final service2 =  RM.inject(() => MyService())
```

>3. Keep a dependency alive throughout the app(e.g api or database service)

set `autoDisposeWhenNotUsed `to false;

>manually close a dependency.

use dispose method.

`myService.dispose();` //Almost no needed


Note that with states_rebuilder:
*  you can inject many async dependent services and states.
* Any injected service or state can be easily mocked in test.
* You can injected instanes based on an abstract class and deal with flavor and environement of developement.


If you have any use case of dependency injection that you want to implement using states_rebuilder, please let me know.

**Comment by nixcode1** [comment]
Thank you so much, this covers all my questions and more.

I do have a follow up question.
What does 'isLazy' do?
It seems my dependency is only injected when i try to access state or listen to it irrespective of the the isLazy value.

**Comment by GIfatahTH** [comment]
If isLazy is true (the default value) the injected object is not instantiated until first used. The opposite is true if isLazy is false.

**Comment by amoslai5128** [comment]
What I like about this library's log tracking in Debug Console, which is very helpful for testing. 

``` Dart
final myService = RM.inject(
        () => MyService(),
        ....
        debugPrintWhenNotifiedPreMessage: "myService: ",  // Observe the life-cycle & actiivty from the state
);
```

**Comment by nixcode1** [comment]
> 
> 
> If isLazy is true (the default value) the injected object is not instantiated until first used. The opposite is true if isLazy is false.
I tested it and this only holds true when I do the injection inside a class(e.g a Widget), but not for a global variable.
For global variables, the service is only injected when I try to access the  inside  a class or it is listened to by an On().

This is not a problem and the library is absolutely brilliant, I'm just curious and trying to understand it better.
