### ISSUE TITLE
Observable & Injector name collision

### ISSUE THREAD

**Issue by MortyMerr** [GIfatahTH/states_rebuilder#22]
Hey! Thank you for your great work. With all respect to you, I have two proposals: 

You use very popular names like `Injector` and `Observable` in a global scope without any prefix. That causes conflicts with other frameworks (rx_dart for instance). Of course that can be handled with explicit prefix after import, but... What do you think about renaming or adding prefixes for these classes? I would gladly open PR, if you are ok with that.

Your library also provides built-in DI. This works badly for users with more complex DI solutions from another packages. What do you think about removing it from repo/moving to separate package? Single responsibility seems to be a good pattern - framework should provide only one feature.

With all respect :)
What do you think?

**Comment by GIfatahTH** [comment]
Thank you for taking the time looking through the code and for your remarks and suggestions.  To tell you the truth, I was thinking about the same thing before considering adding DI to the library and naming it `Injector`. The same thing about `Observable` taken from the Observable pattern.

In my opinion, It is hard to talk about a good state management solution without using a good DI. for this I add a build-in DI to collaborate with `StatesRebuilder` to get out the most of it.  The most popular DI in flutter community are get_it and Provider and I think they can be used with this package without any problem.

**Comment by GIfatahTH** [comment]
For the naming convention, I search in google and dartpub and verified that the injector name is free withing the flutter community. For Observable, I checked the flutter framework and see that they use the term Listenable instead, which encourage me to use it.

Thank you for your comment and for your respect :)

**Comment by MortyMerr** [comment]
But what about conflict with rx_dart? 
Why not use well known scalable DI solution as a dependency of this repo instead of implementing simplified version? 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GIfatahTH** [comment]
I didn't work with rx_dart a lot before and I think it is more suitable to use BloC pattern with rx_dart. But I think you are right Observable term is widely used and can make some conflict. I think I'll name it StatesRebuilderObservable or  ServiceObservable or  What's your opinion?

For DI I will stick with it because although it is simple, it has many good features that I think are very useful at least in my opinion. And you have the option to use can use any DI solution you like with this package without any problem.

**Comment by MortyMerr** [comment]
Yes, this renaming looks good to me, thanks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GIfatahTH** [comment]
I updated the code to use  `ObservableService` and `hasState` instead of `Observable` and `hasObserver`.  

Thank you for you contribution

**Comment by MortyMerr** [comment]
Thanks) this issue should be closed 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
