### ISSUE TITLE
How to declare unsignedUser if  you cant extend the user class?

### ISSUE THREAD

**Issue by Prn-Ice** [GIfatahTH/states_rebuilder#220]
Hi, I'm trying to use `injectedAuth` and I've hit a bit of a snag. 
My model classes are generated using [freezed](https://pub.dev/packages/freezed) and I cant extend them.
How do I declare the `unsignedUser` ?

**Comment by amoslai5128** [comment]
> Hi, I'm trying to use `injectedAuth` and I've hit a bit of a snag.
> My model classes are generated using [freezed](https://pub.dev/packages/freezed) and I cant extend them.
> How do I declare the `unsignedUser` ?

If you're using null safety, there is no need to define the `unsignedUser`, since null means un-signed. Otherwise, with the legacy version, I think you should check out [this](https://github.com/rrousselGit/freezed/issues/296).

**Comment by Prn-Ice** [comment]
Thanks.
