### ISSUE TITLE
[Question] How to read from persisted state?

### ISSUE THREAD

**Issue by Prn-Ice** [GIfatahTH/states_rebuilder#225]
Hi, I created an `injectedCRUD` and had the state persist. 

I noticed that whenever I call `.read` or `.state` its was always empty, so I added print statements in the `fromJson` and those never get printed.

How can I check that the state has been persisted?

**Comment by Prn-Ice** [comment]
Found out the reason why it was always empty on read, I had `readOnInitialization` set to true.

**Comment by Prn-Ice** [comment]
No, state still isnt persisted, its empty every time I hot restart its empty again and no calls to `fromJson` are logged.

**Comment by amoslai5128** [comment]
> No, state still isnt persisted, its empty every time I hot restart its empty again and no calls to `fromJson` are logged.

Can you provide a minimal reproduction sample?

**Comment by Prn-Ice** [comment]
Injected Repository looks like this:
```dart
final p2pOrdersRepositoryRM = RM.injectCRUD<Order?, String>(
    () => P2pOrdersRepository(),
    middleSnapState: (middleSnap) {
      middleSnap.print();
    },
    persist: () => PersistState<List<Order?>>(
      key: '_orders_',
      toJson: (s) {
        logging.Logger('P2pOrdersRepository')
            .shout(json.encode(s.map((e) => e?.toJson()).toList()));

        return json.encode(s.map((e) => e?.toJson()).toList());
      },
      fromJson: (json) {
        logging.Logger('P2pOrdersRepository').severe('read: $json');
        var data = json.decode();
        return data.entries.map((e) => Order.fromJson(e.value)).toList();
      },
    ),
  );
```

Call to read looks like:
```dart
 @override
  Future<List<Order?>> read(String? param) async {
    final result = await _p2pClient.orders();

    return result.data as List<Order?>;
  }
```

`result.data` return a `List<Order>?` and that's why I cast.

Use in widget:
```dart
 OnCRUDBuilder(
                listenTo: p2pOrdersRepositoryRM,
                onError: (error, reload) => Text(error.toString()),
                onWaiting: () => Column(
                  children: [
                    Text(
                        'hasData: ${p2pOrdersRepositoryRM.hasData}'),
                    Text(
                        'data: ${p2pOrdersRepositoryRM.state}'),
                    const Center(child: CircularProgressIndicator()),
                  ],
                ),
                onResult: (data) => Column(
                  children: [
                    Text((data == null).toString()),
                    Text(p2pOrdersRepositoryRM.state
                        .toString()),
                  ],
                ),
              ),
```

**Comment by amoslai5128** [comment]
> Injected Repository looks like this:
> 
> ```dart
> final p2pOrdersRepositoryRM = RM.injectCRUD<Order?, String>(
>     () => P2pOrdersRepository(),
>     middleSnapState: (middleSnap) {
>       middleSnap.print();
>     },
>     persist: () => PersistState<List<Order?>>(
>       key: '_orders_',
>       toJson: (s) {
>         logging.Logger('P2pOrdersRepository')
>             .shout(json.encode(s.map((e) => e?.toJson()).toList()));
> 
>         return json.encode(s.map((e) => e?.toJson()).toList());
>       },
>       fromJson: (json) {
>         logging.Logger('P2pOrdersRepository').severe('read: $json');
>         var data = json.decode();
>         return data.entries.map((e) => Order.fromJson(e.value)).toList();
>       },
>     ),
>   );
> ```
> 
> Call to read looks like:
> 
> ```dart
>  @override
>   Future<List<Order?>> read(String? param) async {
>     final result = await _p2pClient.orders();
> 
>     return result.data as List<Order?>;
>   }
> ```
> 
> `result.data` return a `List<Order>?` and that's why I cast.
> 
> Use in widget:
> 
> ```dart
>  OnCRUDBuilder(
>                 listenTo: p2pOrdersRepositoryRM,
>                 onError: (error, reload) => Text(error.toString()),
>                 onWaiting: () => Column(
>                   children: [
>                     Text(
>                         'hasData: ${p2pOrdersRepositoryRM.hasData}'),
>                     Text(
>                         'data: ${p2pOrdersRepositoryRM.state}'),
>                     const Center(child: CircularProgressIndicator()),
>                   ],
>                 ),
>                 onResult: (data) => Column(
>                   children: [
>                     Text((data == null).toString()),
>                     Text(p2pOrdersRepositoryRM.state
>                         .toString()),
>                   ],
>                 ),
>               ),
> ```

Did you initialize your local storage provider in the root of the widget tree? 
```Dart 
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
     RM.storageInitializer(SharedPreferencesStore());  // Should add this line.
     return HomePage();
  }
}
```

BTW, I've tested for your case, and I'm posting on my git, wait for a sec...

**Comment by Prn-Ice** [comment]
@amoslai5128 I did initialize a local storage provider, in my case hive.
I have also tried `readOnInitialization: true`.

I have a separate `injected` in my code that persists just fine, right now its just the CRUD injected that doesnt seem to work and no error is returned.

Im currently looking through your repo.

**Comment by Prn-Ice** [comment]
To clarify, the issue for me isn't that the repository doesn't work.

The issue is that
- after the data is fetched
- app is restarted
- and the request to read is made again
I expect that the old data is fetched first while the request is made and then updated later.

**Comment by amoslai5128** [comment]
> To clarify, the issue for me isn't that the repository doesn't work.
> 
> The issue is that
> 
> * after the data is fetched
> * app is restarted
> * and the request to read is made again
>   I expect that the old data is fetched first while the request is made and then updated later.

Now I know your question, I took into the source code, and the `shouldRecreateTheState:` offers a similar function but currently only working for `InjectedStream`. 

@GIfatahTH  Should there be any API for getting the persisted state back?

**Comment by GIfatahTH** [comment]
Thanks @ Prn-Ice for the issue, which highlights an edge case that I'm not aware of.

Many thanks to @ amoslai5128 for helping me manage the repository by responding to the issues. 
Your example helps me understand and therefore solve the problem. I use it in this answer.

### First case:  No order is cached in the local storage.
The app starts by showing a `CircularProgressIndicator `and after getting orders from the server it displays them in the `ListTiles`:

Here is a test that validates this case:
````dart
  testWidgets(
    'WHEN there is no orders are cached'
    'AND WHEN the app starts'
    'THEN it fetches for order from the repo',
    (tester) async {
      store.store = {}; //Store is empty
      await tester.pumpWidget(const MyApp());
      expect(find.byType(CircularProgressIndicator), findsOneWidget);
      await tester.pumpAndSettle();
      expect(find.byType(ListTile), findsNWidgets(5));
    },
  );
````

### second case:  There is one order  cached in the local storage. (THIS IS THE BUG)
The app starts by showing the cached order, without fetching the repos.
If you refresh the order than the app displays a `CircularProgressIndicator `and after getting orders from the server it displays them in the `ListTiles`:

Here is a test that validates this case:
````dart
  testWidgets(
    'WHEN there is one order cached'
    'AND WHEN the app starts'
    'THEN it get the cached order'
    'AND WHEN the order is refreshed'
    'THEN it fetches for order from the repo',
    (tester) async {
      store.store = {
        '__Order__': jsonEncode(
          [Order(id: 'id-cached', orderName: 'Order No.#cached').toJson()],
        )
      };

      await tester.pumpWidget(const MyApp());
      await tester.pump(); //The first frame
      expect(find.byType(ListTile), findsOneWidget);
      expect(testOrderCRUD.hasData, true);
      expect(testOrderCRUD.state.length, 1);
      //
      testOrderCRUD.refresh();
      await tester.pump();
      expect(find.byType(CircularProgressIndicator), findsOneWidget);
      expect(testOrderCRUD.isWaiting, true);
      //
      await tester.pumpAndSettle();
      expect(find.byType(ListTile), findsNWidgets(5));
      expect(testOrderCRUD.hasData, true);
      expect(testOrderCRUD.state.length, 5);
    },
  );
````


### second case:  There is one order  cached in the local storage. 
If the parameter shouldRecreateTheState  is set to true than: 
* The app starts by showing the cached order,
* In the background the app fetches for orders and when get them it updates the UI to display them. 
Here is a test that validates this case:
````dart
 testWidgets(
    'WHEN there is one order cached'
    'AND WHEN shouldRecreateTheState == true'
    'AND WHEN the app starts'
    'THEN it get the cached order'
    'AND WHEN the order is refreshed'
    'THEN it fetches for order from the repo',
    (tester) async {
      store.store = {
        '__Order__': jsonEncode(
          [Order(id: 'id-cached', orderName: 'Order No.#cached').toJson()],
        )
      };
      await tester.pumpWidget(const MyApp());
      await tester.pump();
      expect(find.byType(ListTile), findsOneWidget);
      expect(testOrderCRUD.hasData, true);
      expect(testOrderCRUD.state.length, 1);
      //It is waiting for fetch under the hood
      expect(testOrderCRUD.isOnCRUD, true);
      //
      await tester.pump(const Duration(seconds: 1));
      expect(find.byType(ListTile), findsOneWidget);
      expect(testOrderCRUD.hasData, true);
      expect(testOrderCRUD.state.length, 1);
      //
      await tester.pump(const Duration(seconds: 1));
      expect(find.byType(ListTile), findsNWidgets(5));
      expect(testOrderCRUD.hasData, true);
      expect(testOrderCRUD.state.length, 5);
    },
````


Case two is the bug and it is fixed.

For case three to work, you shouldn't use `OnCRUDBuilder`, just use `OnReactive `like this: 

```dart
 Padding(
                  padding: const EdgeInsets.all(15.0),
                  child: OnReactive(
                    () {
                      if (testOrderCRUD.isWaiting) {
                        return const Center(child: CircularProgressIndicator());
                      }
                      return Column(
                        children: testOrderCRUD.state
                            .map((order) => ListTile(
                                title: Text(order?.id ?? 'NO ID'),
                                subtitle: Text(order?.orderName ?? 'NO NAME')))
                            .toList(),
                      );
                    },
             )),
```

 `OnCRUDBuilder` is used to indicate that a crud operation is fired and gives you the possibility to handle its result.
