### ISSUE TITLE
[New widget] `TopStatelessWidget` on top of `MaterialApp` Widget for plugins initialization, app  internationalization and theme managmeent

### ISSUE THREAD

**Issue by GIfatahTH** [GIfatahTH/states_rebuilder#232]
In previous releases we have `TopAppWidget` useful for:
- Initialize plugins; display splashScreen while initialization, and error screen in case of failure.
- Subscribe to `InjectedI18N` and `InjectedTheme` to internationalize the app and manage its theming.
- Invoke side effects when app life cycle changes.

 `TopAppWidget` may look cumbersome and `InjectedI18N` and `InjectedTheme` must be explicitly specified.

`TopStatelessWidget` is a rewrite of `TopAppWidget` to make it less boilerplate.

In all cases just use `TopStatelessWidget` instead of `StatelessWidget` on top of `MaterialApp` widget.

### Plugins initialization
In Flutter it is common to initialize plugins inside the main method:
```dart
void main()async{
 WidgetsFlutterBinding.ensureInitialized();
 await initializeFirstPlugin();
 await initializeSecondPlugin();
 runApp(MyApp());
}
```
If you want to initialize plugins and display splash screen while waiting for them to initialize and display an error screen if any of them fails to initialize or request for permission with the ability to retry the initialization you can use `TopStatelessWidget`:
```dart
class MyApp extends TopStatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  List<Future<void>>? ensureInitialization() {
    return [
      initializeFirstPlugin(),
      initializeSecondPlugin(),
    ];
  }
  @override
  Widget? splashScreen() {
    return Material(
      child: Scaffold(
        body: Center(
          child: CircularProgressIndicator(),
        ),
      ),
    );
  }
  @override
  Widget? errorScreen(error, void Function() refresh) {
    return ElevatedButton.icon(
      onPressed: () => refresh(),
      icon: Icon(Icons.refresh),
      label: Text('Retry again'),
    );
  }
  @override
  Widget build(BuildContext context) {
    return MyHomePage();
  }
}
```

### App internationalization and theme swishing

```dart
 void main() {
   runApp(MyApp());
 }
 final themeRM = RM.injectTheme(
   ...
 );

 final i18nRM = RM.injectedI18N(
   ...
 );

 class MyApp extends TopStatelessWidget {
   // This widget is the root of your application.
   @override
   Widget build(BuildContext context) {
     return MaterialApp(
       //
       theme: themeRM.lightTheme, //light theme
       darkTheme: themeRM.darkTheme, //dark theme
       themeMode: themeRM.themeMode, //theme mode
       //
       locale: i18nRM.locale,
       localeResolutionCallback: i18nRM.localeResolutionCallback,
       localizationsDelegates: [
         GlobalMaterialLocalizations.delegate,
         GlobalWidgetsLocalizations.delegate,
         GlobalCupertinoLocalizations.delegate,
       ],
       home: HomePage(),
     );
   }
 }
```

### App lifecycle

To invoke side effects depending on the app life cycle, use `didChangeAppLifecycleState` hook
```dart
class MyApp extends TopStatelessWidget {
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    print(state);
  }
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

**Comment by karnadii** [comment]
I have the same problem trying to implementing persistState using hive

**Comment by GIfatahTH** [comment]
Hi @karnadii Thank you for the issue.
Please try to make the return type of read object nullable like this:
 ```dart
@override
  Object? read(String key) {
    return box.get(key);
  }
```

**Comment by amoslai5128** [comment]
> > Hi @karnadii Thank you for the issue. Please try to make the return type of read object nullable like this:
> > ```dart
> > @override
> >  Object? read(String key) {
> >    return box.get(key);
> >  }
> > ```
> 
> it works. thanks!

The Wiki Doc example has been updated.

**Comment by indigo-dev** [comment]
@GIfatahTH  Covering app (state) initialization with splashScreen & errorScreen is so convenient, it should be part of flutter sdk imho as everybody needs it. Pretty good feature!

But actually there's a problem worth noting: when using navigator 2.0 (router-based) there is problem related to having more than one MaterialApp. And as the splashScreen and errorScreen are above the app itself, they need be nested within an MaterialApp/CupertinoApp themselves.

Hint: in the docs of TopStatelessWidget this should be reflected. Currently the docs have a typo I think by telling Material(child: ...) instead of MaterialApp(home:....) for the SplashScreen. see https://github.com/GIfatahTH/states_rebuilder/wiki/widget_listener_api

Error message is:
_effectiveRouteInformationProvider != null

Solution to this problem is:
Each MaterialApp has to be assigned a unique key. This seems to resolve a conflict for the router part...

Corresponding code setup is:
```dart
class MyApp extends TopStatelessWidget {
  @override
  List<Future<void>>? ensureInitialization() {
    return [
      // appLaunchStoreInjected.state.getData("current"),
      Future.delayed(Duration(seconds: 5)),
    ];
  }

  @override
  Widget? errorScreen(error, void Function() refresh) {
    // return ErrorScreen.unavailable();
    return MaterialApp(
        key: Key("MaterialAppErrorScreen"),
        home: Scaffold(body: Center(child: Icon(Icons.error))));
  }

  @override
  Widget? splashScreen() {
    // return Material(child: SplashScreen(enableIndicator: true));
    return MaterialApp(
        key: Key("MaterialAppSplashScreen"),
        home: Scaffold(body: Center(child: CircularProgressIndicator())));
  }

  @override
  Widget build(BuildContext context) {
    final _appRouter = appRouterInjected.state;

    return MaterialApp.router(
      key: Key("MaterialAppBuild"),
      routeInformationParser: _appRouter.defaultRouteParser(),
      routerDelegate: AutoRouterDelegate(_appRouter),
      title: 'GP Companion',
      theme: themeInjected.lightTheme.copyWith(
        colorScheme: myLightTheme.colorScheme.copyWith(
          secondary: kThemeColorSecondary,
        ),
      ),
      darkTheme: themeInjected.darkTheme, //TODO darkTheme definition
      themeMode: themeInjected.themeMode,
      debugShowCheckedModeBanner: false,
    );
  }
}
```

**Comment by GIfatahTH** [comment]
@indigo-dev another good catch.

In the next release, I managed to add `MaterialApp` widget with a unique key on top of `splashScreen` and `errrorScreen` so that the use is no longer forced to use `MaterialApp`.   Nevertheless, the use can use `MaterialApp` without a key for more customization.

**Comment by GIfatahTH** [comment]
@indigo-dev

Are you sure that this strange behavior is related to states_rebuilder?

Have you tried it without using InjectedTheme?

**Comment by indigo-dev** [comment]
After I replaced the injected theme references with direct references to myLightTheme it worked suddenly.
Besides the fact I don't like the syntax of Flutter's secondary theme color this behaviour seems to be somehow related to injected theme but only on physical iOS device.

**Comment by indigo-dev** [comment]
Update: as of now it looks like the root cause of that behaviour is not iOS physical or not. After finishing dark mode for my app, it's now getting clear that the problem is having its origin in the ThemeInjector. 
1. So what actually works perfectly: using themeMode.toggle() to switch between lightMode and darkMode. 
2. What also works: setting the themeMode to ThemeMode.system and changing system theme to dark mode. The app theme goes instantly with this change.
3. **What actually causes problems**: setting the themeMode to ThemeMode.system and changing the system theme to light mode. This brings some trouble with it.
The result is somewhat half dark and half light mode, see screenshot the most right picture. I was able to reproduce that behaviour on iOS simulator+device + android emulator.
I hope my code is alright but I followed the docs as far as possible. @GIfatahTH 

``` dart
// My Theme Injector
final InjectedTheme<String> themeInjected = RM.injectTheme(
  themeMode: ThemeMode.system,
  lightThemes: {
    "myTheme": myLightTheme.copyWith(
      colorScheme: myLightTheme.colorScheme.copyWith(
        secondary: kThemeColorSecondary,
      ),
    )
  },
  darkThemes: {
    "myTheme": myDarkTheme.copyWith(
      colorScheme: myDarkTheme.colorScheme.copyWith(
        secondary: kThemeColorSecondary,
      ),
    )
  },
  persistKey: '__theme__',
  debugPrintWhenNotifiedPreMessage: "ThemeInjector",
);

// How I implement the UI to switch to system-mode
themeInjected.themeMode = ThemeMode.system;

```

![Screenshot 2022-02-08 160717](https://user-images.githubusercontent.com/11189868/153017852-69ecb20b-d36a-4f5e-82d9-5d8cee9c6787.jpg)

**Comment by GIfatahTH** [comment]
@indigo-dev 
I tried with this simple example. Does it reproduce your case?

```dart
import 'package:flutter/material.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

final myLightTheme = ThemeData.light();
final myDarkTheme = ThemeData.dark();
final kThemeColorSecondary = Colors.blueGrey;

final InjectedTheme<String> themeInjected = RM.injectTheme(
  themeMode: ThemeMode.system,
  lightThemes: {
    "myTheme": myLightTheme,
  },
  darkThemes: {
    "myTheme": myDarkTheme,
  },
  // persistKey: '__theme__',
  debugPrintWhenNotifiedPreMessage: "ThemeInjector",
);

void main() {
  runApp(_App());
}

class _App extends TopStatelessWidget {
  const _App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: themeInjected.lightTheme.copyWith(
        colorScheme: themeInjected.lightTheme.colorScheme.copyWith(
          secondary: kThemeColorSecondary,
        ),
      ),
      darkTheme: themeInjected.darkTheme,
      themeMode: themeInjected.themeMode,
      home: _Home(),
    );
  }
}

class _Home extends ReactiveStatelessWidget {
  const _Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
          Expanded(
            child: Container(
              color: Theme.of(context).colorScheme.primary,
              child: Center(
                child: Text(
                  'Text 1',
                  style: TextStyle(
                    color: Theme.of(context).colorScheme.onPrimary,
                  ),
                ),
              ),
            ),
          ),
          Expanded(
            child: Container(
              color: Theme.of(context).colorScheme.secondary,
              child: Center(
                child: Text(
                  'Text 2',
                  style: TextStyle(
                    color: Theme.of(context).colorScheme.onSecondary,
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
      floatingActionButton: Row(
        children: [
          const SizedBox(width: 30),
          FloatingActionButton(
            onPressed: () {
              themeInjected.themeMode = ThemeMode.system;
            },
          ),
          const SizedBox(width: 20),
          FloatingActionButton(
            onPressed: () {
              themeInjected.toggle();
            },
          )
        ],
      ),
    );
  }
}
```

**Comment by indigo-dev** [comment]
Thank you very much for your minimum example, it worked (of course it did) and made me wonder what my code is doing.
And oh my goodness. You know what is Not a good practice? Checking current ThemeMode by stating
if (themeInjected.themeMode == ThemeMode.light) else ...

I moved over to check .isDarkTheme instead and all of a sudden it works.
Ouch ^^

**Comment by GIfatahTH** [comment]
@indigo-dev 
>I moved over to check .isDarkTheme instead and all of a sudden it works.
So your issue is solved!
