### ISSUE TITLE
[Question] On ReadMe, Those explanations are still available ? 

### ISSUE THREAD

**Issue by JogoGakha** [GIfatahTH/states_rebuilder#244]
Both cases below are currently available ?
In codes, (1),(2), builder" should widget according to Library.
is it correct to end up without "return " syntax in (1),(2) ?

[https://github.com/GIfatahTH/states_rebuilder/tree/master/states_rebuilder_package#global-and-local-state](url)
```
// The state will be initialized in the widget tree.
final myState = RM.inject(() => throw UnimplementedError())
// In the widget tree
myState.inherited(
  stateOverride: () {
    return MyState(parm1,param2);
  },
  builder: (context) {
    // Read the state through the context
    final _myState = myState.of(context); //--> (1)
  }
)

/////////////////////////////////////////////////
final myBloc = RM.inject<MyBloc>(() => throw UnimplementedError())
//In the widget tree
myState.inherited(
  stateOverride: () {
    return MyBloc(parm1, param2);
  },
  builder: (context) {
    final _myBloc = myBloc.of(context);  // <--------- (2)
  }
)

```
 
plus, this sentence below is on same page.
" In states_rebuilder, we build on the concept of InheritedWidget *to get what we call widget aware injected state.* "

in that sentence, would you explain that part between *  in easy way ?
(I understand why you mentioned InheritedWidget concept.)

**Comment by GIfatahTH** [comment]
>is it correct to end up without "return " syntax in (1),(2) ?

It is obvious that the builder method returns a Widget. The snippet of code in read me assumes that the reader knows that.


>in that sentence, would you explain that part between * in easy way ?

The method ` myState.of(context) `search in the widget tree using the provided context for an `InheretedWidget` that holds the state and register the `BuildContext` for rebuild when the state changes.

**Comment by JogoGakha** [comment]
Thanks.
