### ISSUE TITLE
[Question] this solution beyond Provider's limitation ?

### ISSUE THREAD

**Issue by JogoGakha** [GIfatahTH/states_rebuilder#245]
This codes below are based on [https://github.com/GIfatahTH/states_rebuilder/wiki/state_widget_wise_api](url).
counter1, counter2, counter3 were defined "globally."
So, As this package's basic concept, (2) approach is common useage.

I wonder why (1) approach- nested injection-  is needed.
I guess my understanding is not enough.
explain this. pls.

```
final counter1 = RM.inject<int>(() => 10);
final counter2 = RM.inject<int>(() => 20);

final counter3 = RM.injectFuture<int?>(() => Future.delayed(Duration(seconds: 5), () => 30)); 

void main()=> runApp(MaterialApp(
  debugShowCheckedModeBanner: false,
  home: Scaffold(
    appBar: AppBar(
      title: Text(" "),
    ),
    body: _App(),
  ) ,
));

class _App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    //Nested injection
    return counter1.inherited(
      builder: (context) => counter2.inherited(
        builder: (context) => counter3.inherited(
          builder: (context) => _MyHomePage(),
        ),
      ),
    );
    //OR  Simply
    return [counter1, counter2, counter3].inherited(
      builder: (context) => _MyHomePage(),
    );
  }
}

class _MyHomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Directionality(
        textDirection: TextDirection.ltr,
        child: Column(
          children: [
            Text('counter1: ${counter1.of(context)}'),   <-----------------------------------(1)
            Text('counter2: ${counter2.of(context)}'),
            if (counter3.of(context) != null)
              Text('counter3: ${counter3.of(context)}')
            else
              CircularProgressIndicator(),

            SizedBox( height: 100, ),

            Text('counter1.state: ${counter1.state}'),      <--------------------------------------(2)
            Text('counter2.state: ${counter2.state}'),
            if (counter3.state != null)
              Text('counter3.state: ${counter3.state}')
            else
              CircularProgressIndicator(),
          ],
        ));
  }
}

```

**Comment by amoslai5128** [comment]
> I wonder why (1) approach- nested injection- is needed.

Correct me if I didn't answer your question.

The **state_widget_wise** is commonly used in a `ListView.builder` that can let you allocate the state into each list item that can rebuild independently, instead of rebuilding the whole list.



```
  @override
  Widget build(BuildContext context) {
    // (1) - Nested injection
    return counter1.inherited(
      builder: (context) => counter2.inherited(
        builder: (context) => counter3.inherited(
          builder: (context) => _MyHomePage(),
        ),
      ),
    );
    // (2) - OR  Simply
    return [counter1, counter2, counter3].inherited(
      builder: (context) => _MyHomePage(),
    );
  }

```

Two state_widget_wise approaches actually are the same, (2) is for a syntax shortcut only. Therefore, the widget that has inherited the state (_MyHomePage for your case), [can use](https://github.com/GIfatahTH/states_rebuilder/wiki/state_widget_wise_api): 

```Dart
class _MyHomePage .... {

  @override
  Widget build(BuildContext context) {
    // Calling the of method on the global itemData will get the right state using InheritedWidget
    // The Element owner of the BuildContext will not listen to the injected model
    final Injected<ItemData> itemState = itemData.of(context);

    // When the itemState emits a notification, the Element will rebuild
    final ItemData itemState = itemData.call(context);
    // Shortcut for the .call
    final ItemData itemState = itemData(context);
```

Then, regarding your question of `Text('counter1.state: ${counter1.state}'),      <--------------------------------------(2)`
The state should be listenable when you wrap an `OnBuilder` or `OnReactive` on top of the `Text`, and the key difference between the **state_widget_wise** is the state will be rebuilding the same update to all the `OnReactive or other builders` whatever at any level of the widget tree.

**Comment by JogoGakha** [comment]
> > I wonder why (1) approach- nested injection- is needed.
> 
> Correct me if I didn't answer your question.
> 
> The **state_widget_wise** is commonly used in a `ListView.builder` that can let you allocate the state into each list item that can rebuild independently, instead of rebuilding the whole list.
> 
> ```dart
>   @override
>   Widget build(BuildContext context) {
>     // (1) - Nested injection
>     return counter1.inherited(
>       builder: (context) => counter2.inherited(
>         builder: (context) => counter3.inherited(
>           builder: (context) => _MyHomePage(),
>         ),
>       ),
>     );
>     // (2) - OR  Simply
>     return [counter1, counter2, counter3].inherited(
>       builder: (context) => _MyHomePage(),
>     );
>   }
> ```
> 
> Two state_widget_wise approaches actually are the same, (2) is for a syntax shortcut only. Therefore, the widget that has inherited the state (_MyHomePage for your case), can use:
> 
> ```dart
> class _MyHomePage .... {
> 
>   @override
>   Widget build(BuildContext context) {
>     // Calling the of method on the global itemData will get the right state using InheritedWidget
>     // The Element owner of the BuildContext will not listen to the injected model
>     final Injected<ItemData> itemState = itemData.of(context);
> 
>     // When the itemState emits a notification, the Element will rebuild
>     final ItemData itemState = itemData.call(context);
>     // Shortcut for the .call
>     final ItemData itemState = itemData(context);
> ```
> 
> **However**, using a widget listener (like `OnReactive`) gets more productive for your case.
> 
> Then, regarding your question of
> 
> ```dart
> Text('counter1.state: ${counter1.state}'),      <--------------------------------------(2)
> ```
> 
> The state should be listenable when you wrap an `OnBuilder` or `OnReactive` on top of the `Text`, and the key difference between the **state_widget_wise** is the state will be rebuilding the same update to all the `OnReactive or other builders` whatever at any level of the widget tree.
> 
> [About state_widget_wise](https://github.com/GIfatahTH/states_rebuilder/wiki/state_widget_wise_api) [About state listener](https://github.com/GIfatahTH/states_rebuilder/wiki/widget_listener_api#onbuilder)

First ,thank for your favor.

" When not using - inherited- method , we should use -OnReactive- for rebuilding widget listening the state,
 but, if we use -inherited-, it allows the widget to be rebuilt without sorts of -widget listeners - like OnReactive. "

That is enough to understands that feature's intention ?
Or Teach me my shortage .

Thanks again.

**Comment by amoslai5128** [comment]
> > > I wonder why (1) approach- nested injection- is needed.
> > 
> > 
> > Correct me if I didn't answer your question.
> > The **state_widget_wise** is commonly used in a `ListView.builder` that can let you allocate the state into each list item that can rebuild independently, instead of rebuilding the whole list.
> > ```dart
> >   @override
> >   Widget build(BuildContext context) {
> >     // (1) - Nested injection
> >     return counter1.inherited(
> >       builder: (context) => counter2.inherited(
> >         builder: (context) => counter3.inherited(
> >           builder: (context) => _MyHomePage(),
> >         ),
> >       ),
> >     );
> >     // (2) - OR  Simply
> >     return [counter1, counter2, counter3].inherited(
> >       builder: (context) => _MyHomePage(),
> >     );
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Two state_widget_wise approaches actually are the same, (2) is for a syntax shortcut only. Therefore, the widget that has inherited the state (_MyHomePage for your case), can use:
> > ```dart
> > class _MyHomePage .... {
> > 
> >   @override
> >   Widget build(BuildContext context) {
> >     // Calling the of method on the global itemData will get the right state using InheritedWidget
> >     // The Element owner of the BuildContext will not listen to the injected model
> >     final Injected<ItemData> itemState = itemData.of(context);
> > 
> >     // When the itemState emits a notification, the Element will rebuild
> >     final ItemData itemState = itemData.call(context);
> >     // Shortcut for the .call
> >     final ItemData itemState = itemData(context);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **However**, using a widget listener (like `OnReactive`) gets more productive for your case.
> > Then, regarding your question of
> > ```dart
> > Text('counter1.state: ${counter1.state}'),      <--------------------------------------(2)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The state should be listenable when you wrap an `OnBuilder` or `OnReactive` on top of the `Text`, and the key difference between the **state_widget_wise** is the state will be rebuilding the same update to all the `OnReactive or other builders` whatever at any level of the widget tree.
> > [About state_widget_wise](https://github.com/GIfatahTH/states_rebuilder/wiki/state_widget_wise_api) [About state listener](https://github.com/GIfatahTH/states_rebuilder/wiki/widget_listener_api#onbuilder)
> 
> First ,thank for your favor.
> 
> I understood why inherited" is needed in ListView. I guess inherited feature's core in ListView is "statesOverride" property and scope. It allows each "injected state" to be assigned to each item in ListView. And plus, " When not using - inherited- method , we should use -OnReactive- for rebuilding widget listening the state, but, if we use -inherited-, it allows the widget to be rebuilt without sorts of -widget listeners - like OnReactive in any level of tree ".
> 
> That above is enough to understands that feature's intention ? Or Teach me my shortage .
> 
> But, still can not understand why inherited" is needed in counter1, counter2, counter3 examples .
> 
> Thanks again.

@GIfatahTH

**Comment by GIfatahTH** [comment]
@amoslai5128 @JogoGakha 

I didn't understand well the question. 

In approach 1 (as in here):
```dart
 Text('counter1: ${counter1.of(context)}'),   <-----------------------------------(1)
            Text('counter2: ${counter2.of(context)}'),
            if (counter3.of(context) != null)
              Text('counter3: ${counter3.of(context)}')
            else
              CircularProgressIndicator(),
```
We are getting the scoped value of counters, which may be different from the global counter values.


In approach 2 (as in here):
```dart
Text('counter1.state: ${counter1.state}'),      <--------------------------------------(2)
            Text('counter2.state: ${counter2.state}'),
            if (counter3.state != null)
              Text('counter3.state: ${counter3.state}')
            else
              CircularProgressIndicator(),
```

We are getting the global counter values.

@JogoGakha said:
> I guess inherited feature's core in ListView is "statesOverride" property and scope.
> It allows each "injected state" to be assigned to each item in ListView.
> And plus,
> " When not using - inherited- method , we should use -OnReactive- for rebuilding widget listening the state,
> but, if we use -inherited-, it allows the widget to be rebuilt without sorts of -widget listeners - like OnReactive
> in any level of tree ".

In the big picture, your understanding is right.
