### ISSUE TITLE
Parameter Error in one of the examples

### ISSUE THREAD

**Issue by topcheese** [GIfatahTH/states_rebuilder#253]
I was doing great with the examples, and I thank you so much for this amazing framework. I thought I'd point out an error, as I'm not sure where the "name" parameter is coming from, I'm guessing a typo?

https://github.com/GIfatahTH/states_rebuilder/blob/87cf8f06fc43272f89970484231f63387f2fa435/examples/ex001_00_sync_global_and_local_state/lib/ex_014_00_state_interceptor.dart#L163

**Comment by GIfatahTH** [comment]
The name parameter is coming from dart:core package. 
It is added in version 2.15
https://medium.com/dartlang/dart-2-15-7e7a598e508a

**Comment by topcheese** [comment]
The machine I was testing it on had Dart 2.14.4.
