### ISSUE TITLE
Change usage of `futureSnapshot.data == false` to `futureSnap.connectionState` check

### ISSUE THREAD

**Issue by anticafe** [GIfatahTH/states_rebuilder#26]
I notice in the [Medium article](https://medium.com/flutter-community/an-easy-and-effective-state-management-solution-for-flutter-to-achieve-100-separation-of-f3d6988c2cac), you use `futureSnapshot.connectionState == ConnectionState.waiting` instead `futureSnapshot.data == false`. So, can you also update your [counter_app.dart:L30](https://github.com/GIfatahTH/states_rebuilder/blob/master/example/lib/examples/counter_app.dart#L30) example too?

**Comment by GIfatahTH** [comment]
Both works. But for future injected directly in the Injector, it is prefered to used `futureSnapshot.data == false` and for the future that comes from methods in the model, it is preferred to use `model.snapshot.connectionState == ConnectionState.waiting`. And that's what I did.
