### ISSUE TITLE
Observing navigation 

### ISSUE THREAD

**Issue by benny856694** [GIfatahTH/states_rebuilder#263]
How can I observe navigation? 
Do we have this feature? 
I want to get notified when navigation is done, so that I can update the color of status bar of the phone.
@GIfatahTH

**Comment by GIfatahTH** [comment]
There are onNavigate and onNavigateBack hooks, you can use them.

https://github.com/GIfatahTH/states_rebuilder/blob/dev/examples/ex004_00_navigation/lib/ex09_on_navigate_signin.dart

https://github.com/GIfatahTH/states_rebuilder/blob/dev/examples/ex004_00_navigation/lib/ex10_on_global_back_navigation.dart

**Comment by benny856694** [comment]
I am using onNavigate hook so far, but this is called before the navigation, not after. Maybe we should add a "onNavigated" hook?

**Comment by GIfatahTH** [comment]
As a workaround solution and if you want to wait until page transition animation to finish to fire side effects, you can use Future.delayed with the expected duration of animation (default to 300ms).
