### ISSUE TITLE
NavigatorObserver

### ISSUE THREAD

**Issue by tontonanrakyat** [GIfatahTH/states_rebuilder#270]
Is there any way to add **FirebaseAnalyticsObserver** (NavigatorObserver) to **RM.injectNavigator** (InjectedNavigator)?

**Comment by GIfatahTH** [comment]
@tontonanrakyat  sorry for my late response. I will try to add this feature

**Comment by tontonanrakyat** [comment]
Thanks for your response. 
I really love this package, especially for testing feature :) 

I'm a newbie in programming.
Should I wait until the branch "dev" merged to "master" for next releases?

**Comment by GIfatahTH** [comment]
Add in version 6.2.0
