### ISSUE TITLE
Close drawer & bottomSheet programmatically

### ISSUE THREAD

**Issue by tontonanrakyat** [GIfatahTH/states_rebuilder#274]
_RM.scaffold.openDrawer()
RM.scaffold.openEndDrawer()
RM.scaffold.showBottomSheet()_

Please add an example to [ex004_00_navigation](https://github.com/GIfatahTH/states_rebuilder/tree/master/examples/ex004_00_navigation) folder 
how to close/hide/remove **drawer**, **endDrawer**, **bottomSheet** programmatically.

I tried Navigator.back() or Navigator.pop(context), but it's give me back to previous screen instead of close the drawer.

**Comment by topcheese** [comment]
I think I needed this the last time I was working on my app.  Thanks for sharing!

**Comment by GIfatahTH** [comment]
Example add 
https://github.com/GIfatahTH/states_rebuilder/blob/master/examples/ex004_00_navigation/lib/ex19_dialogs.dart

**Comment by tontonanrakyat** [comment]
Thank you so much.
