### ISSUE TITLE
debugPrintWhenNotifiedPreMessage show double log

### ISSUE THREAD

**Issue by tontonanrakyat** [GIfatahTH/states_rebuilder#275]
After upgrade to flutter 3.0.0 debugPrintWhenNotifiedPreMessage always printed twice.
First print with green color, Second print with blue color.

**Comment by tontonanrakyat** [comment]
solved 

I found it on **StatesRebuilerLogger**  at file logger.dart

 if (!isTestMode) {
      // ignore: avoid_print
      print('\x1B[33m$message\x1B[0m');
      print(message);  // => I remove this line :)

      if (s != null) {
        // ignore: avoid_print
        print('\x1B[31m$s\x1B[0m');
      }
    }

**Comment by GIfatahTH** [comment]
@tontonanrakyat  are you using VS Code?

**Comment by tontonanrakyat** [comment]
yes I am.

**Comment by GIfatahTH** [comment]
Fixed in version 6.2.0
