### ISSUE TITLE
autoDisposeWhenNotUsed: false not working

### ISSUE THREAD

**Issue by KKranjcevic** [GIfatahTH/states_rebuilder#278]
In versions 6+ when "autoDisposeWhenNotUsed: false" is set (not using states_rebuilder navigation) (in tabs and BottomNavigationBar) the Inject is always disposed. In previus version (5.2) it works as it should.

**Comment by GIfatahTH** [comment]
@KKranjcevic  Thank you for the issue.

I will try to get out with an example that replicate the issue. mean while if you have one that would help me.

**Comment by GIfatahTH** [comment]
Thanks for the issue and the pull request.
Merged in pull request #273
