### ISSUE TITLE
You have to register at least one observer using the `StateBuilder` or StateWithMixinBuilder` widgets. ERROR

### ISSUE THREAD

**Issue by xEyad** [GIfatahTH/states_rebuilder#28]
hello, from the documentation (and correct me if i'am wrong) 

1. The registered (injected) models are available for access within the Injector itself and any of its child widgets.
2. To get any of the registered model and make it reactive : ....  To register a widget as a listener in a particular reactive model : Use` Injector.getAsModel<T>(context:context)`. The context is optional and when it is provided, the widget is automatically registered in the model
3. To notify listeners of a reactive model : Use `rebuildStates([List tag])` method. This works inside a model that extends `StatesRebuilder`

so in summary if i extended the class `ModelA` with `StateRebuilder` and i get the  model like this `Injector.getAsModel<ModelA>(context: context)` . then the widget using `context` should be added as a listener to `ModelA` automatically.

if i misunderstood the documentation please correct me. otherwise here is the problem and how to reproduce it.
in the current code snippet it i try to update the widget after the model fetches some data. then i get the error in the title

```dart

class ModelA extends StatesRebuilder {
  ModelA() {
    fetchData();
  }
  void fetchData() async {
    print('fetching data');
    await Future.delayed(Duration(seconds: 10));
    n++;
    print('data fetched');
    rebuildStates();
  }

  int n = 0;
}

class Sandbox extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Injector(
        inject: [Inject<ModelA>(() => ModelA())],
        builder: (context, __) {
          var model = Injector.getAsModel<ModelA>(context: context);
          return MaterialApp(
            title: 'State rebuilder test',
            theme: ThemeData(
              primarySwatch: Colors.blue,
            ),
            home: Scaffold(
                appBar: AppBar(
                  title: Text("Sandbox"),
                ),
                body: Center(child: Text('${model.state.n}'))),
          );
        });
  }
}

void main() {
  runApp(Sandbox());
}

```

**Comment by GIfatahTH** [comment]
I update the documentation to make things more clearly especially the difference between explicit and implicit reactivity. 
If you extend `StatesRebuilder` and use `rebuildStates` to notify observers then you are explicitly using reactivity and you should use `Injector.get` the method instead of `Injector.getAsModel`.

Please read the new documentation and I will publish the new update sooner.

If you want to explicitly use reactivity.
Here is your code, I just changed `Injector.getAsModel`. to `Injector.get`
```dart
class ModelA extends StatesRebuilder {
  ModelA() {
    fetchData();
  }
  void fetchData() async {
    print('fetching data');
    await Future.delayed(Duration(seconds: 10));
    n++;
    print('data fetched');
    rebuildStates();
  }

  int n = 0;
}

class Sandbox extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Injector(
      inject: [Inject<ModelA>(() => ModelA())],
      builder: (context) {
        var model = Injector.get<ModelA>(context: context);
        return MaterialApp(
          title: 'State rebuilder test',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: Scaffold(
              appBar: AppBar(
                title: Text("Sandbox"),
              ),
              body: Center(child: Text('${model.n}'))),
        );
      },
    );
  }
}

void main() {
  runApp(Sandbox());
}
```

If you want to make a profit of implicit reactivity use:
NB: in the next release `getAsModel` is deprecated in favor of  `getAsReactive`
```dart
class ModelA extends StatesRebuilder {
  void fetchData() async {
    print('fetching data');
    await Future.delayed(Duration(seconds: 10));
    n++;
    print('data fetched');
  }

  int n = 0;
}

class Sandbox extends StatelessWidget {
   @override
  Widget build(BuildContext context) {
    return Injector(
      inject: [Inject<ModelA>(() => ModelA())],
      initState: (_) {
        Injector.getAsReactive<ModelA>().setState((state) => state.fetchData());
      },
      builder: (context,_) {
        var model = Injector.getAsModel<ModelA>(context: context);
        return MaterialApp(
          title: 'State rebuilder test',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: Scaffold(
              appBar: AppBar(
                title: Text("Sandbox"),
              ),
              body: Center(child: Text('${model.state.n}'))),
        );
      },
    );
  }
}

void main() {
  runApp(Sandbox());
}
```
