### ISSUE TITLE
With Flutter 3.10 and the new updete of navigation_builder 0.0.3 there are and error

### ISSUE THREAD

**Issue by Spiderbezno** [GIfatahTH/states_rebuilder#284]
With new version navigation_builder 0.0.3 solved a problem with Flutter 3.10 now appears an error in this library

Error: The method 'InjectedNavigator.toReplacement' has fewer named arguments than those of overridden method 'NavigationBuilder.toReplacement'.
injected_navigator.dart:194
Future<T?> toReplacement<T extends Object?, TO extends Object?>(
^
: Context: This is the overridden method ('toReplacement').
navigation_builder.dart:353
Future<T?> toReplacement<T extends Object?, TO extends Object?>(

**Comment by sashker** [comment]
Having the same issue with Flutter 3.7.10 and states_rebuilder 6.2.0 (which is a transitive dependency of multiselect 0.1.0)

**Comment by GIfatahTH** [comment]
I am actively working on the issue and it will be resolved soon.

**Comment by GIfatahTH** [comment]
its done. update to the new version 
https://pub.dev/packages/states_rebuilder
