### ISSUE TITLE
State Builder not working with Hot Reload

### ISSUE THREAD

**Issue by lab-nit-s** [GIfatahTH/states_rebuilder#3]
Hello, first of all this is a great package. Thanks a lot.

Secondly, I am having an issue when I am changing something and doing hot reload.
Does the function `rebuildStates(ids:_)` stop working when I do hot reload ??

**Comment by GIfatahTH** [comment]
No `rebuildStates(ids:_)` works well with hot reload. .I think the problem is with the way you provided your logic class (BLoC).
Make sure not to instantiate your Logic class inside the `build` function.
Would you link me to your code?

**Comment by hyperpanthera** [comment]
I can confirm that it works well for me too.

**Comment by lab-nit-s** [comment]
Yea.. it is working for me well .. Thanks.
