### ISSUE TITLE
conditional rebuild

### ISSUE THREAD

**Issue by hosamkora** [GIfatahTH/states_rebuilder#33]
is there a way to apply conditional rebuild like this:- 
``` dart
StateBuilder<T>(
....
shouldRebuild:(T model) => predicate 
...
);
```

**Comment by GIfatahTH** [comment]
There is a `watch` parameter in the` setState` method by which you can define the parameters to be watched. Watch here means that notifications are only sent if any of the watched parameters change.

Here is an example: 
https://github.com/GIfatahTH/states_rebuilder/blob/master/example/lib/examples/counter_app_with_watch.dart

**Comment by hosamkora** [comment]
as I understand `watch` won't work in my case:

counter model

```dart
class StateModel {

  int counter = 0;

  bool get isgt20 => counter > 20;

  void inc() {
    counter++;
  }

  void dec() {
    counter--;
  }
}

```

widget 1

```dart
StateBuilder<StateModel>(
  models: [Injector.getAsReactive<StateModel>()],
  builder: (_, model) => Text(
    '${model.state.counter}',
    style: TextStyle(color: colorRandomizer, fontSize: 50),
  ),
),
```

widget 2

```dart
StateBuilder<StateModel>(
  models: [Injector.getAsReactive<StateModel>()],
  tag: 20,
  builder: (_, model) => Opacity(
    opacity: model.state.isgt20 ? 1 : .5,
    child: FloatingActionButton(
      ....  
      backgroundColor: colorRandomizer,
      ....
    ),
  ),
),
```

why widget 2 rebuilds each time `inc` and `dec` triggered like widget 1?

widget 2 should only rebuild when `isgt20` value changes

**Comment by GIfatahTH** [comment]
This is an interesting case.
I think I have to add watch parameter to StateBuilder, some think like this: 
```dart
StateBuilder<StateModel>(
  models: [Injector.getAsReactive<StateModel>()],
  watch :(model) => model.state.isgt20,
  tag: 20,
  builder: (_, model) => Opacity(
    opacity: model.state.isgt20 ? 1 : .5,
    child: FloatingActionButton(
      ....  
      backgroundColor: colorRandomizer,
      ....
    ),
  ),
),
```

**Comment by Chukwunonso** [comment]
Sent from Yahoo Mail on Android 
 
  On Fri, 3 Jan 2020 at 22:35, hosamkora<notifications@github.com> wrote:   
is there a way to apply conditional rebuild like this:-
StateBuilder<T>(
....
shouldRebuild:(T model) => predicate 
...
);

**Comment by GIfatahTH** [comment]
the watch parameter is add to the latest version as an experimental feature, check it:

```dart
StateBuilder<StateModel>(
  models: [Injector.getAsReactive<StateModel>()],
  watch :(model) => model.state.isgt20,
  tag: 20,
  builder: (_, model) => Opacity(
    opacity: model.state.isgt20 ? 1 : .5,
    child: FloatingActionButton(
      ....  
      backgroundColor: colorRandomizer,
      ....
    ),
  ),
),
```

**Comment by hosamkora** [comment]
now it works in the latest experimental version: 
```dart
StateBuilder<StateModel>(
  models: [Injector.getAsReactive<StateModel>()],
  watch :(model) => model.state.isgt20,
  tag: 20,
  builder: (_, model) => Opacity(
    opacity: model.state.isgt20 ? 1 : .5,
    child: FloatingActionButton(
      ....  
      backgroundColor: colorRandomizer,
      ....
    ),
  ),
),
```
but when you put it in a list it won't work as expected :
```dart
StateBuilder<StateModel>(
  models: [Injector.getAsReactive<StateModel>()],
  watch :(model) => [ model.state.isgt20 ],
  tag: 20,
  builder: (_, model) => Opacity(
    opacity: model.state.isgt20 ? 1 : .5,
    child: FloatingActionButton(
      ....  
      backgroundColor: colorRandomizer,
      ....
    ),
  ),
),
```

**Comment by GIfatahTH** [comment]
Thanks again for opening this discussion.

`StateModel` is mutable, so I can not do something like:
```dart
StateBuilder<T>(
....
shouldRebuild:(T oldModel) => oldModel.isgt20 != newModel.isgt20,
...
);
```
What I thought of was taking a representative string snapshot before mutating the state and another string snapshot after mutating the state and compare them.
How performant is this idea of comparing string and how cross-platform is, I am not sure? I need the opinion of a dart expert. For this reason, I say that the watch is feature is experimental.

As stated in dart documentation Strings with the same sequence of code units have the same hash code. This is an optimization, if hashCodes are different this means isgt20 before and isgt20 after are different.

What happens with Lists is that
in dartPad identical of strings obtained from lists of the same elements returns true, whereas in flutter it returns false. Why? I need the opinion of a Dart expert.
in DartPad : 
```dart
      final list = [1];
      print(list.toString().hashCode == list.toString().hashCode); // true
      print(identical(list.toString(), list.toString())); //true
```

but in flutter :
```dart
      final list = [1];
      print(list.toString().hashCode == list.toString().hashCode); // true
      print(identical(list.toString(), list.toString())); //false
```
For this reason `watch` works only for primitive types. Until now, it is up to you to find a primitive representation of your reference type objects; in your particular case, it's very simple.
