### ISSUE TITLE
Register Factory

### ISSUE THREAD

**Issue by pathakvivek7865** [GIfatahTH/states_rebuilder#35]
How can i use the Injector widget to register factory instance of the model?

**Comment by pathakvivek7865** [comment]
there is the condition to open the same page many time on stack but with different data, and the problem is when top page is poped out the the singleton instance of model gets disposed. And since all the pages in the stack are register to same instance of model, the remaining pages couldn't get the model reference. How can i solve this,please help? If you understood the problem please add example.

**Comment by GIfatahTH** [comment]
Injector is a StatefullWidget and can be inserted anywhere in the widget tree. 
As a rule, you insert Injector just before injected models are needed. 
As a good practice, only child widgets of Injector (or widgets created after the Injector) should consume its injected models. This is to ensure that when the Injector is disposed, all other widget that depend on it are disposed before.

If you want a model to be available to all pages in the stack you have to injected it globally that is before MaterialApp widget. 

If you can explain your use case by a representative example it would be very helpful.

**Comment by pathakvivek7865** [comment]
class NewsWidget extends StatelessWidget {
 return GestureDetector(
      onTap: () {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => NewsDetailPage(news: news),
          ),
        );
      },
);
}

/////

class NewsDetailPage extends StatelessWidget {
  final News news;
  NewsDetailPage({@required this.news});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          news.title 
        ),
      
      ),
        body: SingleChildScrollView(
            .
            .
            .
             RelatedNews(),
   
        ),

}


//////////
class RelatedNews extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Injector(
      inject: [
        Inject<RelatedNewsStore>(() => RelatedNewsStore()),
      ],
      builder: (context) {
        return Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Text(
                "Related News",
                style: TextStyle(fontSize: 22),
              ),
              GestureDetector(
                 child: RelatedNewsSingleItem()
                 onTap: () {
                 Navigator.push(
                    context,
                    MaterialPageRoute(
                            builder: (context) => NewsDetailPage(news: news),
                    ),
                ),
               },
             
            ],
          ),
        );
      },
    );
  }
}

**Comment by GIfatahTH** [comment]
Sorry, I can't understand the code and its use case. Can you make it clearer?
