### ISSUE TITLE
rebuildStates strange behaviour 

### ISSUE THREAD

**Issue by playrobotics-alex** [GIfatahTH/states_rebuilder#40]
Hello,

I am trying to call rebuildStates() , when I am calling it just once on tap everything works, but if I try to call this several times with 1 second delay it is not working and the rebuild is done only once.

In this example code, there is a print every second (1,2,3) , but the rebuildStates is executed only once after 3 seconds instead of every second.
```
class Counter extends StatesRebuilder {
   int count = 0;
   increment() {
    count = stopwatch.elapsedMicroseconds;

    rebuildStates();
    print('1');

   sleep(const Duration(seconds:1));

   count = stopwatch.elapsedMicroseconds;;
   rebuildStates();
    print('2');

    sleep(const Duration(seconds:1));
    
    count = stopwatch.elapsedMicroseconds;;
    rebuildStates();    
    print('3');
  }
}
```

**Comment by GIfatahTH** [comment]
I tried the code and it works as expected for me. I wonder what is your use case and why you do not use stream instead.

**Comment by playrobotics-alex** [comment]
Hi, 
Thank you for your reply.
I was just trying to create a 3,2,1 countdown, and as you mentioned, I have ended up implementing it with  regular streams.
