### ISSUE TITLE
Best way to "subscribe" to another model

### ISSUE THREAD

**Issue by AirborneEagle** [GIfatahTH/states_rebuilder#41]
I know this is more of a question, than a bug. but I have gone through all docs, and articles etc, and still do not have a solution.
Here is my situation.  I have two blocs/models (i will call them blocs).   they are both plain dart. I am using the implicit change approach in this situation.

one is an authBloc, and the other is an userInfoBloc.
The user info bloc needs to fetch data based on the person that is logged in. or if the person logs out etc.
I know I could have the authBloc call a the user info bloc on a change, but in my case I cannot do that. the auth bloc is generic, and used in more than one application.
I am trying to Inject a stream, and then having the info bloc subcribe to that, but by the time I create a custom stream and have the info bloc subscribe to it, i feel like I should go back to using flutter_bloc.  sure it had a bunch of boiler plate, and it was tied to buildContext, but i really liked . being able to just have blocs 'listen' to each other.

What is the best way to have a model 'respond' to changes in another model?

**Comment by GIfatahTH** [comment]
Very good use case.
From what I understand you want to make the authBloc notify the userInfoBloc whenever its state changes and execute some methods in the userInfoBloc that will, in turn, notify its observers.

Is this sample of code refects your case?

```dart
class User {
  final String name;

  User(this.name);
}

class AuthBloc {
  User user;
  void login() {
    user = User('Done');
  }

  void logout() {
    print('logout');
  }
}

class UserInfoBloc {
  String infoMessage = '';
  void onUserLogin(User user) {
    infoMessage = '${user.name} is logged in';
  }

  void onUserLogout(User user) {
    infoMessage = '${user.name} is logged out';
  }
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Injector(
      inject: [
        Inject(() => AuthBloc()),
        Inject(() => UserInfoBloc()),
      ],
      builder: (_) {
        return MaterialApp(
          home: Scaffold(
              body: Column(
            children: <Widget>[
              AuthPage(),
              UserInfoPage(),
            ],
          )),
        );
      },
    );
  }
}

class AuthPage extends StatelessWidget {
  final authUserInfoRM = Injector.getAsReactive<UserInfoBloc>();
  @override
  Widget build(BuildContext context) {
    final authBlocRM = Injector.getAsReactive<AuthBloc>(context: context);
    return Row(
      children: <Widget>[
        RaisedButton(
          child: Text('Login'),
          onPressed: () {
            authBlocRM.setState(
              (s) => s.login(),
              onData: (_, authBloc) {
                authUserInfoRM.setState((s) => s.onUserLogin(authBloc.user));
              },
            );
          },
        ),
        RaisedButton(
          child: Text('Logout'),
          onPressed: () {
            authBlocRM.setState(
              (s) => s.logout(),
              onData: (_, authBloc) {
                authUserInfoRM.setState((s) => s.onUserLogout(authBloc.user));
              },
            );
          },
        ),
      ],
      mainAxisAlignment: MainAxisAlignment.center,
    );
  }
}

class UserInfoPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final authUserInfo = Injector.getAsReactive<UserInfoBloc>(context: context);
    return Center(child: Text(authUserInfo.state.infoMessage));
  }
}
```

When the user logs in the `onUserLogin` method of the `UserInfoBloc` is called and the widget `UserInfoPage` observer of `UserInfoBloc`  will rebuild.

**Comment by amoslai5128** [comment]
> Very good use case.
> From what I understand you want to make the authBloc notify the userInfoBloc whenever its state changes and execute some methods in the userInfoBloc that will, in turn, notify its observers.
> 
> Is this sample of code refects your case?
> 
> ```dart
> class User {
>   final String name;
> 
>   User(this.name);
> }
> 
> class AuthBloc {
>   User user;
>   void login() {
>     user = User('Done');
>   }
> 
>   void logout() {
>     print('logout');
>   }
> }
> 
> class UserInfoBloc {
>   String infoMessage = '';
>   void onUserLogin(User user) {
>     infoMessage = '${user.name} is logged in';
>   }
> 
>   void onUserLogout(User user) {
>     infoMessage = '${user.name} is logged out';
>   }
> }
> 
> class App extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Injector(
>       inject: [
>         Inject(() => AuthBloc()),
>         Inject(() => UserInfoBloc()),
>       ],
>       builder: (_) {
>         return MaterialApp(
>           home: Scaffold(
>               body: Column(
>             children: <Widget>[
>               AuthPage(),
>               UserInfoPage(),
>             ],
>           )),
>         );
>       },
>     );
>   }
> }
> 
> class AuthPage extends StatelessWidget {
>   final authUserInfoRM = Injector.getAsReactive<UserInfoBloc>();
>   @override
>   Widget build(BuildContext context) {
>     final authBlocRM = Injector.getAsReactive<AuthBloc>(context: context);
>     return Row(
>       children: <Widget>[
>         RaisedButton(
>           child: Text('Login'),
>           onPressed: () {
>             authBlocRM.setState(
>               (s) => s.login(),
>               onData: (_, authBloc) {
>                 authUserInfoRM.setState((s) => s.onUserLogin(authBloc.user));
>               },
>             );
>           },
>         ),
>         RaisedButton(
>           child: Text('Logout'),
>           onPressed: () {
>             authBlocRM.setState(
>               (s) => s.logout(),
>               onData: (_, authBloc) {
>                 authUserInfoRM.setState((s) => s.onUserLogout(authBloc.user));
>               },
>             );
>           },
>         ),
>       ],
>       mainAxisAlignment: MainAxisAlignment.center,
>     );
>   }
> }
> 
> class UserInfoPage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     final authUserInfo = Injector.getAsReactive<UserInfoBloc>(context: context);
>     return Center(child: Text(authUserInfo.state.infoMessage));
>   }
> }
> ```
> 
> When the user logs in the `onUserLogin` method of the `UserInfoBloc` is called and the widget `UserInfoPage` observer of `UserInfoBloc` will rebuild.

Hey, GlfatahTH, your answer is very great. However, would it be better to put `final authBlocRM = Injector.getAsReactive<AuthBloc>(context: context);`  outside the build, and put it into a didChangeDependencies() method in the AuthPage class? 
Would the performance be faster?

**Comment by AirborneEagle** [comment]
@GIfatahTH 
great answer! :)
This works in some of my use cases, and I have implemented it in those areas. 👍 
In some of my use cases, however, I am finding that there are some strange things needing to be done (probably my ill implementation of blocs) 
but so far your library has presented a way to solve each of them.
one example is that I have a ton of async stuff going on, and the various blocs are communicating with each other behind the scenes of the widgets. these behind the scenes changes are needing to trigger rebuilds. in some cases I can use "listener" classes that just listen to the streams and then they call
something like you mentioned `Injector.getAsReactive<UserInfoBloc>()setState((s) => s.onUserLogout(authBloc.user));`

another one that I ran into had to do with dynamically generated Blocs. 
I have a page displaying information in chunks. each chunk is complex enough to have its own bloc.
it was tricky for me to figure out, and I was not able to find a reliable way to use them with implicit rebuilding.   so I have a parent model which is used reactively, it then has a list of blocs extending StatesRebuilder.  
so then in the code, I can simply iterate over that list of blocs, and have the widgets respond to the explicit calls to `rebuildStates();`

it may be worth noting here.  When tries to use a dynamic list of blocs to respond implicitly, I ran into what seemed like some bugs, where the screen would not rebuild when the list of blocs changed. but if I left and came back, then it would show correctly. and as long as the list of blocs didn't change, then everything worked fine.

**Comment by GIfatahTH** [comment]
Thanks for trying the library fro this complicated situation. As it is such a complicated situation I try to divided it into simple parts and try to understand them and learn from them to improve the library.
Let's start by this part:

>one example is that I have a ton of async stuff going on, and the various blocs are communicating with each other behind the scenes of the widgets. these behind the scenes changes are needing to trigger rebuilds. in some cases I can use "listener" classes that just listen to the streams and then they call something like you mentioned Injector.getAsReactive<UserInfoBloc>()setState((s) => s.onUserLogout(authBloc.user));


>communicating with each other behind the scenes of the widgets

Do you mean that some of your blocs depend on other of your blocs?

>in some cases I can use "listener" classes

What do you mean by "listener" classes?


Let's say I have three blocs; BlocA, BlocB, and BlocC.
How can a listener class subscribe to the three blocs and what is the use case here?

I really want to make a profit from your use case? I add `OnSetStateListener` class that I want to improve and I think your use case can help me.

In my head, I have something like this.

```dart
OnSetStateListener(
  models:[blocARM, blocBRM, blocCRM],
  onSetState: (context, blocRM){

    if(blocRM is reactiveModel<BlocA>){
      call of .setState((s)=>s.method()),
    }

    if(blocRM is reactiveModel<BlocB>){
      calls of  .setState((s)=>s.method()),
    }

    if(blocRM is reactiveModel<BlocC>){
      calls of .setState((s)=>s.method()),
    }
  },

  child: ChildWidget(),
);
```

As you can see OnSetStateListener subscribe to three reactive models A, B, and C. `OnSetStateListener` will not rebuild its child, but it will invoke `onSetState` method each time any of the three blocs emits a notification. (OnSetStateListener is for side effects only).

`OnSetStateListener` calls its `onSetState` method each time any of its subscribed reactive models emits a notification. It calls `onSetState` with the bloc that emits the notification in the parameter (blocRM).

So I check for the type of bloc that emits the notification and do whatever you want.

By this you do not want to define stream and subscribe to them, I suppose!

`OnSetStateListener` will have `onError` and `onData` parameters to be invoked only if any of the blocs have en error for the former, and if all the blocs have data for the latter.

**Comment by AirborneEagle** [comment]
Thank you! 
I would for sure see a benefit to having a listener object like the one you mentioned.  but I would need to spend more time thinking about how it would be implemented in a way that is most useful.
My first reaction is that I would like a widget that just listens to the models, but does not rebuild the child widgets. this could be used for things like triggering alerts, or snackbars, etc. 
Let me use the example of in app notifications.
I want to trigger an alert based on what happens in the database.
one bloc handles all the logic surrounding the data (wether or not we need to notify, or maybe we need to fetch additional data first, etc),
 and then I have a bloc that handles the notifications (read/unread/ control the device/play sounds etc. filter notifications based on the app state/behavior etc.)

Right now, I have something like this:
```
/// used as Reactive Model
class DataBloc {
   static final instance = DataBloc._internal();
   DataBloc._internal() {
         DataListener.instance.setListeners();
   }

   List<Data> data = [];
   void updateData(data){
      /// look at the data and pass through logic
      Injector.get<NotificationBloc>().triggerNotice(someData);
   }
}

/// I have this as a separate class, because in my app, it is much bigger than just a single stream listener
class DataListener {
   /// singleton 
   void setListeners(){
      dataBase().streamData().listen((newData){
      Injector.getAsReactive<DataBloc>().setState((state){
                state.updateData(newData);
            });
      })
  }
}

```

> Do you mean that some of your blocs depend on other of your blocs?

in some cases yes. but I am refactoring as I go to avoid that.
What I am meaning, is that the blocs could trigger behavior in one another.  

Perhaps your idea of a listener widget would help avoid this problem.
I really liked the [BlocListener](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocListener-class.html) from the `flutter_bloc` package.
the ability to have a `condition` .  never running more than one time per state change (compared to the flutter build method) etc.  

I am not sure if that helped at all.  :/

**Comment by GIfatahTH** [comment]
>My first reaction is that I would like a widget that just listens to the models, but does not rebuild the child widgets.

`OnSetStateListener` does exactly what you want and give you three callbacks to execute side effects: 
* `onSetState` callback for general use
* `onDate` if all observable models have data
* `onError` if at least one of the models has an error.

>the ability to have a condition. never running more than one time per state change (compared to the flutter build method) etc.

`OnSetStateListener` has a `watch` parameter to link the rebuild to a particular state change.

>I really liked the BlocListener from the flutter_bloc package.

`OnSetStateListener` is compared to `BlocListener` except that in `BlocListener` the current state name is exposed and you can use it in your logic. (states in flutter_bloc are a discrete set of state snapshot of your app ex: loading, error, increase, pause, running ....)

Whereas states_rebuilder is not based on naming your discrete states and adding events to trigger a change from one state to another. 

BUT in states_rebuilder you have access to the most expected state, `onIdle`, `onWaiting`, `onError`, and `onData`. For another state status you, until now, you can use custom-defined states.

In the [countdown timer example](https://github.com/GIfatahTH/states-rebuilder-examples/blob/master/006-countdown_timer/lib/main.dart),  I used the idea of custom state status, and I defined it using enumeration:
```dart
enum TimerStatus { ready, running, paused }
```

**Comment by AirborneEagle** [comment]
I think that this new class sounds like it will help solve a number of issues I am running into.

Do you happen to have an example uploaded where I can see how it is used.?

**Comment by AirborneEagle** [comment]
I have used it in one place now. Thank you! this is exactly what I was looking for!
I will go ahead and close this issue now.
I would suggest that we get some documentation on how to use this class, as well as a good example. 
If I can get to it, and you have not already done it, I will submit a PR with something to that effect.

Good work @GIfatahTH 🎉

**Comment by GIfatahTH** [comment]
Thank you. I will try to find a good example of using OnSetStateListener. At the same time, I will wait for your contribution because I really need a community contribution.

>note: I found that to be able to use the OnSetStateListener, I needed to upgrade to the latest version of states_rebuilder. which was 1.12.1 at the time.

The latest version is 1.13.0 right now!

**Comment by AirborneEagle** [comment]
I am still planning to contribute. :)   
things are just super busy.

**Comment by AirborneEagle** [comment]
I just pulled the repo, but, @GIfatahTH, it looks like you already got to the examples and docs for `OnSetStateListener`

is there anything else you would like some help with on this repo?

**Comment by GIfatahTH** [comment]
Thanh you
