### ISSUE TITLE
WhenRebuilder initState issue

### ISSUE THREAD

**Issue by asarkar1990** [GIfatahTH/states_rebuilder#46]
I am subscribing to a stream inside WhenRebuilder initState . But it gives me the following error :
`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() or markNeedsBuild() called during build.
E/flutter (27396): This StateBuilder<dynamic> widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter (27396): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (27396):   StateBuilder<dynamic>
E/flutter (27396): The widget which was currently being built when the offending call was made was:`

how i am using it:
**On UI**
body: WhenRebuilder(
          models: [Injector.getAsReactive<StorageLossBloc>()],
          initState: (_, ReactiveModel<StorageLossBloc> bloc) {
            print("init state");
            bloc.setState(
              (state) => state.subscribe(),
            );
          },

**Bloc:**
import 'dart:async';

import 'package:lsms/models/model.dart';
import 'storage_loss_repository.dart';

class StorageLossBloc {
  StreamSubscription _subscription;
  final StorageLossRepository _repo = StorageLossRepository();
  List<StorageLoss> _storageLosses = [];

  List<StorageLoss> get storageLosses => _storageLosses;

  void subscribe() {
    _subscription = _repo.storageLosses().listen((List<StorageLoss> list) {
      _storageLosses = list;
    });
  }

  void dispose() {
    _subscription.cancel();
    _storageLosses = [];
  }

  Future<bool> save(StorageLoss _loss) async => await _repo.save(_loss);
}

I want to be able to subscribe to the stream when the widget build for the first time and cancel the subscription on dispose.

**Comment by GIfatahTH** [comment]
Thanks for reporting an issue.

I think subscribing to a stream does not need to be done inside a setState. Why not try this
```dart
body: WhenRebuilder(
models: [Injector.getAsReactive()],
initState: (_, ReactiveModel bloc) {
print("init state");
bloc.state.subscribe();
}
```
Even better Why not use Inject.stream and expose your data from the stream (list) to the whidget tree.

**Comment by asarkar1990** [comment]
> Thanks for reporting an issue.
> 
> I think subscribing to a stream does not need to be done inside a setState. Why not try this
> 
> ```dart
> body: WhenRebuilder(
> models: [Injector.getAsReactive()],
> initState: (_, ReactiveModel bloc) {
> print("init state");
> bloc.state.subscribe();
> }
> ```
> 
> Even better Why not use Inject.stream and expose your data from the stream (list) to the whidget tree.
`body: WhenRebuilder(
models: [Injector.getAsReactive()],
initState: (_, ReactiveModel bloc) {
print("init state");
bloc.state.subscribe();
}`
The above solution does not work. Seems like the UI do not rebuild for the changes in the bloc.
"Even better Why not use Inject.stream and expose your data from the stream (list) to the widget tree" - 
Yes. This one works . But what I was trying is to inject the whole bloc and not injecting the streams separately because I need  to access  other properties of that bloc too.

**Comment by GIfatahTH** [comment]
I apologize for my late response!

>Yes. This one works . But what I was trying is to inject the whole bloc and not injecting the streams separately because I need to access other properties of that bloc too

You can inject your bloc and your stream, some thing like this:

```dart
Injector(
  inject :[
    Inject(()=>YourBloc(),
    Inject.stream(()=>Injector.get<YourBloc>().yourStrem())
 ]
 builder:(_){
   //you can access your bloc and subscribe to your stream
    }
)
```

**Comment by asarkar1990** [comment]
Thank you for your kind reply. Yes finally I solved the issue as you mentioned here.
