### ISSUE TITLE
StateProxy?

### ISSUE THREAD

**Issue by webskydavid** [GIfatahTH/states_rebuilder#47]
Hi, im wondering if there is a way to create a proxy state that can be used in other state classes. For example like it is used in provider package:
```
Widget build(BuildContext context) {
  return MultiProvider(
    providers: [
      ChangeNotifierProvider(create: (_) => Counter()),
      ProxyProvider<Counter, Translations>(
        create: (_, counter, __) => Translations(counter.value),
      ),
    ],
    child: Foo(),
  );
}
```
I would like to create a parent state model that holds some date to used in other models and the date are pushed throw the parameters . Only child models can use parent model. Subscribing is not the case. 
The child models need also be notified if the parent model has changes.

Any idea?

**Comment by GIfatahTH** [comment]
From what I understand from the Provider package, `ProxyProvider` is used to inject dependencies of a class. In your example, `Translations` class depends on the `Counter` class. 
in `hangeNotifierProvider(create: (_) => Counter()),` you have registered the Counter class and in the next ProxyProvider you have injected the registred instance in the Translations class.

In the states_rebuilder logic you can achieve the same results by:
```dart
Widget build(BuildContext context) {
  return Injector(
    inject: [
      Inject( () => Counter()),
      Inject( () => Translations(Injector.get<Counter>().value)),
      ),
    ],
    builder:(_)=> Foo(),
  );
}
```

You said:
>The child models need also be notified if the parent model has changes.

I don't think that you can achieve such a thing with ProxyProvider. Correct me if I am wrong.

In states_rebuilder, parent class  `Counter` can notify child class `Translations` in the `setState` method
```dart
counter.setState((s)=>s.increment(),
  onData:(_,__){
    translations.setState((s)=>s.doSomething());
 }
);
```
This code means that when the increment() method of the counter object is invoked, it will change the state of the counter and notify its observers. After the counter state is mutated without error, the doSomething() method of translations object is invoked and it will notify widgets observing the translations reactive model.

If you want to link counter with translations globally so that counter model changes it will notify the translations model you can use OnSetStateListener widget:

```dart
Widget build(BuildContext context) {
  return OnSetStateListener<Counter>(
              models:[Injector.getAsReactive<Counter>(),
              onData:(context,counterRM){
                  translations.setState((s)=>s.doSomeThing());
              }
             child : SomeWidget()
           )
}
```
This means that whenever counter model emits a notifcation, it will notify translations to do some thing.

**Comment by D10100111001** [comment]
@GIfatahTH I'm struggling with this same exact issue.

**App.dart**
```dart
Widget build(BuildContext context) {
  return Injector(
    inject: [
      Inject( () => EnvironmentConfig()),
    ],
    builder:(_)=> LoginScreen(),
  );
}
```

**LoginScreen.dart**
```dart
Widget build(BuildContext context) {
  final environmentRM = Injector.getAsReactive<EnvironmentConfig>(context: context);
  return Injector(
    inject: [
      Inject( () => ApiService(environmentRM.state.baseUrl)),
      ),
    ],
    builder:(_)=> Foo(),
  );
}
```

I was expecting something like this to work and it seems more logical and readable with the design of how we are using reactive models. In this case, I want a new `ApiService` class to be created everytime the environment config changes with the proper and other data passed in without have mutable fields in the ApiSerice. I dont want ApiService to be a mutable class. All of the properties will be immutable and it will act like a pure service class with no mutations whatsoever. So when I use the `Injector.get<ApiService>()` it will give me the most up to date version of the model.

Also, is there a community chat application you use so we can have real-time communication so I can ask questions easier without creating issues? Something like Discord, Slack, Gitter, etc.

**Comment by GIfatahTH** [comment]
Do you mean that each time `environmentRM` emits a notification, you want to reinject the `ApiService` with the new value of `baseUrl`.

You can add a unique key to the injector widget so that the  `ApiService` is unregistered and registered for each rebuild.

```dart
Widget build(BuildContext context) {
  final environmentRM = Injector.getAsReactive<EnvironmentConfig>(context: context);
  return Injector(
      key: UniqueKey(),
    inject: [
      Inject( () => ApiService(environmentRM.state.baseUrl)),
      ),
    ],
    builder:(_)=> Foo(),
  );
}
```

**Comment by D10100111001** [comment]
Is there a way to know from multiple reactive models which one caused the current build method call? (even if it is batched).

Example:
```dart
Widget build(BuildContext context) {
  final environmentRM = Injector.getAsReactive<EnvironmentConfig>(context: context);
  final appRM = Injector.getAsReactive<AppConfig>(context: context);
  return Injector(
      key: environmentRM.isSource ? UniqueKey() : GlobalKey(),
    inject: [
      Inject( () => ApiService(environmentRM.state.baseUrl)),
      ),
    ],
    builder:(_)=> Foo(),
  );
}
```

**Comment by GIfatahTH** [comment]
>Is there a way to know from multiple reactive models which one caused the current build method call? (even if it is batched).

[See this note on the exposed model! It may help!](https://github.com/GIfatahTH/states_rebuilder/tree/master/examples/002-form_validation_with_reactive_model#note-on-the-exposed-model)

What do you mean by `environmentRM.isSource`
```dart
Injector(
      key: environmentRM.isSource ? UniqueKey() : GlobalKey(),
    inject: [
      Inject( () => ApiService(environmentRM.state.baseUrl)),
      ),
    ],
    builder:(_)=> Foo(),
```

Your case seems very interesting, and I am working on a way to let Injector listen to reactive model and re-inject the model when the reactive model  emits a notification:

something like this :

```dart
Widget build(BuildContext context) {
  final environmentRM = Injector.getAsReactive<EnvironmentConfig>(context: context);
  final appRM = Injector.getAsReactive<AppConfig>(context: context);
  return Injector(
    inject: [
      Inject( () => ApiService(environmentRM.state.baseUrl)),
      ),
   //Here whenever environmentRM emits a notification the `ApiService(environmentRM.state.baseUrl)` is reinjected
    reinjectOn : [environmentRM],
    ],
    builder:(_)=> Foo(),
  );
}
```

**Comment by D10100111001** [comment]
@GIfatahTH When can I expect the release of v1.14.3?

**Comment by GIfatahTH** [comment]
@D10100111001 Tomorrow if no surprises are thrown.

**Comment by GIfatahTH** [comment]
In the upcoming update, I added a new feature that is related to this issue.

## `Inject.previous` Constructor

With the named constructor `Inject.previous`, you can inject and reinject objects by keeping track of their previous values before reinjection. `Inject.previous` is very useful when combined with the `reinjectOn` parameter.

Let's say we are in a shopping app, where a list of products will be displayed based on the authenticated user.

Our basic app will have an `Auth` class and a `Products` class. The `Products` class depends on the Auth class.

To inject the Products 

```dart
 return Injector(
    inject: [
        //Injecting the Auth object
        Inject(()=>Auth()),
        Inject.previous(
            (Products previous) => Products(
                //used to fetch data in the Products object
                token: Injector.get<Auth>().token,
                // authenticated user ID
                userId: Injector.get<Auth>().userId,
                //List of all items we want to keep from the previous Products object
                items: previous.items ?? [], 
                //We can establish more then one dependence
                otherProperty: Injector.get<OtherModel>().otherProperty,
            ),
        ),
    ],
    //Here the connection between Products and Auth objects is established
    //Whenever authRM emits a notification, the injected Products instance  
    //is override by a new one as defined in the Inject.previous constructor.
    reinjectOn: [RM.get<Auth>(), RM.get<OtherModel>()],
    //shouldNotifyOnReinjectOn:true, //this is the default behavior
    builder: (_) => ....

 )
```
>`reinjectOn` takes a list of `ReactiveModel`s, so theoretically you can link `Products` to an infinite number of objects

>By default the Products widget listeners will be notified when any of the models defined in the `reinjectOn` parameter issues a notification. To override this behavior set `shouldNotifyOnReinjectOn` parameter to false

**Comment by pMertDogan** [comment]
Hi,
I want store User friends in Foo class.When the User friends changed Foo class must be updated with the new value.

User.dart
```
class User{
string name,x,y,z;
List<Friend> friendList = <Friend>[ Friend(name: "Jack"),Friend(name: "Mark")  ]
}
```

Foo.dart
```
class Foo{
String a;
String b;
List<Friend> _userFriends;

Foo({@required User userClass}){
_userFriends = userClass.friendList;
}

}
```

So should i use this code?

```

Injector(
    inject: [
        Inject(()=>User()),
        Inject.previous(
            (User previous) => Foo(
                userClass: Injector.get<User>(),
            ),
        ),
    ],

```

Is it correct? 

Thanks

**Comment by GIfatahTH** [comment]
@pMertDogan  apologize for the late response;

Yes with `reinjectOn `parameter:

```dart
Injector(
    inject: [
        Inject(()=>User()),
        Inject.previous(
            (User previous) => Foo(
                userClass: Injector.get<User>(),
            ),
        ),
    ],
   reinjectOn: [RM.get<user>()]
```
