### ISSUE TITLE
How I can set to idle state?

### ISSUE THREAD

**Issue by vico-aguado** [GIfatahTH/states_rebuilder#49]
HI! 

I need reset my model to idle state, but I don't know how :(

I run one method in my model and works fine the flow : .none -> .waiting -> .done, but I need set .none again, my model still in .done forever.

Could you help me?

Thank for all

**Comment by GIfatahTH** [comment]
Hi and thank you for try states_rebuilder and opening an issue.

Yes that the way states_rebuilder work. once you are out from the idle (none) state you can not go back to it.

I can manage to add a setter to get it back to idle, but I do not see the use case here.

Could you explain by example the benefit of having the ability to set to the idle state?

**Comment by vico-aguado** [comment]
Sure!

I explain my case:

I have a screen where users choose tickets (adult, child, senior) , this screen calls services like getTickets, getShowtimes, etc, and works fine with different instances to the same TicketsModel (with seeds), but, this screen have a button to add a voucher (like a free ticket), so, it open one modal custom sheet (showCupertinoModalPopup). 

In this modal I check the voucher is not redeemed to add it to tickets, if it is redeemed I show the error. So, the flow of TicketsModel (seed: voucher) after of error it stills in .done (with hasError). 
When I show showCupertinoModalPopup again it shows to the user the last error in these screen. :(

So, I want to reset this flow and I don't know how :(

Could you help me?

Thank for all

**Comment by GIfatahTH** [comment]
Now I understand your case. And it is an important case.

After you call a method in a reactive model (TicketsModel (seed: voucher)) and if it ends with an error, the model async state remains on hasError state.

You may want something like this:
```dart
onPressed: () => ticketsModel .setState(
                (s) => s.someMethod(),
               onError: (context, error) async {
             //display and await until the user dismiss the alert dialog
              await showCupertinoModalPopup(
                  context: context,
                  builder: (context) {
                    return CupertinoAlertDialog(
                      content: Text('error'),
                    );
                  });
             //The new feature is to have the ability to reset the async state to idle without notifying observers widget 
              ticketsModel .resetConnectionState();
  });
```

**Comment by vico-aguado** [comment]
Yeah! You understand my case perfectly!!, that would help me a lot !!

Do you know when I can use this new feature (resetConnectionState) ?

Thank for all

**Comment by GIfatahTH** [comment]
I added `resetToIdle` and `resetToHasData` methods. See the changelog [v-1.14.0 ](https://github.com/GIfatahTH/states_rebuilder/blob/v-1.14.0/states_rebuilder_package/CHANGELOG.md)
