### ISSUE TITLE
How to setState() from non UI code like bloc ?

### ISSUE THREAD

**Issue by asarkar1990** [GIfatahTH/states_rebuilder#50]
It's not an issue . It's a question. 
How can I setState() form backgroup code ?
If app state changes due to external network stream then how can I notify UI?

**Comment by GIfatahTH** [comment]
what do you mean by calling setState from (background) code?. Do you consider `onValue` stream from firebase as an external network stream? if so use Inject.stream and you can notify the UI when stream emits data.
