### ISSUE TITLE
About initialData like StreamBuider

### ISSUE THREAD

**Issue by binhodev** [GIfatahTH/states_rebuilder#53]
Hello @GIfatahTH ,

I have enjoyed your work, I would like to ask a question.
As in StreamBuilder, has initialData, with StateBuilder is it possible too? 

Ah! Editing...
How work StateBuilder > initState?
It is same that override method (initState) to initializate? Why i need initialize a Stream to listen, type:
```
myBloc.myGetStream.listen((state){
   ...
}
```

**Comment by GIfatahTH** [comment]
Hi @binhodev , 
with states_rebuilder you can inject streams and futures using `Inject.stream` and `Inject.future`.
both `Inject.stream` and `Inject.future` have `initialValue ` parameter.

This is a snippet of code form [countdown Timer](https://github.com/GIfatahTH/states_rebuilder/tree/master/examples/004-countdown_timer)
```dart
      inject: [
        //NOTE4: Injecting the stream
        Inject<int>.stream(
          () => Stream.periodic(Duration(seconds: 1), (num) => num),
          //NOTE4 : Defining the initialValue of the stream
          initialValue: 0,
        ),
      ],
```


>Ah! Editing...
>How work StateBuilder > initState?
>It is same that override method (initState) to initializate? Why i need initialize a Stream to listen, >type:
YOU do not need to listen to stream if you use `Inject.stream`
If you use `Inject.stream` you automatically listen to it and automatically cancel subscription from it when the widget is disposed.

**Comment by binhodev** [comment]
WoW!! Thanks my friend to explanations, have a nice day!
