### ISSUE TITLE
DeskTop Support(Mac,Linux,Windows)

### ISSUE THREAD

**Issue by KaushickSArgekar** [GIfatahTH/states_rebuilder#56]
Need a Desktop Support

**Comment by GIfatahTH** [comment]
We have to wait until desktop is supported by flutter in the master channel

**Comment by KaushickSArgekar** [comment]
It's already supported in the master channel
I am using it 
packages like
url_launcher.
shared_prefs
flare_flutter are supporting in desktop

**Comment by GIfatahTH** [comment]
I think it is supported for mac only. Am a windows use and flutter is in early-stage for windows

>This page covers desktop support for macOS which is available as an alpha release as of 1.13. This page does not cover Windows or Linux platforms, which are in technical preview. You can try Windows and Linux platform support by reading the Desktop shells page in the Flutter wiki.

Is there any problem with the desktop? are the other state management supported for desktop?

**Comment by advancedtw** [comment]
i'm using states_rebuilder on mac flutter desktop. no problems encountered nor was i expecting any.

**Comment by KaushickSArgekar** [comment]
I encountered error at

Router.navigator.pop();
