### ISSUE TITLE
Keep TabBarView alive

### ISSUE THREAD

**Issue by hyperpanthera** [GIfatahTH/states_rebuilder#6]
Hi, I put two widgets which I wrapped with the [StateBuilder] in a [TabBarView] which is also wrapped in [StateBuilder] but when I switch between the tabs, the two widgets always rebuild.

How can I fix that?

**Comment by GIfatahTH** [comment]
Does the 1.1.0 update help?

**Comment by hyperpanthera** [comment]
I will check tomorrow! Thanks for the reminder.

**Comment by hyperpanthera** [comment]
@GIfatahTH Check out issue #19116, I think AutomaticKeepAliveClientMixin is required to fix this issue.

Nevertheless, I will try it out with the new update tomorrow.

Thanks.

**Comment by hyperpanthera** [comment]
@GIfatahTH Still does not work. Might be an issue with Flutter though. Any idea?

**Comment by GIfatahTH** [comment]
@hyperpanthera  Yes it is the Flutter way. When you switch between tabs they rebuild. As you said AutomaticKeepAliveClientMixin is required to prevent them from rebuilding. For this, you simply wrap your widget inside a statefulWidget and mix with AutomaticKeepAliveClientMixin and set wantKeepAlive to true.

By the way, there are many mixens to be used with StatefulWidget. I intend to make some of them available in StateBuilder, for example:
1- TickerProviderStateMixin (already added)
2- WidgetsBindingObserver 

Do you have any proposition of the important ones you advise me to add?

**Comment by hyperpanthera** [comment]
Thanks for your analysis.

AutomaticKeepAliveClientMixin could be useful to keep the TabBarViews alive.

**Comment by hyperpanthera** [comment]
Closing it because it is not related to this library but rather related to Flutter itself.
