### ISSUE TITLE
Rebuild increases on every route change with getAsReactive

### ISSUE THREAD

**Issue by cocacrave** [GIfatahTH/states_rebuilder#65]
I'm facing a problem where I must be doing it wrong. I asked the question on stackoverflow but getting no replies.

First I've injected `onAuthStateChanged()` stream from FirebaseAuth, which returns `Stream<User>`

```
return runApp(
  Injector(
    inject: [Inject.stream(() => Injector.get<AuthStore>().onAuthStateChanged())],
    builder: (_) => HomePage();
  ),
);
```

Then I've wrapped all my page routes with `PageBuilder` to check if user is logged in or not. Which seems to create the problem.

```
class PageBuilder extends StatelessWidget {
  @override
  Widget build(context) {
    final authRM = Injector.getAsReactive<User>(context: context);
    print(authRM);
    return ....
  }
}
```

On initial run, the output from `print(authRM)` is:
```
Stream of <User> singleton reactive model (#Code 357289166) => isWaiting
Stream of <User> singleton reactive model (#Code 357289166) => hasData : null
```

Then if I change route (which also is wrapped by `PageBuilder`) the output is:
```
Stream of <User> singleton reactive model (#Code 357289166) => hasData : null
Stream of <User> singleton reactive model (#Code 357289166) => hasData : null
```

Then route again:
```
Stream of <User> singleton reactive model (#Code 357289166) => hasData : null
Stream of <User> singleton reactive model (#Code 357289166) => hasData : null
Stream of <User> singleton reactive model (#Code 357289166) => hasData : null
```

And next route: 4, next: 5, next: 6, ... and on and on.

Obviously I'm not getting how this works... Please help.

**Comment by cocacrave** [comment]
I get it now... Really had to read the docs carefully.

**Comment by GIfatahTH** [comment]
@cocacrave  thank you for opening the issue. 
I have tried to reproduce your case and have not got it. If you have a full simple example that reproduce your case that would be very helpful.

Please that routing in flutter cause rebuilding of all pages  on Navigator stack.

see this:

https://github.com/flutter/flutter/issues/11655
and
https://stackoverflow.com/questions/52249578/how-to-deal-with-unwanted-widget-build

**Comment by cocacrave** [comment]
Omg thank you! I changed pushNamed to pushReplacementNamed and no more duplicate outputs.
Btw I love your example apps, they've been a great resource.
