### ISSUE TITLE
How to user Inject.future?

### ISSUE THREAD

**Issue by binhodev** [GIfatahTH/states_rebuilder#66]
Hello @GIfatahTH 

About Inject.future, i can get a FireabaseUser uid? I tryed like this:

Injecting:
```dart
Inject<FirebaseUser>.future(() => FirebaseAuth.instance.currentUser(),)
```

Registering:
```dart
final firebaseUserAuth = Injector.getAsReactive<FirebaseUser>(context: context).snapshot;
```

It return null in 
```dart
print('UID: ${firebaseUserAuth.data.uid}
```

**Comment by GIfatahTH** [comment]
Injecting future works,

Please  try this print and inform me back::

```dart
final firebaseUserAuth = Injector.getAsReactive<FirebaseUser>(context: context).snapshot;

print(ReactiveModel<FirebaseUser>());
```

**Comment by binhodev** [comment]
> Injecting future works,
> 
> Please try this print and inform me back::
> 
> ```dart
> final firebaseUserAuth = Injector.getAsReactive<FirebaseUser>(context: context).snapshot;
> 
> print(ReactiveModel<FirebaseUser>());
> ```

Hello, tryed and log this:
`Future of <FirebaseUser> singleton reactive model (#Code 230150760) => isWaiting (null)`


```dart
final firebaseUserAuth = Injector.getAsReactive<FirebaseUser>(context: context).snapshot;
```

Analyzing the previous line of code, to get the result in onSetState in StateBuilder, that is, to get the result it is necessary to wait for it to happen, the problem was that in the Build method it always returns null because the result was requested in the Build construction and not before.

What I did, I kept the code and used the condition to check if there was data. Would that be the correct way to obtain the data?

Regards,
Binho

**Comment by GIfatahTH** [comment]
Form the log you provide I do not see the onData part. I shoul see some thing like this:
```dart
Future of <FirebaseUser> singleton reactive model (#Code 230150760) => onData (...)
```

This means that the future is not resolved. You have to figure out if the  `FirebaseAuth.instance.currentUser()`  futre ends with data

**Comment by binhodev** [comment]
I'll close this, now this working! Thanks!
