### ISSUE TITLE
Could you do a example about Firestore?

### ISSUE THREAD

**Issue by amoslai5128** [GIfatahTH/states_rebuilder#67]
GIfatahTH,

Thanks for your great works and you're a lifesaver, I do love this states_rebuilder.

Could you offer a new example about Firestore based on example 007?  
It's more than happy with a user profile upload function or more complex practice!

Btw, where happened to example 009? 

Cheers,

**Comment by GIfatahTH** [comment]
>Cloud you offer a new example about Firestore based on example 007?
It's more than happy with a user profile upload function or more complex practice!

I will do in the future.

>Btw, where happened to example 009?
The example 010 should be 009, I Will fix it in the next release.

**Comment by amoslai5128** [comment]
> > Cloud you offer a new example about Firestore based on example 007?
> > It's more than happy with a user profile upload function or more complex practice!
> 
> I will do in the future.
> 
> > Btw, where happened to example 009?
> > The example 010 should be 009, I Will fix it in the next release.

Dear GIfatahTH,
I've finished a Firestore version of Example 009/010, instead of your Firebase Database, however, there's something I don't understand:

In data_source, xxx_respository.dart, you defined a  Stream<List<Counter>> countersStream() { } for return a stream. When I change it to Firestore, data doesn't automatically change. 

Here is my solution: 
I don't know is there a better for the alternative of the **broadcast stream**?

```
final StreamController<List<Asset>> _assetsController =
      StreamController<List<Asset>>.broadcast();


  @override
  Stream assetStream(String uid) {
    // Register the handler for when the assets posts data changes
    ref.document(uid).collection('Assets').snapshots().listen((snap) {
      if (snap.documents.isNotEmpty) {
        var posts = snap.documents
            .map((doc) {
              print('resp: ' + doc.data.entries.toString());
              return Asset.fromMap(doc.data, doc.documentID);
            })
            .where((aseet) => aseet.name != null)
            .toList();

        // Add the posts onto the controller
        _assetsController.add(posts);
      }
    });

    // Return the stream underlying our _assetsController.
    return _assetsController.stream;
  }
```

**Comment by GIfatahTH** [comment]
I will try it.

**Comment by amoslai5128** [comment]
> I will try it.

Thank you so much.

**Comment by amoslai5128** [comment]
OMG, YOU DID IT :)
How generous you are!  

So many breaking changes... 
what's the difference between these two scripts (any performance issues)?
1. Example you provided
 `observe: () => RM.future(IN.get<UserService>().currentUser())`
2. Doc stated that
 `observe: () => RM.get<UserService>.future((s, stateAsync) => s.currentUser())`
3. This one sometimes doesn't work 
 `observe: () => RM.get<UserService>()..setState((s) => s.currentUser(), watch:userServiceRM.state.user),`

**Comment by GIfatahTH** [comment]
The first and the second both give you a new ReactiveModel from the returning future of currentUser. Expect that the second exposes the stateAsycn if you want to await possible currently executing future.

The third one execute the setState on the global UserService ReactiveModel. 

So if you want to limit the rebuild to the current StateBuilder use the first or the second. If you want to rebuild all other observer widgets subscribed to the global UserService ReactiveModel use the third.

BTW, in the third case, can you show some cases where it doesn't work.

**Comment by amoslai5128** [comment]
> The first and the second both give you a new ReactiveModel from the returning future of currentUser. Expect that the second exposes the stateAsycn if you want to await possible currently executing future.
> 
> The third one execute the setState on the global UserService ReactiveModel.
> 
> So if you want to limit the rebuild to the current StateBuilder use the first or the second. If you want to rebuild all other observer widgets subscribed to the global UserService ReactiveModel use the third.
> 
> BTW, in the third case, can you show some cases where it doesn't work.

Thank you for your kind answer, I've got a better understanding.
The third one was coursed by other things after I checked, so it's completely no problem :)

**Comment by amoslai5128** [comment]
Hey GIfatahTH  :)
I know it's out of this topic, however, will you plan to release a new article about the least changes from the states_rebuilder? 

I figured out your ReactiveModel is not a simple thing at all, to satisfy the curiosity, I've been reading papers, studies for Dependency Injection, Dependency Inversion and Inversion of Control (IoC), but it's over my knowledgable level  X_X...  

UNTIL I saw old comments from Youtube tutorial (Interestingly he did mention your library LOL) https://www.youtube.com/watch?v=vBT-FhgMaWM

**Comment by GIfatahTH** [comment]
>I figured out your ReactiveModel is not a simple thing at al

Do you mean that it is difficult to understand and implement? And what do you expect from an article to make it simpler?

>UNTIL I saw old comments from Youtube tutorial (Interestingly he did mention your library LOL) >https://www.youtube.com/watch?v=vBT-FhgMaWM

Do you mind quote the comment?

**Comment by amoslai5128** [comment]
> To share a bit what's all about:
- Vanilla BLoC for state management and also serve as MVP/MVVM architecture, no package, just InheritedWidget + Streams and StreamBuilders + one little widget I created for simplicity (when streams are overkill) inspired on the package ***states_rebuilder*** (which is a very simplistic but elegant way of state management using what's already provided by Dart and Flutter). This little widget is basically a stateful widget that uses setState when notified from the BLoC, somehow serves a similar function that of "NotifyPropertyChanged" but without all the hassle of the binding pattern.

It's the first on-top comment, you can search by "Amen brother! I'm a huge"

**Comment by GIfatahTH** [comment]
Great!!

>I wish the doc can tell more about How DI (or Service Locator?) with Reactive Model, the states >flow, and it might be an idea to have a simple comparison to the latest flutter_bloc. Haha, is it too >greedy?

This is exactly what I'm doing right now:

* I am rewriting the documents so that the readme file is very short for a quick start, and I will use github wiki for detailed documentation.

* I am implementing the TodoMVC using states_rebuilder following the same approach as with flutter_bloc (immutability, states, events) so that one can easily compare the two.

Any contribution is welcome.

**Comment by amoslai5128** [comment]
🌝WoW, cannot wait more!! I think your library will grow up as popular as flutter bloc😃. 

Yes, I think a short quick start guideline is necessary.
Also a part for people shouldn't do that, some kind of examples on tge table, giving few bad examples on left side, and answer on the right 

I can contribute the language translation of traditional Chinese & ZH-SC, if you wish🌞

**Comment by GIfatahTH** [comment]
That would be fantastic.

Now docs are on the v-2.1.0 branch, do you mind checking them?

**Comment by amoslai5128** [comment]
> That would be fantastic.
> 
> Now docs are on the v-2.1.0 branch, do you mind checking them?

Haha, I do like the first part with emoji 😆🤣
It looks fun and vibrant🌞

**Comment by amoslai5128** [comment]
Btw, would the new version 2.1 add multiple RMKeys: [ () => ]?

**Comment by GIfatahTH** [comment]
In the  new version 2.1, to get the `reaciveModel `created in `observeMany `parameter, we use the rmKey paramter with the new `get` method.

Here is an example inspired from #83 
```dart
class StateBuilderTest extends StatelessWidget {
  //create a key
  final rmKey = RMKey();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: StateBuilder(
          observeMany: [
            //two ReactiveModel of type string
            () => RM.create<String>('x'),
            () => RM.create<String>('y'),
            () => RM.create<bool>(false),
          ],
          //Assign it to this StatesBuilder(),
          rmKey: rmKey,
          builder: (context, model) {
            return Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text('${model.state}'),
                RaisedButton(
                  child: Text('Concat string'),
                  onPressed: () {
                    //to get a model we use rmKey.get<T>()
                    if (rmKey.get<bool>().state) {
                      //If more than one model are of the same type,
                      //the default behavior is to get the first one
                      rmKey.get<String>().state += 'x';
                    } else {
                      //in this case rmKey.get<String>(1) means get the second ReactiveModel of type String
                      rmKey.get<String>(1).state += 'y';
                    }
                  },
                ),
                RaisedButton(
                  child: Text('Switch bool'),
                  onPressed: () {
                    print(rmKey.get<bool>().state);
                    rmKey.get<bool>().state = !rmKey.get<bool>().state;
                  },
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}
```

**Comment by amoslai5128** [comment]
> In the new version 2.1, to get the `reaciveModel `created in `observeMany `parameter, we use the rmKey paramter with the new `get` method.
> 
> Here is an example inspired from #83
> 
> ```dart
> class StateBuilderTest extends StatelessWidget {
>   //create a key
>   final rmKey = RMKey();
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Center(
>         child: StateBuilder(
>           observeMany: [
>             //two ReactiveModel of type string
>             () => RM.create<String>('x'),
>             () => RM.create<String>('y'),
>             () => RM.create<bool>(false),
>           ],
>           //Assign it to this StatesBuilder(),
>           rmKey: rmKey,
>           builder: (context, model) {
>             return Column(
>               mainAxisAlignment: MainAxisAlignment.center,
>               children: [
>                 Text('${model.state}'),
>                 RaisedButton(
>                   child: Text('Concat string'),
>                   onPressed: () {
>                     //to get a model we use rmKey.get<T>()
>                     if (rmKey.get<bool>().state) {
>                       //If more than one model are of the same type,
>                       //the default behavior is to get the first one
>                       rmKey.get<String>().state += 'x';
>                     } else {
>                       //in this case rmKey.get<String>(1) means get the second ReactiveModel of type String
>                       rmKey.get<String>(1).state += 'y';
>                     }
>                   },
>                 ),
>                 RaisedButton(
>                   child: Text('Switch bool'),
>                   onPressed: () {
>                     print(rmKey.get<bool>().state);
>                     rmKey.get<bool>().state = !rmKey.get<bool>().state;
>                   },
>                 ),
>               ],
>             );
>           },
>         ),
>       ),
>     );
>   }
> }
> ```

What if my RMKey is defined as Dynamic or other components? 

>           observeMany: [
>             //two ReactiveModel of type string
>             () => RM.create<Dynamic>('x'),
>             () => RM.create<Dynamic>('y'),
>             () => RM.create<ZoomController>(...),
>             () => RM.create<PointerDownEvent>(...),
>           ],

**Comment by GIfatahTH** [comment]
>Should I type as follow?
>
>rmKey.get(0).state += 123;
>rmKey.get(1).state += 'ABC';
>rmKey.get<ZoomController>.setState((xx) => ....);

YES 👍

**Comment by amoslai5128** [comment]
> > Should I type as follow?
> > `rmKey.get(0).state += 123;`
> > ` rmKey.get(1).state += 'ABC';`
> > ` rmKey.get<ZoomController>.setState((xx) => ....);`
> 
> YES 👍

Seems like I'm getting more familiar with States_Rebuilder  haha
Watching on every update 🥇

**Comment by amoslai5128** [comment]
Hey GIfatahTH,

I want to ask more about the relationship between Service & Domain layer in Clean_architecture, should service handles the main logic when transforms the data into action for UI? 
Let say I got a data set from server:

**Data Source Layer:** Code only handles the server connection, without parsing that data? (shouldn't directly contact to Domain?)

**Service Layer:** It's just like a bridge that directly contacts with Domain & Data Source, so it gets the data first and escapes the JSON parsing functions from Domain, but this layer also does the classification works, finally transforming it into a state.

**UI Layer:** Gets the state from Service Layer, and displays it.

Is that correct? I'm avoiding the data source do too much logic without the logic of server connection itself. Otherwise, it'd become a nightmare when switching other backend servers.
The domain layer just like the core, however, it's more like a data model?
I'm getting some confuse with the service layer....

**Comment by GIfatahTH** [comment]
Design patterns and clean architecture principles are here to help us to keep our code simple, readable, maintainable and testable. They are principles not rules. So whenever an idea make sense for you just use it provided it keeps your code simple, readable, maintainable and testable.

**Comment by amoslai5128** [comment]
> Design patterns and clean architecture principles are here to help us to keep our code simple, readable, maintainable and testable. They are principles not rules. So whenever an idea make sense for you just use it provided it keeps your code simple, readable, maintainable and testable.

Thank you! I will keep my code as clean as possible HAHA


> > > Cloud you offer a new example about Firestore based on example 007?
> > > It's more than happy with a user profile upload function or more complex practice!
> > 
> > 
> > I will do in the future.
> > > Btw, where happened to example 009?
> > > The example 010 should be 009, I Will fix it in the next release.
> 
> Dear GIfatahTH,
> I've finished a Firestore version of Example 009/010, instead of your Firebase Database, however, there's something I don't understand:
> 
> In data_source, xxx_respository.dart, you defined a Stream<List> countersStream() { } for return a stream. When I change it to Firestore, data doesn't automatically change, I've to use **broadcast stream**. It looks heavy...
> 
> Here is my code:
> I don't know is there a better alternative of using a **broadcast stream**?
> 
> ```
> final StreamController<List<Asset>> _assetsController =
>       StreamController<List<Asset>>.broadcast();
> 
> 
>   @override
>   Stream assetStream(String uid) {
>     // Register the handler for when the assets posts data changes
>     ref.document(uid).collection('Assets').snapshots().listen((snap) {
>       if (snap.documents.isNotEmpty) {
>         var posts = snap.documents
>             .map((doc) {
>               print('resp: ' + doc.data.entries.toString());
>               return Asset.fromMap(doc.data, doc.documentID);
>             })
>             .where((aseet) => aseet.name != null)
>             .toList();
> 
>         // Add the posts onto the controller
>         _assetsController.add(posts);
>       }
>     });
> 
>     // Return the stream underlying our _assetsController.
>     return _assetsController.stream;
>   }
> ```

BTW, I got some update here, I figure out I don't need to use a broadcast to make multiple subscriptions of the stream, I just yield them all LOL... 

````
  @override
  Stream<List<Asset>> assetStream(String uid) async* {
    yield* ref.document(uid).collection('Assets').snapshots().asyncMap(
        (snapshot) async => snapshot.documents
            .map((doc) => Asset.fromMap(doc.data, doc.documentID))
            .toList()
              //descending sort b, a
              ..sort((b, a) => a.createTime.compareTo(b.createTime)));
  }
```
Still, I don't know why the follow code didn't work as excepted by defining a **final snapshots** to let the code better looking:
```
  @override
  Stream<List<Asset>> assetStream(String uid) async* {
    final snapshots =
        ref.document(uid).collection('Assets').getDocuments().asStream(); 
    yield* ref.document(uid).collection('Assets').snapshots().asyncMap(
        (snapshot) async => snapshot.documents
            .map((doc) => Asset.fromMap(doc.data, doc.documentID))
            .toList()
              //descending sort b, a
              ..sort((b, a) => a.createTime.compareTo(b.createTime)));
  }
```

**Comment by GIfatahTH** [comment]
>I know it's out of this topic, however, will you plan to release a new article about the least changes >from the states_rebuilder


Here it is one:

https://medium.com/flutter-community/immutable-state-management-rebuilder-how-to-refactor-to-immutability-and-vice-versa-b9576d6744f2

**Comment by amoslai5128** [comment]
> > I know it's out of this topic, however, will you plan to release a new article about the least changes >from the states_rebuilder
> 
> Here it is one:
> 
> https://medium.com/flutter-community/immutable-state-management-rebuilder-how-to-refactor-to-immutability-and-vice-versa-b9576d6744f2

Oh WoW, reading on it!!

**Comment by amoslai5128** [comment]
Very good article! Now, I'm trying to do a complex application with states_rebuilder ;)

**Comment by amoslai5128** [comment]
> > I know it's out of this topic, however, will you plan to release a new article about the least changes >from the states_rebuilder
> 
> Here it is one:
> 
> https://medium.com/flutter-community/immutable-state-management-rebuilder-how-to-refactor-to-immutability-and-vice-versa-b9576d6744f2

Oh, the GitHub link inside this article seems dead.
https://github.com/GIfatahTH/states_rebuilder_shopper

**Comment by amoslai5128** [comment]
Dear GIfatahTH,

Here I have some suggestion for example 9 - immutable state todo app.  We all know that immutability does a good job but it'd be unfriendly for  beginners dealing with those exhaustive codes like:
```
//From Data Class / Todo_State
  @override
  bool operator ==(Object o) {
    if (identical(this, o)) return true;

    return o is Todo &&
        o.id == id &&
        o.complete == complete &&
        o.note == note &&
        o.task == task;
  }

  @override
  int get hashCode {
    return id.hashCode ^ complete.hashCode ^ note.hashCode ^ task.hashCode;
  }

  @override
  String toString() {
    return 'Todo(id: $id,task:$task, complete: $complete)';
  }
```

**However, with a VSCode Data Class extension + Equatable package, it looks much nicer :)**
The extension can also generate the annoying toJson/fromJson, copyWith() automatically.

VSCode Extension: https://marketplace.visualstudio.com/items?itemName=BendixMa.dart-data-class-generator
Equatable package: https://pub.dev/packages/equatable

```
//After the extends Equatable
  @override
  List<Object> get props => [id, complete, note, task];

  @override
  bool get stringify => true;
```

**Comment by amoslai5128** [comment]
I saw you define a photoUrl in the example 9 immutable. todo. Will it be a good idea to do an example of firebase storage for upload photos, docs (with upload progress status & downloaded Url)?
```
// domain/entities/user.dart
class User {
  .......
  final String photoUrl;
```

In an immutable way, I've tried to use your example to do that, however, the code looks unclean since I've to get the download Url into **Service_State.dart** before it's been CopyWith in **add_edit_screen.dart** .

Here is my current flow with the upload part:
upload multiple photos or docs.
  1.  UI - deleted an old & picked 2 new images, array[url, url(deleted), local, local]
  2. Service - only upload the local path images, and await repo returns new URLs
  3. Repo - standard Future from offical firebase storage doc
  4. Service - received a Storage Task Event from Repo, checking the status, and await the download URL
  5. UI - get status until download URLs has got, taking it to copyWith();

I know step 5 would be unnecessary since it should be done in Repo / Service level, however, I used your data_source/todo_repository.dart, there is a **List<Todo> _cashedTodos**. <---- Smart move but Idk how to use it :(

**Comment by GIfatahTH** [comment]
* To work with immutable object its is very helpful to use Equitable and kt_dart libraries.

* To show upload or download progress status, you have to have two variables:
1- total size of the file,
2- current uploaded or downloaded size.

Usually libraries provides a stream to listen to get the current size.

If this is the case, I follow this pattern:

1- Interface
```dart
abstract class IUploaderRepository {
//.. other stuff

Stream<dounble> progress(int totalSize);
}
```
2- Service
```dart
class UploaserService{
//.. other stuff

 Stream<dounble> progress(int totalSize){
   return uploaderRepository.progress(totalSize);
 }
}
```
3- UI
```dart
....
RaisedButton(
onPressed: (){
    // use file picker to get the file ptath
    // get the file total size
    int totalSize = .....;
     // shwoDialog
     showDiaglog(
         context : context,
         builder : (context){
         ..... 
         StateBuilder<double>(
                observe : ()=> RM.get<UpdouderService>().stream((s,_)=>s.progress(totalSize)).
                //You can automatically cloze the dialog after finishing the upload
                onSetState : (context, progressRM){
                    if(progressRM.state >=100){
                       RM.navigator.pop();
                   }
                 },
                builder: (context , progressRM){
                   //  Display some thing
                }
           )
       }
}
)
```


It remains the data_source part. This is the least important part because it is an implementation detail that can be changed at any time without affecting our application.

Simply choose the provider of your choice (Firebase store for example) and implement the IUploader interface.

**Comment by GIfatahTH** [comment]
The answer starts by known the relation between the two entities. is it one-to-many (one Shop can have many products or in the other sense one Product can be in many shops) or is the relation many-to-many?

What do you think?

**Comment by amoslai5128** [comment]
> The answer starts by known the relation between the two entities. is it one-to-many (one Shop can have many products or in the other sense one Product can be in many shops) or is the relation many-to-many?
> 
> What do you think?

I think one shop can have many products, one to many. Thus, option 2 would be suitable, right?
And there's another question, should I put these two together in single service rather than separate out each of them for a different state? Such as ShopService, ProductService.dart?

**Comment by amoslai5128** [comment]
OMG, what a breaking changes in version 3.0, hehe, Functional injection looks very cool

**Comment by GIfatahTH** [comment]
>what a breaking change in version 3.0

Although, global functional injection is a new feature, old apps written with the `Injector `approach still work with v.3.0. 

There are two **_minor breaking changes_** in v3.0 :
`StateBuilder `only rebuilds when notification has data. 
So one that has a code like this : 
```dart
StateBuilder(
 observer : () => modelRM,
 builder: (context, modelRM){
 return Text (myModel.state);
}
)
```

will not notice any change and performance is better because we are minimizing the unnecessary rebuilds (onWaint and hasError statuses).

BUT one that writes something like this:

```dart
StateBuilder(
 observer : () => modelRM,
 builder: (context, modelRM){
  if (modelRM.isWaiting){
  return SomeWaitingWidget();
 }
 return Text (myModel.state);
}
)
```
Will notice that `SomeWaitingWidget`is not displayed when the `modelRM `is waiting.

To Solve: 

either use the `shouldRebuild `parameter:
```dart
StateBuilder(
 observer : () => modelRM,
 shouldRebuild : (_)=> true,
 builder: (context, modelRM){
  if (modelRM.isWaiting){
  return SomeWidget();
 }
 return Text (myModel.state);
}
)
```

or use `WhenBuilderOr `instead of `StateBuilder `:
```dart
WhenBuilderOr(
 observer : () => modelRM,
 builder: (context, modelRM){
  if (modelRM.isWaiting){
  return SomeWidget();
 }
 return Text (myModel.state);
}
)
```

The other breaking change is that the API of `StateWithMixinBuilder `is changed and I think the `StateWithMixinBuilder `is not widely used.

> However, any performance/security difference between old and new

the global functional injection is more secure and has more performance.

By the way, I think it is time to close this issue, and open new issues for any question or comment under related opened issues.

**Comment by amoslai5128** [comment]
Thank you so much for the work.
Anything that I can contribute? Like formatting the readme, or something else.

**Comment by amoslai5128** [comment]
Hey, I've improve the readme formating on your v3.0.0 branch, and I cannot pull the request.

**Comment by amoslai5128** [comment]
That's all right, I pulled.
