### ISSUE TITLE
Reactive model(extends StatesRebuilder) is null in StateBuilder

### ISSUE THREAD

**Issue by cosinus84** [GIfatahTH/states_rebuilder#68]
Hello, maybe I didn't understand but, service is null
```
    return StateBuilder<AuthService>(
        models: [Injector.get<AuthService>()],
        child: child,
        builderWithChild: (context, service, child) {})
```
AuthService extends StatesRebuilder. Using AuthService model = Injector.get<AuthService>(); it works ok, but service is still null.

Thanks

**Comment by kitesoft** [comment]
chnage to : 
Injector.getAsReactive<AuthService>()

**Comment by cosinus84** [comment]
Even if it extends StatesRebuilder? is this ok ?

**Comment by GIfatahTH** [comment]
As AuthService extends StatesRebuilder, the service parameter is always null. Use this
```dart
 return StateBuilder<AuthService>(
        models: [Injector.get<AuthService>()],
        child: child,
        builderWithChild: (context, _, child) {
        final service =Injector.get<AuthService>();

})
```
