### ISSUE TITLE
How to deal with the Flutter Stepper Weight when Injecting with a ReactiveModel instead of statefulweight? 

### ISSUE THREAD

**Issue by amoslai5128** [GIfatahTH/states_rebuilder#70]
How to deal with the Flutter Stepper Weight when Injecting with a ReactiveModel instead of StatefulWeight? 

**final currentStep = ReactiveModel.create(0);**

//Body

```
 StateBuilder(
       models: [currentStep],
       builder: (_, __) => Stepper(
         type: StepperType.vertical,
         controlsBuilder: (context,
             {VoidCallback onStepContinue, VoidCallback onStepCancel}) {
           return Row(
               ....................
            // Null child, I call my customized buttons
           );
         },
         currentStep: currentStep.state,
         onStepContinue: stepContinue(),
         onStepCancel: stepCancel(),

```

but I realized that nothing will be reacted after the **currentStep.state** changed, and the index of step didn't follow any updates. However, but original setState(), it works well.

The reason I want to drop Stepper into ReactiveModel to manage the states is I plan to turn the whole class to a **StatelessWeight**.

**Comment by GIfatahTH** [comment]
It would be very helpful if you add a representative short example that reproduces the issue. Here is what I tried;

```dart
class StepperPage extends StatelessWidget {
  final _indexRM = ReactiveModel.create(0);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: StateBuilder(
        models: [_indexRM],
        builder: (_, __) {
          return _tabStep();
        },
      ),
    );
  }

  Widget _tabStep() => Stepper(
        steps: [
          Step(
            title: Text("First"),
            content: _indexRM.value == 0 ? Text("This is the first step.") : Container(),
          ),
          Step(
            title: Text("Second"),
            content: _indexRM.value == 1 ? Text("This is the second step.") : Container(),
          ),
          Step(
            title: Text("Third"),
            content: _indexRM.value == 2 ? Text("This is the third step.") : Container(),
          ),
        ],
        currentStep: _indexRM.value,
        onStepTapped: (index) {
          _indexRM.setValue(() => index);
        },
      );
}
```
Actually, I used to run tests for such codes and not trying them on device emulator.

The following test works for me.

```dart
  testWidgets('Stepper_test', (WidgetTester tester) async {
    await tester.pumpWidget(MaterialApp(home: StepperPage()));
    //first
    expect(find.text('First'), findsOneWidget);
    expect(find.text('This is the first step.'), findsOneWidget);
    expect(find.text('Second'), findsOneWidget);
    expect(find.text('This is the second step.'), findsNothing);
    expect(find.text('Third'), findsOneWidget);
    expect(find.text('This is the third step.'), findsNothing);

    //tap on Second Step;
    await tester.tap(find.text('Second'));
    await tester.pump();
    expect(find.text('This is the first step.'), findsNothing);
    expect(find.text('This is the second step.'), findsOneWidget);
    expect(find.text('This is the third step.'), findsNothing);

    //tap on Third Step;
    await tester.tap(find.text('Third'));
    await tester.pump();
    expect(find.text('This is the first step.'), findsNothing);
    expect(find.text('This is the second step.'), findsNothing);
    expect(find.text('This is the third step.'), findsOneWidget);
  });
```
This test passes, try it with your emulator and feed me back!

**Comment by amoslai5128** [comment]
OMG, thank you for your reply.
I also found a solution by changing it:

From:
final currentStep = ReactiveModel.create(0);

To:
ReactiveModel<int> currentStepRM = ReactiveModel<int>.create(0);

**Comment by amoslai5128** [comment]
I'm sorry my code is a bit Boilerplate, if there's any for the improvement, please tell me more about that

**Comment by amoslai5128** [comment]
The problem updated

**Comment by amoslai5128** [comment]
#UPDATE

Oh, I've found that the problem is from 
` 
RaisedButton(
              child: new Text(
                'Next',
                style: new TextStyle(color: Colors.white),
              ),
              onPressed: () =>
                  {stepContinue(), FocusScope.of(context).unfocus()},
              color: Colors.transparent,
            ),
`
**FocusScope.of(context).unfocus()**
Since I want to close the keyboard after the Step moves next. How should I do with this? 

I

**Comment by amoslai5128** [comment]
> #UPDATE
> 
> Oh, I've found that the problem of keyboard re-focusing will affect the index state, it's from
> 
> ```
> RaisedButton(
>               child: new Text(
>                 'Next',
>                 style: new TextStyle(color: Colors.white),
>               ),
>               onPressed: () =>
>                   {stepContinue(), FocusScope.of(context).unfocus()},
>               color: Colors.transparent,
>             ),
> ```
> 
> **FocusScope.of(context).unfocus()**
> Since I want to close the keyboard after the Step moves next. Somehow I may loop back and edit again the pervious step.
> How should I do with this?
> 
> I've successfully turned it into a statelessWeight, I love StatesRebuilder so much!!!!!

I know how to solve....
Solution:  add `` !FocusScope.of(context).hasPrimaryFocus
                    ? FocusScope.of(context).unfocus()
                    : null``

```
RaisedButton(
              child: new Text(
                'Next',
                style: new TextStyle(color: Colors.white),
              ),
              onPressed: () => {
                stepContinue(),
                !FocusScope.of(context).hasPrimaryFocus
                    ? FocusScope.of(context).unfocus()
                    : null
              },
              color: Colors.transparent,
            ),

```
