### ISSUE TITLE
Must be missing something obvious...

### ISSUE THREAD

**Issue by jmwatte** [GIfatahTH/states_rebuilder#73]
Just a question...
If I click onPressed, to get the nextnumber()...OK... thenumber gets updated in the UI.
But on the longpressed()... spitTheNumbers()... thenumber gets udated but not on the UI.
So the number gets udated but the number in the async-method not on the UI. 
I don't see it. How should I go about solving this?
Hope it is OK to ask this here.

thx for any insight and help.

`
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

class PlayWithInt {
  PlayWithInt(
      {this.end: 100,
      this.thenumber: 50,
      this.direction: -1,
      this.iCanSpit: true});

  int direction; //count down with -1 or count up +1
  int end; //maximum of number
  bool iCanSpit; //pauzes spitTheNumbers
  int thenumber; //the chosen number

//changes thenumber after delay
  spitTheNumbers() async {
    while (thenumber <= end && thenumber >= 0 && iCanSpit) {
      await Future.delayed(Duration(milliseconds: 200));
      print("instream: $thenumber");
      if (thenumber + direction != end && thenumber - direction != 0) {
        changeNumberbyOne(addnumber: direction);
      }
    }
  }

//adds [addnumber] to the thenumber
  changeNumberbyOne({addnumber: 1}) {
    thenumber = thenumber + addnumber;
    print("inchangenumberbyone: $addnumber/$thenumber");
  }

}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Injector(
      inject: [
        Inject<PlayWithInt>(() => PlayWithInt()),
      ],
      builder: (_) {
        final playWithInt = Injector.getAsReactive<PlayWithInt>();
        return Scaffold(
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  'You have pushed the button to this value:',
                ),
                StateBuilder(
                  models: [playWithInt],
                  builder: (_, __) {
                    return Text('${playWithInt.value.thenumber}');
                  },
                ),
              ],
            ),
          ),
          floatingActionButton: Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: <Widget>[
              GestureDetector(
                onLongPress: () {
                  playWithInt.setState((state) {
                    return rollBackPlease(playWithInt);
                  });
                },
                onLongPressUp: () {
                  playWithInt.setState((state) => state.iCanSpit = false);
                },
                child: FloatingActionButton(
                  onPressed: () {
                    playWithInt.setState((state) => state.changeNumberbyOne());
                    print('${playWithInt.value.thenumber}');
                  },
                  child: Icon(Icons.arrow_forward),
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  ReactiveModel<PlayWithInt> rollBackPlease(
      ReactiveModel<PlayWithInt> playWithInt) {
    return playWithInt
      ..setState((state) => state.iCanSpit = true)
      ..setState((state) => state.direction = -1)
      ..setState((state) => state.spitTheNumbers());
  }
}
`

**Comment by GIfatahTH** [comment]
Please try this:
```dart
class PlayWithInt {
  PlayWithInt(
      {this.end: 100,
      this.thenumber: 50,
      this.direction: -1,
      this.iCanSpit: true});

  int direction; //count down with -1 or count up +1
  int end; //maximum of number
  bool iCanSpit; //pauzes spitTheNumbers
  int thenumber; //the chosen number

//changes thenumber after delay
  spitTheNumbers() async {
    while (thenumber <= end && thenumber >= 0 && iCanSpit) {
      //You have to notify the widget for each while loop
      await ReactiveModel<PlayWithInt>().setState(
        (_) async {
          await Future.delayed(Duration(milliseconds: 200));
          print("instream: $thenumber");
          if (thenumber + direction != end && thenumber - direction != 0) {
            changeNumberbyOne(addnumber: direction);
          }
        },
      );
    }
  }

//adds [addnumber] to the thenumber
  changeNumberbyOne({addnumber: 1}) {
    thenumber = thenumber + addnumber;
    print("inchangenumberbyone: $addnumber/$thenumber");
  }
}

void main() => runApp(MaterialApp(home: MyHomePage()));

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Injector(
      inject: [
        Inject(() => PlayWithInt()),
      ],
      builder: (_) {
        final playWithInt = Injector.getAsReactive<PlayWithInt>();
        return Scaffold(
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  'You have pushed the button to this value:',
                ),
                StateBuilder(
                  models: [playWithInt],
                  builder: (_, __) {
                    return Text('${playWithInt.value.thenumber}');
                  },
                ),
              ],
            ),
          ),
          floatingActionButton: Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              GestureDetector(
                onLongPress: () {
                  playWithInt.state
                    ..iCanSpit = true
                    ..direction = -1
                    ..spitTheNumbers();
                },
                onLongPressUp: () {
                  playWithInt.setState((state) => state.iCanSpit = false);
                },
                child: FloatingActionButton(
                  onPressed: () {
                    playWithInt.setState((state) => state.changeNumberbyOne());
                    print('${playWithInt.value.thenumber}');
                  },
                  child: Icon(Icons.arrow_forward),
                ),
              ),
            ],
          ),
        );
      },
    );
  }
}
```

**Comment by jmwatte** [comment]
Wonderfull, didn't realize that you could call the ReactiveModel from within the Model... Russian dolls...
Learned that one. On to more experimenting.
Thanks.
