### ISSUE TITLE
Inject.interface abstract class with parameter type

### ISSUE THREAD

**Issue by atoumbre** [GIfatahTH/states_rebuilder#74]
Hello.

Let me start by giving a kudos you for this great job.

Meanwhile, Inject.interface seems not working for abstract class parameter type like 

class A<T> implements B<T>{
...
}

**Comment by GIfatahTH** [comment]
Thank you very much for your kind comment.
I will try to see. If you can find a simple example that reproduces the issue, that would be helpful.

**Comment by atoumbre** [comment]
Hello. 

Sorry, No issue there. I needed to pass the abstract class as type parameter to Inject.interface.

Thanks
