### ISSUE TITLE
Like `FutureBuilder` and `StreamBuilder` but more powerful. (New featrues)

### ISSUE THREAD

**Issue by GIfatahTH** [GIfatahTH/states_rebuilder#75]
Fluter core API has `FutureBuilder` and `StreamBuilder` to handle futures and streams respectively.

```dart
class Foo {
    Future<userID> login() async {
        await api.login(token);
    }
}
```
In the UI and after instantiating the Foo object using our dependence injection (Global instance, InheretedWidget, or Provider, get_it, ..), we use FutureBuilder

```dart
FutureBuilder(
    future : foo.login();
    builder : (context, snapshot){
        if(snapshot.isWaiting){
            return SplashScreen();
        }
        if(snapshot.hasError){
            return Text('An Error has happened'),
        }
        if(snapshot.hasData){
            return Text('${snapshot.data}');    
        }
    }
)
```

In states_rebuilder world, after injection the Foo object using Injector, use can use one of the availbale wdiget:
* `StateBuilder`, the default widget listener;
* `WhenRebuilder`, to exhaustively go throw all the available state status (onIdle, onWaiting, onError, onData);
* `WhenRebuilderOr`, to selectively go throw any of the available state status:
* `OnSetStateListener` to execute side effects.

## before (actual version v.1.14.3):
```dart
WhenRebuilder<Foo>(
    models : [ReactiveModel<Foo>()],
    //we used the initState to trigger the future
    iniState : (ctx, fooRM) => fooRM.setState((s)=>s.login()),
    onIdle : ()=> Text('Welcoming Screen'),
    onWaiting : ()=> SplashScreen(),
    onError: (e)=> Text('An Error has happened'),
    onDate : (fooRM){
        return Text('${fooRM.state.userID}');
    }
)
```
Or; by creating a future ReactiveModel form the login method
```dart
WhenRebuilder<Foo>(
    models : [ReactiveModel.future<int>(Injector.get<Foo>().login())],
    onIdle : ()=> Text('Welcoming Screen'),
    onWaiting : ()=> SplashScreen(),
    onError: (e)=> Text('An Error has happened'),
    onData : (userIdRM){
      return Text('${userIdRM.value}');
    }
)
```
## after next update (1.15.0)

```dart
WhenRebuilder<Foo>(
    models : [RM.getFuture<Foo,int>((f)=> f.login())],
    onIdle : ()=> Text('Welcoming Screen'),
    onWaiting : ()=> SplashScreen(),
    onError: (e)=> Text('An Error has happened'),
    onData : (userId){
       return Text('${userIdRM}');
    }
)
```
in `RM.getFuture<Foo,int>((f)=> f.login())` the first generic type (Foo) defines the type of the injected model, and the second generic type (int) defined the resulting type of the value resolved by the future.

The same thing is obtained for stream using `RM.getStream`

```dart
WhenRebuilder<Foo>(
    models : [RM.getStream<Foo,int>((f)=> f.fireStoreStream())],
    onIdle : ()=> Text('Welcoming Screen'),
    onWaiting : ()=> SplashScreen(),
    onError: (error)=> Text('An Error has happened'),
    onData : (userId){
       return Text('${userId}');
    }
)
```

As I said you can use `StateBuilder`, `WhenRebuilderOr`, `OnSetStateListener`.

**Comment by amoslai5128** [comment]
When will this new release go live? Can't wait for it!

**Comment by GIfatahTH** [comment]
@amoslai5128  I am happy that you find the library so useful.

Usually, before publishing any new feature, I try to test it, use it in a somewhat complex example and track its performance issues. That said, and as we all know Flutter is performant by default, in spite of the fact that `build ()` can be called frequently during the life cycle of the widget. We must be prepared for unwanted rebuilds.

In the case of `FutureBuilder` we read this caution in the Flutter docs:

> The future must have been obtained earlier, .....
> If the future is created at the same time as the FutureBuilder, 
> then every time the FutureBuilder's parent is rebuilt, the asynchronous task will be restarted.

In many tutorials I see something like this :
```dart
FutureBuilder(
    future : foo.asyncMethod();
    builder : (context, snapshot){

    }
)
```
This is not good, because each time the build process is invoked the async method is called and the builder of the `FutureBuilder` is invoked.

With states_rebuilder the same unwanted behavior is expected: 

```dart
StateBuilder(
    models : [RM.getFuture<Foo,void>((f)=> f.asyncMethod())],
    builder :(context, rm){

    }
)
```
states_rebuilder is a little better, when a parent of `StateBuilder` is rebuilding the builder of `StateBuilder` will not be called, but still the async method will be called.

To remedy this, the `models` parameter should be of void callback type:

```dart
StateBuilder(
    models : [() => RM.getFuture<Foo,void>((f)=> f.asyncMethod())],
    builder :(context, rm){

    }
)
```
By simply adding `() => ` we gain performance and the future is entirely controlled by the `StateBuilder` widget and will never be called by an unwanted rebuilds.

In this context, I intended to add two parameters:
* `observe` which is of type `StatesRebuilder Function()`. to register to one observable model.
* `observeMany` which is of type `List<StatesRebuilder Function()>`. to register to more than one observable model.

**justification of the chosen names:**
* As states_rebuilder use the observer pattern, `observe` is more descriptive than `models`.
* both are verbs, because verbs are used for actions and callbacks are actions.
* In most cases one will subscribe to one observable model, so it is convenient to use `observe: ()=> ..` instead of `observe: [()=> ...]`

With this new parameters : 

```dart
WhenRebuilder<Foo>(
    observe : ()=> RM.getStream<Foo,int>((f)=> f.fireStoreStream()),
    onIdle : ()=> Text('Welcoming Screen'),
    onWaiting : ()=> SplashScreen(),
    onError: (error)=> Text('An Error has happened'),
    onData : (userId){
       return Text('${userId}');
    }
)
```
even with other types of `ReactiveModel`, `observe` is more efficient than `models`:

```dart
WhenRebuilder<Foo>(
    //old
    //models : [RM.get<Foo>()], // this get will be called for each parent rebuild.
    //new
    observe : () => RM.get<Foo>(),//this get is called once at the time of creation
    onIdle : ()=> Text('Welcoming Screen'),
    onWaiting : ()=> SplashScreen(),
    onError: (error)=> Text('An Error has happened'),
    onData : (foo){
       ...
    }
)
```
Think of the performance difference:
* with `models : [RM.get<Foo>()]` the `get` method is called at the time of the creation and each time the parent widget rebuilds (hot restart, window sizing in web, routing, ...). If the invoked method does heavy calculation the performance loose is critical.
* with `observe : ()=> RM.get<Foo>()` the `get` method is called only once at the time of creation.

`observe` and `observeMany` are experimental, and the `models` is maintained and may be deprecated in a future release.

**Comment by amoslai5128** [comment]
> @amoslai5128 I am happy that you find the library so useful.
> 
> Usually, before publishing any new feature, I try to test it, use it in a somewhat complex example and track its performance issues. That said, and as we all know Flutter is performant by default, in spite of the fact that `build ()` can be called frequently during the life cycle of the widget. We must be prepared for unwanted rebuilds.
> 
> In the case of `FutureBuilder` we read this caution in the Flutter docs:
> 
> > The future must have been obtained earlier, .....
> > If the future is created at the same time as the FutureBuilder,
> > then every time the FutureBuilder's parent is rebuilt, the asynchronous task will be restarted.
> 
> In many tutorials I see something like this :
> 
> ```dart
> FutureBuilder(
>     future : foo.asyncMethod();
>     builder : (context, snapshot){
> 
>  .......................

Thank you for the kind reply. Speaking of which, should it be a better performance by adding a **watch:**  inside the setState, StateBuilder, WhenRebuilder? 

Because your document mentioned that watch is for targeting a part of the state, for example:
Counter{
 String id;
 int num;
 Color color;
 //Initializing by constructor...
}
So, by default the watch: is not been set, if I setState only changed the color here, the StateBuilder will get a full notification?

**Comment by GIfatahTH** [comment]
`setState`, and all the observer widget have a `watch` parameter to determine the part of the state to rebuild when it changes.

To control the widget rebuild, you can :
- `watch`,
- `tag` and `filterTags` ,
- `seed` for new reactive models,
- create a local reactive model from primitives, objects, future or streams.
