### ISSUE TITLE
rebuild on external callback

### ISSUE THREAD

**Issue by FlorianKaufmann** [GIfatahTH/states_rebuilder#77]
Hello,

Thank you for your amazing library! I'm using a mix of clean_architecture_dane_mackier_app and clean_architecture_firebase_login for my application and love the abstraction level it offers.

I would like to know if it is possible to update the ui as data comes from data_source layer ( for me it is ble data). I have a service that exchange with the ble stack. I would like the ble stack to notify the service such that the ui refresh on incoming data.

Hope the question is not dumb.

Greetings

**Comment by amoslai5128** [comment]
Have you tried the Stream? Target component will watch and rebuild in real-time after any notifying from that stream.

You can see my another issue, I'm using a broadcast() stream to handle the stream from data_source, then each time Firestore returns a change will affect the application UI too. I think it's suitable for your case.
After the data_source, you also need to write an Injector.get stream to your page

https://github.com/GIfatahTH/states_rebuilder/issues/67

**Comment by FlorianKaufmann** [comment]
Haven't tried using stream. I'll give it a look. Seems wrong to shortcut the service layer tho.

**Comment by GIfatahTH** [comment]
@FlorianKaufmann  .
In the architecture I used, the data_source layer must not communicate directly with the UI layer part. It is the role of the application service layer to orchestrate the flow of data between different layers.
As @amoslai5128  suggested, streams are the best candidate here, you define an interface for the stream in the service layer, the data_source implement the interface, and the service class should expose the stream to the UI to subscribe to it.
in the example https://github.com/GIfatahTH/states_rebuilder/tree/master/examples/010-clean_architecture__multi_counter_realtime_firebase

the interface is:
```dart
Stream<List<Counter>> countersStream();
```

the data_source implementation is :
1- fire base implementation:
```dart
 @override
  Stream<List<Counter>> countersStream() {
    Stream<List<Counter>> stream;

    //Map the onValue stream to return a stream of list of counters
    stream = databaseReference.onValue.map((event) {
      Map<dynamic, dynamic> values = event.snapshot.value;
      if (values == null) {
        return [];
      }
      Iterable<String> keys = values.keys.cast<String>();

      List<Counter> counters = keys
          .map((key) => Counter(id: int.parse(key), value: values[key]))
          .toList();

      return counters ?? [];
    });

    return stream;
  }
```
2- fake impementation
```dart
  @override
  Stream<List<Counter>> countersStream() {
    return _controller.stream;
  }
```

in the servcie class  I refered to the stream via the interface
```dart
  Stream<List<Counter>> countersStream() {
    return _counterRepository.countersStream();
  }
```
in the UI layer I consumed the stream and inject it the the UI widget tree.

```dart
Inject.stream(() => Injector.get<CountersService>().countersStream());
```

**Comment by FlorianKaufmann** [comment]
This is so easy. Thanks for the crystal clear response.
