### ISSUE TITLE
Open more doors using the magic of Reactive Model Key [new feature]

### ISSUE THREAD

**Issue by GIfatahTH** [GIfatahTH/states_rebuilder#79]
`states_rebuilder` is based on the concepts of `ReactiveModel`. 

A `ReactiveModel` can be injected and used when needed anywhere in the widget tree.

To get an injected model we use:
```dart
final modelRM = Injector.getAsReactive<T>();
// or more concisely:
final modelRM = ReactiveModel<T>();
// or even more concisely (since next 1.15.0 release):
final modelRM = RM.get<T>();
```
In another hand, `ReactiveModel` can be created locally:
 
```dart
//creating a reactive model from a boolean value
final switchRM = ReactiveModel<bool>.create(true);
// or more concisely (since next 1.15.0 release)
final switchRM = RM.create<bool>(true);
```
> with `states_rebuilder` we can locally create `ReactiveModel` from primitive values, objects, futures or streams.

To consume the created `ReactiveModel`, we use one of the available widget observers : `StateBuilder`, `WhenRebuilder`, `WhenRebuilderOr` or `OnSetStateListener`.

Let's display a Flutter Switch button:

```dart
Scaffold(
    appBar: AppBar(
        title: StateBuilder<bool>(
        observe: () => RM.create(true),
        builder: (ctx, switchRM) {
            return Switch(
                value: switchRM.value,
                onChanged: (value) {
                    switchRM.value = value;
                },
            );
        },
        ),
    ),
    body: Container(),
)
```

One may argue that we can use a simple `StatefulWidget`!. Yes, but notice that with `states_rebuilder` the only part that rebuilds is the `Switch` button.

Let's complicate the situation a bit. Let's say we want two switches one on the appBar and the other in the bottomSheet and we want the two switches to be synchronized. Let's add a button in the center of the body to toggle the switches.

If using `StatefulWidget`, we must rebuild the entire Scaffold to fulfill the requirements.

With `states_rebuilder` and using the new concept of reactive model keys, we can limit the rebuild to the switches only.

```dart
Widget build(BuildContext context) {
//define a reactive model key with initial value of true
final switchKey = RMKey(true);
return MaterialApp(
   home: Scaffold(
    appBar: AppBar(
        title: StateBuilder<bool>(
        observe: () => RM.create(true),
        //assign the key to this StateBuilder widget
        rmKey: switchKey,
        builder: (ctx, switchRM) {
            return Switch(
            value: switchRM.value,
            onChanged: (value) {
                switchRM.value = value;
            },
            );
        },
      ),
    ),
    body: Center(
        child: RaisedButton(
        child: Text('Toggle'),
        onPressed: () {
            //set the value and notify listeners
            switchKey.value = !switchKey.value ;
        },
      ),
    ),
    bottomSheet: StateBuilder<bool>(
        //subscribe the this StateBuilder using the defined key
        observe: () => switchKey,
        builder: (ctx, switchRM) {
        return Switch(
            value: switchRM.value,
            onChanged: (value) {
               switchRM.value = value;
            },
        );
      },
    ),
  ),
 );
}
```

Similar to global keys in Flutter, the reactive model key (`RMKey`) is used to control a `state_builder` observer widget from outside.

```dart
final switchKey = RMKey(true);
```
Here we created a `ReactiveModel` key and initialize it to be true. 

```dart
    title: StateBuilder<bool>(
    observe: () => RM.create(true),
    //assign the key to this StateBuilder widget
    rmKey: switchKey,
    builder: (ctx, switchRM) {
        return Switch(
        value: switchRM.value,
        onChanged: (value) {
            switchRM.value = value;
        },
        );
    },
    ),
```

The `StateBuilder` has a new parameter called `rmKey` that receives the defined `RMKey`.

By assigning an RM Key to a `StateBuilder` widget, we can notify it to rebuild from outside the builder of the `StateBuilder` widget.

`RMKey` inherits all The `ReactiveModel` functionality, such as `setState`, `setValue`, and `state`, `value` getters.

```dart
RaisedButton(
    child: Text('Toggle'),
    onPressed: () {
        //set the value and notify listeners
        switchKey.value = !switchKey.value ;
    },
),
```
You can even subscribe widgets to a `RMKey` so that wehner the `RMKey` or the `ReactiveModel` associated with it emits a notification, the subscribed widget will rebuild:

```dart
bottomSheet: StateBuilder<bool>(
    //subscribe the this StateBuilder using the defined key
    observe: () => switchKey,
    builder: (ctx, switchRM) {
    return Switch(
        value: switchRM.value,
        onChanged: (value) {
            switchRM.value = value;
        },
    );
    },
),
```

`RMKey` has a new functionality called refresh. Let create a future as we used in the example above.

```dart
//createa RMKey
final fetchProductsKey = RMKey();
//..
StateBuilder(
    models : [() => RM.getFuture<Foo,void>((f)=> f.fetchProducts())],
    //associate it with this widget
    rmKey: fetchProductsKey
    builder :(context, rm){

    }
)
```
When the `StateBuilder` widget is inserted in the widget tree, the `fetchProducts()` is invoked to get the list of products and the builder closure of the `StateBuilder` widget will be called once the future resolves.

What if we want to refresh the list of products and call `fetchProducts()` again.

With the concept of `RMKey`, we just call the builtin refresh method:

```dart
RaisedButton(
    child: Text('refresh products'),
    onPressed: () {
        fetchProductsKey.refresh();
    },
```

If you have a counter with `RMKey`, when `refresh()` is called the counter is reset to its initial value.

**Comment by jhoogstraat** [comment]
Do I need provide a ReactiveModel to the StateBuilder when I provide a RMKey?
See the following examples:
```dart
final _buttonEnabledState = RMKey(true);
StateBuilder(
    observe: () => _buttonEnabledState,
    builder: (context, state) => LoginButton(isEnabled: state.value)
)
```

Vs. this:
```
final _buttonEnabledState = RMKey(true);
StateBuilder(
    observe: () => RM.create(true),
    rmKey: _buttonEnabledState
    builder: (context, state) => LoginButton(isEnabled: state.value)
)
```

**Comment by GIfatahTH** [comment]
The first example seems to work until a parent widget updates.
