### ISSUE TITLE
easier way to solve this?

### ISSUE THREAD

**Issue by jmwatte** [GIfatahTH/states_rebuilder#80]
`import 'package:flutter/material.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

class AppDataBase {
  var packNames = ["pack1", "pack2", "pack3"];
  SellLyric selectedlyric = SellLyric()..inpacks = "pack5";
}

class SellLyric {
  var inpacks;
}

class LyricsCopy {
  var inpacks = "pack1";
}

class AddToPackScreen extends StatelessWidget {
  final contr = TextEditingController();

  @override
  Widget build(BuildContext context) {
    var lyric = Injector.getAsReactive<LyricsCopy>();
    var store = Injector.getAsReactive<AppDataBase>();
    lyric.state.inpacks = store.state.selectedlyric.inpacks;//set the initiale state of lyric so as not to rebuild
    return InsideAddToPackScreen();

  }
}

class InsideAddToPackScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var lyric = Injector.getAsReactive<LyricsCopy>(context: context);
    var store = Injector.getAsReactive<AppDataBase>(context: context);
    return Scaffold(
      appBar: AppBar(
        title: Text(lyric.state.inpacks.toString()),
        leading: IconButton(
          icon: Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context, lyric.value),
        ),
      ),
      body: Column(children: <Widget>[
        Expanded(
          child: ListView.builder(
            itemCount: store.state.packNames.length,
            itemBuilder: (BuildContext context, int index) {
              return ListTile(
                  onTap: () {
                    lyric.state.inpacks
                            .split(" ")
                            .contains(store.state.packNames.elementAt(index))
                        ? lyric.setState((state) {
                            var b = state.inpacks.split(" ");
                            b.removeWhere((value) =>
                                value ==
                                store.state.packNames.elementAt(index));
                            var v = b.join(" ");
                            print("1" + v);
                            return state.inpacks = v;
                          })
                        : lyric.setState((state) {
                            var b = state.inpacks.split(" ");
                            b.add(store.state.packNames.elementAt(index));
                            var v = b.join(" ");
                            print("2" + v);
                            return state.inpacks = v;
                          });
                  },
                  title: lyric.state.inpacks.split(" ").contains(
                              store.state.packNames.elementAt(index)) ==
                          true
                      ? Text(
                          store.state.packNames.elementAt(index).toString(),
                          style: TextStyle(backgroundColor: Colors.green),
                        )
                      : Text(store.state.packNames.elementAt(index).toString(),
                          style: TextStyle(backgroundColor: Colors.red)));
            },
          ),
        ),
        TextField(
          onSubmitted: (value) => lyric.setState((state) {
            var b = state.inpacks.split(" ");
            if (b.contains(value) == false) b.add(value);
            print("3" + b.join(" "));
            if (store.state.packNames.contains(value) == false)
              store.state.packNames.add(value);
            return state.inpacks = b.join(" ");
          }),
        ),
      ]),
    );
  }
}
`

problem: I want to initialize the value of 'lyric' with a value from 'store'. But when I do that inthe buildmethod it gets reset to those values so my solution was to put the initialising in a toplevelwidget or -look at it from another way - extract the widget.

Question: is there a way to initialise lyric in another way so I dan't have to make sub/top widgets to get that seperation?

thx for your library. It's fun trying it out.

**Comment by GIfatahTH** [comment]
Thanks fro trying the library.
first I do not see the generic type in your getAsReactive methods
```dart
    var lyric = Injector.getAsReactive();
    var store = Injector.getAsReactive();
```
this should throw.
This is the correct code.
```dart
    var lyric = Injector.getAsReactive<SellLyric>();
    var store = Injector.getAsReactive<AppDataBase>();
```
If you want to initialize any value for one time, use iniState callback that are available in Injector, StateBuilder, WhenRbuilder, WhenRebuilderOr and OnSetStateListener widgets

```dart
import 'package:flutter/material.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

class AppDataBase {
  var packNames = ["pack1", "pack2", "pack3"];
  SellLyric selectedlyric = SellLyric()..inpacks = "pack5";
}

class SellLyric {
  var inpacks;
}

class LyricsCopy {
  var inpacks = "pack1";
}

class Issue80 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Injector(
        inject: [
          Inject(() => AppDataBase()),
          Inject(() => SellLyric()),
          Inject(() => LyricsCopy()),
        ],
        initState: () {
          var lyric = Injector.get<SellLyric>();
          var store = Injector.get<AppDataBase>();
          lyric.inpacks = store.selectedlyric
              .inpacks; //set the initiale state of lyric so as not to rebuild
        },
        builder: (context) {
          return AddToPackScreen();
        },
      ),
    );
  }
}

// class AddToPackScreen extends StatelessWidget {
//   final contr = TextEditingController();

//   @override
//   Widget build(BuildContext context) {
//     return InsideAddToPackScreen();
//   }
// }

class AddToPackScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var lyric = Injector.getAsReactive<SellLyric>(context: context);
    var store = Injector.getAsReactive<AppDataBase>(context: context);
    return Scaffold(
      appBar: AppBar(
        title: Text(lyric.state.inpacks.toString()),
        leading: IconButton(
          icon: Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context, lyric.value),
        ),
      ),
      body: Column(children: [
        Expanded(
          child: ListView.builder(
            itemCount: store.state.packNames.length,
            itemBuilder: (BuildContext context, int index) {
              return ListTile(
                  onTap: () {
                    lyric.state.inpacks
                            .split(" ")
                            .contains(store.state.packNames.elementAt(index))
                        ? lyric.setState((state) {
                            var b = state.inpacks.split(" ");
                            b.removeWhere((value) =>
                                value ==
                                store.state.packNames.elementAt(index));
                            var v = b.join(" ");
                            print("1" + v);
                            state.inpacks = v;
                          })
                        : lyric.setState((state) {
                            var b = state.inpacks.split(" ");
                            b.add(store.state.packNames.elementAt(index));
                            var v = b.join(" ");
                            print("2" + v);
                            state.inpacks = v;
                          });
                  },
                  title: lyric.state.inpacks.split(" ").contains(
                              store.state.packNames.elementAt(index)) ==
                          true
                      ? Text(
                          store.state.packNames.elementAt(index).toString(),
                          style: TextStyle(backgroundColor: Colors.green),
                        )
                      : Text(store.state.packNames.elementAt(index).toString(),
                          style: TextStyle(backgroundColor: Colors.red)));
            },
          ),
        ),
        TextField(
          onSubmitted: (value) => lyric.setState((state) {
            var b = state.inpacks.split(" ");
            if (b.contains(value) == false) b.add(value);
            print("3" + b.join(" "));
            if (store.state.packNames.contains(value) == false)
              store.state.packNames.add(value);
            return state.inpacks = b.join(" ");
          }),
        ),
      ]),
    );
  }
}
```

**Comment by jmwatte** [comment]
Ok. Thanks.
