### ISSUE TITLE
Workiing with immutable state [new feature]

### ISSUE THREAD

**Issue by GIfatahTH** [GIfatahTH/states_rebuilder#82]
Immutable state has its fun and advantages, with this update you can work with immutable states just as fine as you do with mutable state.

Let's see this imaginary example: Fetching for a list of products and add a product to the list and persist the new list.

This is the fake repository used to fetch and persist the list of products
```dart
//fake repository
List<Product> _products = [Product('prod1'), Product('prod2')];
Future<List<Product>> fetchProductsRepo() {
  //simulate a delay
  return Future.delayed(
    Duration(seconds: 1),
    () {
      //simulate an error
      if (Random().nextBool()) {
        throw Exception('A Custom Message');
      }
      return _products;
    },
  );
}

Future addProductRepo(Product product) async {
  //simulate a delay
  await Future.delayed(
    Duration(seconds: 1),
    () {
      //simulate an error
      if (Random().nextBool()) {
        throw Exception('A Custom Message');
      }
      _products.add(product);
    },
  );
}
```
This is the simple `Product` model

```dart
//Product model
@immutable
class Product {
  final name;
  Product(this.name);
}
```
This is the immutable list Products state class
```dart
@immutable
class ProductsState {
  final List<Product> products;

  ProductsState(this.products);

  //methods in the ProductsState must return a new state of ProductsState.

  //We use Future want to show a CircularProgressIndicator while waiting for Products,
  Future<ProductsState> getProducts() async {
    final result = await fetchProductsRepo();
    return ProductsState(result);
  }

  //We use stream generator because we want to yield back the old state on error
  Stream<ProductsState> addProduct(Product product) async* {
    //yield the new state so States_rebuilder will update the UI to display it,
    yield ProductsState([...products, product]);
    try {
      await addProductRepo(product);
    } catch (e) {
      //yield the old state
      yield this;
      rethrow;
    }
  }
}
```
Notice that methods in the `ProductsState` are the event that trigger the transform from the actual state to the next state. Methods in the `ProductState` must returns a new instance of `ProductsState`.

In `fetchProducts` we returned Future because we want to wait for the asynchronous method to end and display a `CircularProgressIndicator`.

Whereas in `addProduct` we used a stream generator because we want to instantly display the new list (yield the new list) and execute in the background the asynchronous method. It is if the asynchronous method ends with an error, then we want to display the old list (yield the old list) and display a snackBar of the error.

Notice that in the same fashion as with mutable state, the business logic is a simple dart class.

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Injector(
      //inject ProductsState with empty list of product (this is the initial state)
      inject: [Inject(() => ProductsState([]))],
      builder: (context) {
        return MaterialApp(
          home: Scaffold(
            appBar: AppBar(),
            body: Center(
              child: WhenRebuilderOr<ProductsState>(
                //get the registered instance of ProductsState ReactiveModel
                observe: () => RM.get<ProductsState>()
                //use the cascade operator and invoke the future method to call getProducts
                  ..future(
                    (productState) => productState.getProducts(),
                    //If the future ends with error show an alert dialog
                  ).onError(_showErrorDialog),
                //While waiting for the future to end, display a CircularProgressIndicator
                onWaiting: () => Center(
                  child: CircularProgressIndicator(),
                ),
                builder: (context, productStateRM) {
                  final products = productStateRM.value.products;
                  return ListView.builder(
                    itemCount: products.length,
                    itemBuilder: (context, index) {
                      return ListTile(
                        title: Text('${products[index].name}'),
                      );
                    },
                  );
                },
              ),
            ),
            floatingActionButton: FloatingActionButton(
              child: Icon(Icons.add),
              onPressed: () {
                final newProduct = Product('prod ${Random().nextInt(100)}');
                //get the registered ProductsState ReactiveModel
                RM.get<ProductsState>()
                  //invoke the stream method and define the error side effect
                  .stream(
                    (productState) => productState.addProduct(newProduct),
                  ).onError(_showSnackBar);
              },
            ),
          ),
        );
      },
    );
  }

  void _showErrorDialog(BuildContext context, dynamic error) {
    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          content: Text('error.message'),
        );
      },
    );
  }

  void _showSnackBar(BuildContext context, dynamic error) {
    Scaffold.of(context).showSnackBar(
      SnackBar(
        content: Text('error.message'),
      ),
    );
  }
}
```

First, we injected `ProductsState` object with an initial state of an empty list.

```dart
 //inject ProductsState with empty list of product (this is the initial state)
      inject: [Inject(() => ProductsState([]))],
```

Then we called the `fetchProducts` method form the `observe` parameter of the `WhenRebuilderOr` widget.

```dart
observe: () => RM.get<ProductsState>()
//use the cascade operator and invoke the future method to call getProducts
    ..future(
    (productState) => productState.getProducts(),
    //If the future ends with error show an alert dialog
    ).onError(_showErrorDialog),
```
* By `RM.get<ProductsState>()` we get the actual registered `ReactiveModel` of the state in the service locator.
* By `..future((productState) => productState.getProducts(),)` we triggered the `getProducts` method add told state_builder that this method is a future, so state_builder changes the state status of the `ReactiveModel` to `isWaiting` to display the `CircularProgressIndicator` and when the future ends with data, `state_builder` change the registered instance in the service locator to hold the new state and notify observing widgets.
* By  `.onError(_showErrorDialog),` we told `state_builder` what to do if the future ends with and error.

See docs for more information on error handling.

To add a product in the onPressed callback : 

```dart
onPressed: () {
final newProduct = Product('prod ${Random().nextInt(100)}');
//get the registered ProductsState ReactiveModel
RM.get<ProductsState>()
    //invoke the stream method and define the error side effect
    .stream(
    (productState) => productState.addProduct(newProduct),
    ).onError(_showSnackBar);
},
```
* By `RM.get<ProductsState>()` we get the actual registered `ReactiveModel` of the state in the service locator.
* By `.stream((productState) => productState.addProduct(newProduct),)` we told `state_builder` that `addProduct` is a stream so it will subscribe to and notify observing widget on data emitting (yield).
* By  `.onError(_showSnackBar),` we told `state_builder` what to do if the stream emits an error.

Stream are automatically disposed of after they are done or when the `ReactiveModel` is disposed. So do not fear memory leakage.

**Comment by amoslai5128** [comment]
How many cool changes you gonna put it on the next release? I check it everyday LOL

Sorry for the dumb question, does immutable state work better than the mutable state? (preventing unwanted changes & better performance?)

**Comment by GIfatahTH** [comment]
>, does immutable state work better than the mutable state?

That is what experts have been saying.
