### ISSUE TITLE
How to track many RM models in StateBuilder?

### ISSUE THREAD

**Issue by pMertDogan** [GIfatahTH/states_rebuilder#86]
I have registered 2 or more ReactiveModel to observeMany parameter of the StateBuilder. First RM is local RM for changing text, second is global RM. My problem is I want track second RM model.

I read documents and i find Exposed Model
```
//first case : generic model is ModelA
StateBuilder<ModelA>(
  models:[modelA, modelB],
  builder:(context, exposedModel){
    //exposedModel is an instance of ReactiveModel<ModelA>.
  }
)
//second case : generic model is ModelB
StateBuilder<ModelB>(
  models:[modelA, modelB],
  builder:(context, exposedModel){
    //exposedModel is an instance of ReactiveModel<ModelB>.
  }
)
//third case : generic model is dynamic
StateBuilder(
  models:[modelA, modelB],
  builder:(context, exposedModel){
    //exposedModel is dynamic and it will change over time to hold the instance of model that emits a notification.
    
    //If modelA emits a notification the exposedModel == ReactiveModel<ModelA>.
    //Wheres if modelB emits a notification the exposedModel == ReactiveModel<ModelB>.
  }
)
```

Currently i was using this trick

```
...
    final userVMRM2 = RM.get<UserVM>();

...
          StateBuilder<String>(
            rmKey: loginRMKey,
            observeMany: [() => RM.create<String>("Login"), () => userVMRM2],
            builder: (context, loginButtonTxt) {
              return Tab(
                child: userVMRM2.isWaiting
                    ? lastTapIndex == 0
                        ? OrangeLoadingIndicator()
                        : Text(
                            "Please wait...",
                            style: Theme.of(context).textTheme.display1,
                          )
                    : Text(
                        loginButtonTxt.value,
                        style: Theme.of(context).textTheme.display1,
                      ),
              );
            },
          )
```

Its working but i think its litle tricky.Can you add some improvement about this? or Can you suggest a correct way?

**Comment by GIfatahTH** [comment]
* If you use observerMany, the exposed model is the model of the first model that has the type of the generic type you provide.
* If you provide rmKey, the exposed model as well the generic type must be of the ReactiveModel key.
* If you want to use more than one RMKey you have to use nested StateBuilders.

If I understand your intention, your example can be rewritten like this:

```dart
          WhenRebuilderOr<String>(
            rmKey: loginRMKey,
            observeMany: [() => RM.create<String>("Login"), () => userVMRM2],
            onWaiting: () =>  lastTapIndex == 0
                        ? OrangeLoadingIndicator()
                        : Text(
                            "Please wait...",
                            style: Theme.of(context).textTheme.display1,
                          ),
            builder: (context, loginButtonTxt) {
              return Tab(
                child: Text(
                        loginButtonTxt.value,
                        style: Theme.of(context).textTheme.display1,
                      ),
              );
            },
          )
```

**Comment by tk2232** [comment]
#83 I have a similar difficulty.

**Comment by pMertDogan** [comment]
> 
> 
>     * If you use observerMany, the exposed model is the model of the first model that has the type of the generic type you provide.
> 
>     * If you provide rmKey, the exposed model as well the generic type must be of the ReactiveModel key.
> 
>     * If you want to use more than one RMKey you have to use nested StateBuilders.
> 
> 
> If I understand your intention, your example can be rewritten like this:
> 
> ```dart
>           WhenRebuilderOr<String>(
>             rmKey: loginRMKey,
>             observeMany: [() => RM.create<String>("Login"), () => userVMRM2],
>             onWaiting: () =>  lastTapIndex == 0
>                         ? OrangeLoadingIndicator()
>                         : Text(
>                             "Please wait...",
>                             style: Theme.of(context).textTheme.display1,
>                           ),
>             builder: (context, loginButtonTxt) {
>               return Tab(
>                 child: Text(
>                         loginButtonTxt.value,
>                         style: Theme.of(context).textTheme.display1,
>                       ),
>               );
>             },
>           )
> ```

Thanks for code.I forget WhenRebuilderOr. 

 if you can add option to stateBuilder for track many RM its would be helpfull

**Comment by GIfatahTH** [comment]
Keys, in the next update, will have the ability to get the ReactiveModels created inside observeMany parameter : 
```dart
          StateBuilder<String>(
            rmKey: loginRMKey,
            observeMany: [() => RM.create<String>("Login"), () => RM.get<UserVM>()],
            builder: (context, loginButtonTxt) {
              return Tab(
                child: loginRMKey.get<UserVM>().isWaiting
                    ? lastTapIndex == 0
                        ? OrangeLoadingIndicator()
                        : Text(
                            "Please wait...",
                            style: Theme.of(context).textTheme.display1,
                          )
                    : Text(
                        loginButtonTxt.value,
                        style: Theme.of(context).textTheme.display1,
                      ),
              );
            },
          )
```

see #83

**Comment by pMertDogan** [comment]
Hi , thanks for update but is it possible add optional  builder parameter ?

Example:


```
          StateBuilder(
            observeMany: [
() => RM.create<String>("Login"), 
() => RM.get<UserVM>(),
() => RM.create<int>(0),
],
            builder: (context, stringRM , userVMRM , intRM) {
          return ....;
}   
```

**Comment by GIfatahTH** [comment]
Unfortunately, dart do not allow us to use optional parameter in the builder closure.
