### ISSUE TITLE
Different model instance in each Page ?

### ISSUE THREAD

**Issue by fabiobond** [GIfatahTH/states_rebuilder#88]
Hi, 
I've used this great library in one of my project and it was working well. It was version 1.11.
Now I've upgraded to 1.15 and many things seems to be changed. I cannot get any more a different model instance in each page

```
class PageBloc extends StatesRebuilder  {
  String key;
  PageBloc(this.key);
}
```

```
class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Injector(
        inject: [Inject<PageBloc>(() => PageBloc("Bloc1"))],
        builder: (context) {

          return Scaffold(
            appBar: AppBar(
              title: Text("Test States Rebuilder - Page 1"),
            ),
            body: StateBuilder<PageBloc>(
              models: [Injector.get<PageBloc>()],
              builder: (context, _) {
                PageBloc bloc = Injector.get<PageBloc>();
                return Center(
                  child: Text("This is ${bloc.key}"),
                );
              },
            ),
            floatingActionButton: FloatingActionButton(
                onPressed: () {
                    Navigator.of(context).push(MaterialPageRoute(builder: (context) => TestPage2()));
                },
                child: Icon(Icons.chevron_right)),
          );
        });
  }
}

class TestPage2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Injector(
        inject: [Inject<PageBloc>(() => PageBloc("Bloc2"))],
        builder: (context) {
          return Scaffold(
              appBar: AppBar(
                title: Text("Test States Rebuilder - Page 2"),
              ),
              body: StateBuilder<PageBloc>(
                models: [Injector.get<PageBloc>()],
                builder: (context, _) {
                  final bloc = Injector.get<PageBloc>();
                  return Center(
                    child: Text("This is ${bloc.key}"),
                  );
                },
              ),
          );
        });
  }
}
```

when I push TestPage2, I still get "This is Bloc 1" but I expected to have "This is Bloc 2"
The old version of the library was returning different instances on each page but I cannot get the same behaviour with the current version.

Can you point me in the right direction ? Using the "name" parameter in Injector works but this is not what I want.
Thanks.

**Comment by GIfatahTH** [comment]
Thanks for opening the issue and for using the library.

Yes, I removed the ability to inject the same model more than one time. A model should be injected only one time it the app, to inject another instance you have to use the name parameter.

Injecting a model more than once may lead to bugs, because states_rebuilder uses the service locator pattern for dependency injection where there is no guarantee you get the right instance for all the situations if you register many instances with the same name.

**Comment by fabiobond** [comment]
Thanks for your reply, this explain my problem.

So, if I need to access my model from a generic child widget down the tree, how can this be possible now ?
I cannot Inject the model using a name because my generic Widget would need to know the name to use to obtain its instance of the model. But this means that I've to pass the name to all children.
Should I use Provider for this?

**Comment by GIfatahTH** [comment]
If you can come with a demo example that would help me understand the case.

**Comment by GIfatahTH** [comment]
Feel free to reopen when you have a demo example.
