### ISSUE TITLE
Getting error even after injecting model 

### ISSUE THREAD

**Issue by aditya21** [GIfatahTH/states_rebuilder#95]
return Injector(
      inject: [
        Inject(
          () => CameraState(
            cameras: args['cameras'],
          ),
        ),
      ],
      builder: (context) {
----
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Builder(dirty, dependencies: [InheritedInject<CameraState>]):
'package:states_rebuilder/src/injector.dart': Failed assertion: line 159 pos 12: 'inheritedInject == null || (reactiveModel == inheritedInject.model)': is not true.

**Comment by GIfatahTH** [comment]
Please provide a full minimalistic example. I can not understand the context of your case

**Comment by GIfatahTH** [comment]
waiting for more clarification
