### ISSUE TITLE
what!!!!

### ISSUE THREAD

**Issue by gustavobrian** [GIfatahTH/states_rebuilder#97]
So much work and at once you changed all the interfaces ... it's practically another library ... why?
You update the project and PUMMM everything is destroyed ...
Thank you for your work, but I would like to understand what was the benefit of changing everything ..?
Thank you

**Comment by GIfatahTH** [comment]
I am sorry I now that breaking changes are not  welcome

I do not think that I changed all the interfaces. The main changes are:
* Remove the context subscription. (why #89 )
* Remove the `models `parameter and use `observe `and `observeMap`. (why #75 )
* Remove `setValue `and `value `(why #94 )
The remainder of the interface remains the same.

By these changes the API is clearer, and the internal code is less complex, this allows me to add more useful feature ;
* add the possibility to denounce, throttle a setState call #96
* setState is used for immutable and mutable. it is used with futures and streams #94
* Asynchronous dependency injection #91
* add ReactiveModel key #79
* performance 

 and many more

**Comment by lukepighetti** [comment]
In @GIfatahTH defense he did it under a major revision which is for breaking changes...
